<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_class_2026_0420.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import data_table
data_table.enable_dataframe_formatter()

df_wide = pd.DataFrame({
    'Weekday': ['Tuesday', 'Wednesday'],
    'Miami': [80, 83],
    'Rochester': [57, 62],
    'St. Louis': [71, 75]
})

df_wide

     Weekday  Miami  Rochester  St. Louis
0    Tuesday     80         57         71
1  Wednesday     83         62         75

In [2]:
df_long = pd.DataFrame({
    'Weekday': ['Tuesday', 'Wednesday', 'Tuesday', 'Wednesday', 'Tuesday', 'Wednesday'],
    'City': ['Miami', 'Miami', 'Rochester', 'Rochester', 'St. Louis', 'St. Louis'],
    'Temperature': [80, 83, 57, 62, 71, 75]
})

df_long

     Weekday       City  Temperature
0    Tuesday      Miami           80
1  Wednesday      Miami           83
2    Tuesday  Rochester           57
3  Wednesday  Rochester           62
4    Tuesday  St. Louis           71
5  Wednesday  St. Louis           75

# Example 1
Difference in temperature between Miami and Rochester on Tuesday and Wed.

In [3]:
df_wide['Miami'] - df_wide['Rochester']

0    23
1    21
dtype: int64

In [ ]:
df_long['Temperature']

# Example 2
Calculate average temperature across all cities and all days

In [4]:
df_long['Temperature'].mean()

np.float64(71.33333333333333)

In [ ]:
df_wide['Miami']
df_wide['Rochester']
df_wide['St. Louis']

In [5]:
df_wide['Miami'] + df_wide['Rochester'] + df_wide['St. Louis']

0    208
1    220
dtype: int64

# melt()

In [6]:
df_wide

     Weekday  Miami  Rochester  St. Louis
0    Tuesday     80         57         71
1  Wednesday     83         62         75

In [7]:
df_wide_to_long = (
    df_wide
    .melt()
)

df_wide_to_long

    variable      value
0    Weekday    Tuesday
1    Weekday  Wednesday
2      Miami         80
3      Miami         83
4  Rochester         57
5  Rochester         62
6  St. Louis         71
7  St. Louis         75

In [8]:
df_wide_to_long = (
    df_wide
    .melt(
        id_vars= ['Weekday']
    )
)

df_wide_to_long

     Weekday   variable  value
0    Tuesday      Miami     80
1  Wednesday      Miami     83
2    Tuesday  Rochester     57
3  Wednesday  Rochester     62
4    Tuesday  St. Louis     71
5  Wednesday  St. Louis     75

In [10]:
df_wide_to_long = (
    df_wide
    .melt(id_vars = "Weekday",
          var_name = "City",
          value_name = "Temperature")
)

df_wide_to_long

     Weekday       City  Temperature
0    Tuesday      Miami           80
1  Wednesday      Miami           83
2    Tuesday  Rochester           57
3  Wednesday  Rochester           62
4    Tuesday  St. Louis           71
5  Wednesday  St. Louis           75

In [11]:
df_wide_to_long = (
    df_wide
    .melt(id_vars = "Weekday",
          var_name = "Town",
          value_name = "Temp")
)

df_wide_to_long

     Weekday       Town  Temp
0    Tuesday      Miami    80
1  Wednesday      Miami    83
2    Tuesday  Rochester    57
3  Wednesday  Rochester    62
4    Tuesday  St. Louis    71
5  Wednesday  St. Louis    75

In [12]:
df_wide_to_long = (
    df_wide
    .melt(id_vars = "Day",
          var_name = "Town",
          value_name = "Temp")
)

df_wide_to_long

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['Day']"

In [13]:
df_long

     Weekday       City  Temperature
0    Tuesday      Miami           80
1  Wednesday      Miami           83
2    Tuesday  Rochester           57
3  Wednesday  Rochester           62
4    Tuesday  St. Louis           71
5  Wednesday  St. Louis           75

In [14]:
df_long_to_wide = (
    df_long
    .pivot(
        index = 'Weekday',
        columns= 'City',
        values = 'Temperature'
    )
)

df_long_to_wide

City       Miami  Rochester  St. Louis
Weekday
Tuesday       80         57         71
Wednesday     83         62         75

In [15]:
df_long_to_wide.columns

Index(['Miami', 'Rochester', 'St. Louis'], dtype='object', name='City')

In [16]:
df_long_to_wide = (
    df_long
    .pivot(
        index = 'Weekday',
        columns= 'City',
        values = 'Temperature'
    )
    .reset_index()
)

df_long_to_wide

City    Weekday  Miami  Rochester  St. Louis
0       Tuesday     80         57         71
1     Wednesday     83         62         75

In [17]:
dict_data = {"Name": ["Donna", "Donna", "Mike", "Mike"],
             "Department": ["ECON", "DANL", "ECON", "DANL"],
             "2022": [1, 2, 3, 1],
             "2023": [2, 3, 4, 2],
             "2024": [5, 1, 2, 2]}
df = pd.DataFrame(dict_data)

df

    Name Department  2022  2023  2024
0  Donna       ECON     1     2     5
1  Donna       DANL     2     3     1
2   Mike       ECON     3     4     2
3   Mike       DANL     1     2     2

In [18]:
df_longer = df.melt(id_vars=["Name", "Department"],
                    var_name="Year",
                    value_name="Number of Courses")

df_longer

     Name Department  Year  Number of Courses
0   Donna       ECON  2022                  1
1   Donna       DANL  2022                  2
2    Mike       ECON  2022                  3
3    Mike       DANL  2022                  1
4   Donna       ECON  2023                  2
5   Donna       DANL  2023                  3
6    Mike       ECON  2023                  4
7    Mike       DANL  2023                  2
8   Donna       ECON  2024                  5
9   Donna       DANL  2024                  1
10   Mike       ECON  2024                  2
11   Mike       DANL  2024                  2

In [19]:
df_wider = (
    df_longer
    .pivot(
        index = ["Name", "Department"],
        columns = 'Year',
        values = 'Number of Courses'
    )
    .reset_index()
)

df_wider

Year   Name Department  2022  2023  2024
0     Donna       DANL     2     3     1
1     Donna       ECON     1     2     5
2      Mike       DANL     1     2     2
3      Mike       ECON     3     4     2

# Classwork 15

# Question 1

Reshape ny_pincp to a longer format.

In [20]:
ny_pincp = pd.read_csv('https://bcdanl.github.io/data/NY_pinc_wide.csv')
ny_pincp

Warning: Total number of columns (58) exceeds max_columns (20). Falling back to pandas display.

,fips,geoname,pincp1969,pincp1970,pincp1971,pincp1972,pincp1973,pincp1974,pincp1975,pincp1976,...,pincp2015,pincp2016,pincp2017,pincp2018,pincp2019,pincp2020,pincp2021,pincp2022,pincp2023,pincp2024
0,36000,New York,4619,4920,5234,5603,6022,6533,7066,7510,...,56608,58400,62206,64229,66460,70412,76360,77461,81932,85552
1,36001,"Albany, NY",4272,4821,5304,5709,6154,6641,7184,7623,...,53320,53251,56786,57320,61768,67517,73579,73955,79282,83395
2,36003,"Allegany, NY",2928,3208,3424,3511,3831,4211,4513,4808,...,33811,34307,39331,39692,41277,41763,42357,40655,41741,44689
3,36005,"Bronx, NY",3632,3839,3999,4199,4497,4894,5373,5633,...,30776,31362,33218,34287,36922,42602,44384,42681,45142,46787
4,36007,"Broome, NY",3895,4153,4412,4700,5061,5517,5991,6393,...,38156,38541,40717,41572,43393,47364,50221,49216,52684,55337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,36115,"Washington, NY",3102,3385,3535,3746,4092,4458,4691,5040,...,35586,36336,38718,39517,41803,46397,48512,48477,51363,53847
59,36117,"Wayne, NY",3752,3854,4086,4342,4871,5408,5803,6140,...,40267,41430,43739,44779,47760,51570,54739,55141,57958,60489
60,36119,"Westchester, NY",6365,6682,7095,7550,8005,8704,9446,10042,...,89965,92351,98473,102241,105656,110091,120216,123313,131127,136419
61,36121,"Wyoming, NY",3360,3534,3803,4226,4705,5041,5351,5592,...,35619,36144,38395,38981,41691,46387,50532,50868,51117,53586
62,36123,"Yates, NY",3293,3497,3767,3898,4502,5149,5467,5736,...,34653,36229,38369,38696,42042,45702,49788,50708,52361,54652

In [21]:
ny_pincp_longer = (
    ny_pincp
    .melt(
        id_vars = ['fips', 'geoname'],
        var_name= 'Year',
        value_name= 'Income'
    )
)

ny_pincp_longer

       fips          geoname       Year  Income
0     36000         New York  pincp1969    4619
1     36001       Albany, NY  pincp1969    4272
2     36003     Allegany, NY  pincp1969    2928
3     36005        Bronx, NY  pincp1969    3632
4     36007       Broome, NY  pincp1969    3895
...     ...              ...        ...     ...
3523  36115   Washington, NY  pincp2024   53847
3524  36117        Wayne, NY  pincp2024   60489
3525  36119  Westchester, NY  pincp2024  136419
3526  36121      Wyoming, NY  pincp2024   53586
3527  36123        Yates, NY  pincp2024   54652

[3528 rows x 4 columns]

In [22]:
ny_pincp_longer = (
    ny_pincp
    .query('geoname != "New York"')
    .melt(
        id_vars = ['fips', 'geoname'],
        var_name= 'Year',
        value_name= 'Income'
    )
)

ny_pincp_longer

       fips          geoname       Year  Income
0     36001       Albany, NY  pincp1969    4272
1     36003     Allegany, NY  pincp1969    2928
2     36005        Bronx, NY  pincp1969    3632
3     36007       Broome, NY  pincp1969    3895
4     36009  Cattaraugus, NY  pincp1969    3139
...     ...              ...        ...     ...
3467  36115   Washington, NY  pincp2024   53847
3468  36117        Wayne, NY  pincp2024   60489
3469  36119  Westchester, NY  pincp2024  136419
3470  36121      Wyoming, NY  pincp2024   53586
3471  36123        Yates, NY  pincp2024   54652

[3472 rows x 4 columns]