<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_class_2026_0504.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

fortune1000 = pd.read_csv("https://bcdanl.github.io/data/fortune1000_2025.csv")
fortune = fortune1000[[
    "Rank", "Company", "Sector", "Industry",
    "Revenues_M", "Profits_M", "Number_of_Employees"
]]

In [2]:
fortune

,Rank,Company,Sector,Industry,Revenues_M,Profits_M,Number_of_Employees
0,1,Walmart,Retailing,General Merchandisers,680990.0,19440.0,2100000
1,2,Amazon,Retailing,Internet Services and Retailing,637960.0,59250.0,1560000
2,3,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,400280.0,14400.0,400000
3,4,Apple,Technology,"Computers, Office Equipment",391040.0,93740.0,164000
4,5,CVS Health,Health Care,Health Care: Pharmacy and Other Services,372810.0,4610.0,259500
...,...,...,...,...,...,...,...
995,996,Datadog,Technology,Computer Software,2680.0,183.7,6500
996,997,SBA Communications,Financials,Real estate,2680.0,749.5,1720
997,998,Quad/Graphics,Media,"Publishing, Printing",2670.0,-50.9,12200
998,999,Americold Realty Trust,Financials,Real estate,2670.0,-94.3,13760
999,1000,KinderCare Learning,Business Services,Education,2660.0,-92.8,43690

In [3]:
url_path = "https://bcdanl.github.io/data/fortune1000_2025_shuffled.csv"
fortune_shuffled = pd.read_csv(url_path)
sectors = fortune_shuffled.groupby("Sector")

fortune_shuffled

,Rank,Company,Ticker,Sector,Industry,City,State,Revenues_M,Profits_M,Assets,Market_Value,Number_of_Employees
0,522,Arista Networks,ANET,Technology,Network and Other Communications Equipment,Santa Clara,California,7000.0,2850.0,$14.04B,$97.71B,4410
1,738,Upbound Group,UPBD,Retailing,Specialty Retailers: Other,Plano,Texas,4320.0,123.5,$2.65B,$1.38B,11970
2,741,Hyster-Yale,HY,Industrials,Industrial Machinery,Cleveland,Ohio,4310.0,142.3,$2.03B,$735.1M,8500
3,661,First Horizon,FHN,Financials,Commercial Banks,Memphis,Tennessee,5030.0,775.0,$82.15B,$9.98B,7200
4,412,Celanese,CE,Chemicals,Chemicals,Irving,Texas,10280.0,-1520.0,$22.86B,$6.34B,12160
...,...,...,...,...,...,...,...,...,...,...,...,...
995,107,Abbott Laboratories,ABT,Health Care,Medical Products and Equipment,Abbott Park,Illinois,41950.0,13400.0,$81.41B,$230.06B,114000
996,271,Universal Health Services,UHS,Health Care,Health Care: Medical Facilities,King of Prussia,Pennsylvania,15830.0,1140.0,$14.47B,$12.21B,87500
997,861,Extra Space Storage,EXR,Financials,Real estate,Salt Lake City,Utah,3380.0,854.7,$28.85B,$31.48B,8010
998,436,KeyCorp,KEY,Financials,Commercial Banks,Cleveland,Ohio,9240.0,-161.0,$187.17B,$17.52B,16750
999,103,Dow,DOW,Chemicals,Chemicals,Midland,Michigan,42960.0,1120.0,$57.31B,$24.65B,36000

In [4]:
fortune_shuffled['Sector'].nunique()

21

In [5]:
fortune_shuffled['Sector'].value_counts()

Sector
Financials                       178
Technology                        99
Energy                            97
Retailing                         85
Health Care                       83
Business Services                 59
Industrials                       46
Materials                         45
Transportation                    37
Food, Beverages & Tobacco         36
Wholesalers                       33
Engineering & Construction        31
Hotels, Restaurants & Leisure     28
Media                             26
Chemicals                         24
Household Products                22
Aerospace & Defense               21
Motor Vehicles & Parts            19
Apparel                           14
Telecommunications                 9
Food & Drug Stores                 8
Name: count, dtype: int64

In [6]:
sectors.apply(lambda df: df.nlargest(1, "Revenues_M", keep="all"))

/tmp/ipykernel_834/1196263043.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sectors.apply(lambda df: df.nlargest(1, "Revenues_M", keep="all"))

,,Rank,Company,Ticker,Sector,Industry,City,State,Revenues_M,Profits_M,Assets,Market_Value,Number_of_Employees
Sector,,,,,,,,,,,,,
Aerospace & Defense,675,54,RTX,RTX,Aerospace & Defense,Aerospace & Defense,Arlington,Virginia,80740.0,4770.0,$162.86B,$176.85B,186000
Apparel,473,90,Nike,NKE,Apparel,Apparel,Beaverton,Oregon,51360.0,5700.0,$38.11B,$93.89B,79400
Business Services,549,127,Visa,V,Business Services,Financial Data Services,San Francisco,California,35930.0,19740.0,$94.51B,$685.9B,31600
Chemicals,999,103,Dow,DOW,Chemicals,Chemicals,Midland,Michigan,42960.0,1120.0,$57.31B,$24.65B,36000
Energy,298,8,Exxon Mobil,XOM,Energy,Petroleum Refining,Spring,Texas,349580.0,33680.0,$453.48B,$516.05B,60900
Engineering & Construction,726,123,D.R. Horton,DHI,Engineering & Construction,Homebuilders,Arlington,Texas,36800.0,4760.0,$36.1B,$40.06B,14770
Financials,259,6,Berkshire Hathaway,BRK.A,Financials,Insurance: Property and Casualty (Stock),Omaha,Nebraska,371430.0,89000.0,$1.15T,$1.15T,392400
Food & Drug Stores,138,26,Walgreens Boots Alliance,WBA,Food & Drug Stores,Food & Drug Stores,Deerfield,Illinois,147660.0,-8640.0,$81.04B,$9.66B,252500
"Food, Beverages & Tobacco",140,45,PepsiCo,PEP,"Food, Beverages & Tobacco",Food Consumer Products,Purchase,New York,91850.0,9580.0,$99.47B,$205.61B,319000
Health Care,225,3,UnitedHealth Group,UNH,Health Care,Health Care: Insurance and Managed Care,Eden Prairie,Minnesota,400280.0,14400.0,$298.28B,$479.08B,400000
"Hotels, Restaurants & Leisure",343,126,Starbucks,SBUX,"Hotels, Restaurants & Leisure",Food Services,Seattle,Washington,36180.0,3760.0,$31.34B,$111.42B,361000
Household Products,573,51,Procter & Gamble,PG,Household Products,Household and Personal Products,Cincinnati,Ohio,84040.0,14880.0,$122.37B,$399.61B,108000
Industrials,98,64,Caterpillar,CAT,Industrials,Construction and Farm Machinery,Irving,Texas,64810.0,10790.0,$87.76B,$157.62B,112900
Materials,31,140,Nucor,NUE,Materials,Metals,Charlotte,North Carolina,30730.0,2030.0,$33.94B,$27.77B,32700
Media,619,46,Walt Disney,DIS,Media,Entertainment,Burbank,California,91360.0,4970.0,$196.22B,$178.43B,205040
Motor Vehicles & Parts,600,18,General Motors,GM,Motor Vehicles & Parts,Motor Vehicles & Parts,Detroit,Michigan,187440.0,6010.0,$279.76B,$46.79B,162000
Retailing,334,1,Walmart,WMT,Retailing,General Merchandisers,Bentonville,Arkansas,680990.0,19440.0,$260.82B,$703.8B,2100000
Technology,240,4,Apple,AAPL,Technology,"Computers, Office Equipment",Cupertino,California,391040.0,93740.0,$364.98B,$3.34T,164000
Telecommunications,200,30,Verizon Communications,VZ,Telecommunications,Telecommunications,New York,New York,134790.0,17510.0,$384.71B,$190.95B,99600
Transportation,558,47,UPS,UPS,Transportation,"Mail, Package, and Freight Delivery",Atlanta,Georgia,91070.0,5780.0,$70.07B,$93.22B,372180
Wholesalers,135,56,Sysco,SYY,Wholesalers,Wholesalers: Food and Grocery,Houston,Texas,78840.0,1960.0,$24.92B,$36.71B,76000

In [7]:
sectors.apply(lambda df: df.nlargest(3, "Revenues_M", keep="all"))

/tmp/ipykernel_834/2538359886.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sectors.apply(lambda df: df.nlargest(3, "Revenues_M", keep="all"))

                         Rank                 Company Ticker  \
Sector
Aerospace & Defense 675    54                     RTX    RTX
                    959    59         Lockheed Martin    LMT
                    868    63                  Boeing     BA
Apparel             473    90                    Nike    NKE
                    341   405                      VF    VFC
...                       ...                     ...    ...
Transportation      626    49                   FedEx    FDX
                    353    70         Delta Air Lines    DAL
Wholesalers         135    56                   Sysco    SYY
                    139    73               TD Synnex    SNX
                    320    80  Performance Food Group   PFGC

                                      Sector  \
Sector
Aerospace & Defense 675  Aerospace & Defense
                    959  Aerospace & Defense
                    868  Aerospace & Defense
Apparel             473              Apparel
                    341              Apparel
...                                      ...
Transportation      626       Transportation
                    353       Transportation
Wholesalers         135          Wholesalers
                    139          Wholesalers
                    320          Wholesalers

                                                              Industry  \
Sector
Aerospace & Defense 675                            Aerospace & Defense
                    959                            Aerospace & Defense
                    868                            Aerospace & Defense
Apparel             473                                        Apparel
                    341                                        Apparel
...                                                                ...
Transportation      626            Mail, Package, and Freight Delivery
                    353                                       Airlines
Wholesalers         135                  Wholesalers: Food and Grocery
                    139  Wholesalers: Electronics and Office Equipment
                    320                  Wholesalers: Food and Grocery

                              City       State  Revenues_M  Profits_M  \
Sector
Aerospace & Defense 675  Arlington    Virginia     80740.0     4770.0
                    959   Bethesda    Maryland     71040.0     5340.0
                    868  Arlington    Virginia     66520.0   -11820.0
Apparel             473  Beaverton      Oregon     51360.0     5700.0
                    341     Denver    Colorado     10450.0     -968.9
...                            ...         ...         ...        ...
Transportation      626    Memphis   Tennessee     87690.0     4330.0
                    353    Atlanta     Georgia     61640.0     3460.0
Wholesalers         135    Houston       Texas     78840.0     1960.0
                    139    Fremont  California     58450.0      689.1
                    320   Richmond    Virginia     54680.0      435.9

                           Assets Market_Value  Number_of_Employees
Sector
Aerospace & Defense 675  $162.86B     $176.85B               186000
                    959   $55.62B     $104.79B               121000
                    868  $156.36B     $128.32B               172000
Apparel             473   $38.11B      $93.89B                79400
                    341   $11.61B       $6.05B                24000
...                           ...          ...                  ...
Transportation      626   $87.01B      $58.41B               422100
                    353   $75.37B      $28.16B               103000
Wholesalers         135   $24.92B      $36.71B                76000
                    139   $30.27B       $8.65B                25750
                    320   $13.39B      $12.28B                36810

[63 rows x 12 columns]

In [8]:
def get_nlargest_obs(df, n, var):
  return df.nlargest(n, var, keep="all")

In [9]:
sectors

In [10]:
sectors.apply(get_nlargest_obs)

TypeError: get_nlargest_obs() missing 2 required positional arguments: 'n' and 'var'

In [11]:
sectors.apply(get_nlargest_obs, 3, "Revenues_M")

/tmp/ipykernel_834/3870767964.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sectors.apply(get_nlargest_obs, 3, "Revenues_M")

                         Rank                 Company Ticker  \
Sector
Aerospace & Defense 675    54                     RTX    RTX
                    959    59         Lockheed Martin    LMT
                    868    63                  Boeing     BA
Apparel             473    90                    Nike    NKE
                    341   405                      VF    VFC
...                       ...                     ...    ...
Transportation      626    49                   FedEx    FDX
                    353    70         Delta Air Lines    DAL
Wholesalers         135    56                   Sysco    SYY
                    139    73               TD Synnex    SNX
                    320    80  Performance Food Group   PFGC

                                      Sector  \
Sector
Aerospace & Defense 675  Aerospace & Defense
                    959  Aerospace & Defense
                    868  Aerospace & Defense
Apparel             473              Apparel
                    341              Apparel
...                                      ...
Transportation      626       Transportation
                    353       Transportation
Wholesalers         135          Wholesalers
                    139          Wholesalers
                    320          Wholesalers

                                                              Industry  \
Sector
Aerospace & Defense 675                            Aerospace & Defense
                    959                            Aerospace & Defense
                    868                            Aerospace & Defense
Apparel             473                                        Apparel
                    341                                        Apparel
...                                                                ...
Transportation      626            Mail, Package, and Freight Delivery
                    353                                       Airlines
Wholesalers         135                  Wholesalers: Food and Grocery
                    139  Wholesalers: Electronics and Office Equipment
                    320                  Wholesalers: Food and Grocery

                              City       State  Revenues_M  Profits_M  \
Sector
Aerospace & Defense 675  Arlington    Virginia     80740.0     4770.0
                    959   Bethesda    Maryland     71040.0     5340.0
                    868  Arlington    Virginia     66520.0   -11820.0
Apparel             473  Beaverton      Oregon     51360.0     5700.0
                    341     Denver    Colorado     10450.0     -968.9
...                            ...         ...         ...        ...
Transportation      626    Memphis   Tennessee     87690.0     4330.0
                    353    Atlanta     Georgia     61640.0     3460.0
Wholesalers         135    Houston       Texas     78840.0     1960.0
                    139    Fremont  California     58450.0      689.1
                    320   Richmond    Virginia     54680.0      435.9

                           Assets Market_Value  Number_of_Employees
Sector
Aerospace & Defense 675  $162.86B     $176.85B               186000
                    959   $55.62B     $104.79B               121000
                    868  $156.36B     $128.32B               172000
Apparel             473   $38.11B      $93.89B                79400
                    341   $11.61B       $6.05B                24000
...                           ...          ...                  ...
Transportation      626   $87.01B      $58.41B               422100
                    353   $75.37B      $28.16B               103000
Wholesalers         135   $24.92B      $36.71B                76000
                    139   $30.27B       $8.65B                25750
                    320   $13.39B      $12.28B                36810

[63 rows x 12 columns]

In [15]:
def filter_by_threshold(df, column, threshold):
    threshold = df[column].quantile(.95)
    return df[ df[column] > threshold ]

sectors.apply(filter_by_threshold, "Revenues_M", 100000)

/tmp/ipykernel_834/1297249700.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sectors.apply(filter_by_threshold, "Revenues_M", 100000)

                                   Rank                   Company Ticker  \
Sector
Aerospace & Defense           675    54                       RTX    RTX
Apparel                       473    90                      Nike    NKE
Business Services             9     137           PayPal Holdings   PYPL
                              549   127                      Visa      V
                              676   152                Mastercard     MA
Chemicals                     373   174                        3M    MMM
                              999   103                       Dow    DOW
Energy                        234    34             Valero Energy    VLO
                              298     8               Exxon Mobil    XOM
                              365    29        Marathon Petroleum    MPC
                              513    16                   Chevron    CVX
                              855    28               Phillips 66    PSX
Engineering & Construction    726   123               D.R. Horton    DHI
                              871   129                    Lennar    LEN
Financials                    57     11            JPMorgan Chase    JPM
                              235    32       Goldman Sachs Group     GS
                              259     6        Berkshire Hathaway  BRK.A
                              400    25                Fannie Mae   FNMA
                              624    17           Bank of America    BAC
                              642    38               Freddie Mac   FMCC
                              809    36      State Farm Insurance      ~
                              850    33               Wells Fargo    WFC
                              992    21                 Citigroup      C
Food & Drug Stores            138    26  Walgreens Boots Alliance    WBA
Food, Beverages & Tobacco     140    45                   PepsiCo    PEP
                              223    50    Archer Daniels Midland    ADM
Health Care                   225     3        UnitedHealth Group    UNH
                              275    10                   Cencora    COR
                              435    13               Cigna Group     CI
                              683     9                  McKesson    MCK
                              834     5                CVS Health    CVS
Hotels, Restaurants & Leisure 343   126                 Starbucks   SBUX
                              364   165                McDonald's    MCD
Household Products            284   212         Colgate-Palmolive     CL
                              573    51          Procter & Gamble     PG
Industrials                   97     89                     Deere     DE
                              98     64               Caterpillar    CAT
                              271   119   Honeywell International    HON
Materials                     31    140                     Nucor    NUE
                              384   221          Cleveland-Cliffs    CLF
                              635   226       International Paper     IP
Media                         461   114    Warner Bros. Discovery    WBD
                              619    46               Walt Disney    DIS
Motor Vehicles & Parts        600    18            General Motors     GM
Retailing                     54     24                Home Depot     HD
                              334     1                   Walmart    WMT
                              482    12          Costco Wholesale   COST
                              915     2                    Amazon   AMZN
                              965    22            Meta Platforms   META
Technology                    55     31                    Nvidia   NVDA
                              240     4                     Apple   AAPL
                              374     7                  Alphabet  GOOGL
                              485    44         Dell Technologies   DELL
                              934    14                 Microsoft   MSFT
Telecommunications            200    30    Verizon Communications     VZ
Transportation                558    47                       UPS    UPS
                              626    49                     FedEx    FDX
Wholesalers                   135    56                     Sysco    SYY
                              139    73                 TD Synnex    SNX

                                                          Sector  \
Sector
Aerospace & Defense           675            Aerospace & Defense
Apparel                       473                        Apparel
Business Services             9                Business Services
                              549              Business Services
                              676              Business Services
Chemicals                     373                      Chemicals
                              999                      Chemicals
Energy                        234                         Energy
                              298                         Energy
                              365                         Energy
                              513                         Energy
                              855                         Energy
Engineering & Construction    726     Engineering & Construction
                              871     Engineering & Construction
Financials                    57                      Financials
                              235                     Financials
                              259                     Financials
                              400                     Financials
                              624                     Financials
                              642                     Financials
                              809                     Financials
                              850                     Financials
                              992                     Financials
Food & Drug Stores            138             Food & Drug Stores
Food, Beverages & Tobacco     140      Food, Beverages & Tobacco
                              223      Food, Beverages & Tobacco
Health Care                   225                    Health Care
                              275                    Health Care
                              435                    Health Care
                              683                    Health Care
                              834                    Health Care
Hotels, Restaurants & Leisure 343  Hotels, Restaurants & Leisure
                              364  Hotels, Restaurants & Leisure
Household Products            284             Household Products
                              573             Household Products
Industrials                   97                     Industrials
                              98                     Industrials
                              271                    Industrials
Materials                     31                       Materials
                              384                      Materials
                              635                      Materials
Media                         461                          Media
                              619                          Media
Motor Vehicles & Parts        600         Motor Vehicles & Parts
Retailing                     54                       Retailing
                              334                      Retailing
                              482                      Retailing
                              915                      Retailing
                              965                      Retailing
Technology                    55                      Technology
                              240                     Technology
                              374                     Technology
                              485                     Technology
                              934                     Technology
Telecommunications            200             Telecommunications
Transportation                558                 Transportation
                              626                 Transportation
Wholesalers                   135                    Wholesalers
                              139                    Wholesalers

                                                                         Industry  \
Sector
Aerospace & Defense           675                             Aerospace & Defense
Apparel                       473                                         Apparel
Business Services             9                           Financial Data Services
                              549                         Financial Data Services
                              676                         Financial Data Services
Chemicals                     373                                       Chemicals
                              999                                       Chemicals
Energy                        234                              Petroleum Refining
                              298                              Petroleum Refining
                              365                              Petroleum Refining
                              513                              Petroleum Refining
                              855                              Petroleum Refining
Engineering & Construction    726                                    Homebuilders
                              871                                    Homebuilders
Financials                    57                                 Commercial Banks
                              235                                Commercial Banks
                              259        Insurance: Property and Casualty (Stock)
                              400                          Diversified Financials
                              624                                Commercial Banks
                              642                          Diversified Financials
                              809       Insurance: Property and Casualty (Mutual)
                              850                                Commercial Banks
                              992                                Commercial Banks
Food & Drug Stores            138                              Food & Drug Stores
Food, Beverages & Tobacco     140                          Food Consumer Products
                              223                                 Food Production
Health Care                   225         Health Care: Insurance and Managed Care
                              275                        Wholesalers: Health Care
                              435        Health Care: Pharmacy and Other Services
                              683                        Wholesalers: Health Care
                              834        Health Care: Pharmacy and Other Services
Hotels, Restaurants & Leisure 343                                   Food Services
                              364                                   Food Services
Household Products            284                 Household and Personal Products
                              573                 Household and Personal Products
Industrials                   97                  Construction and Farm Machinery
                              98                  Construction and Farm Machinery
                              271                            Industrial Machinery
Materials                     31                                           Metals
                              384                                          Metals
                              635                           Packaging, Containers
Media                         461                                   Entertainment
                              619                                   Entertainment
Motor Vehicles & Parts        600                          Motor Vehicles & Parts
Retailing                     54                       Specialty Retailers: Other
                              334                           General Merchandisers
                              482                           General Merchandisers
                              915                 Internet Services and Retailing
                              965                 Internet Services and Retailing
Technology                    55   Semiconductors and Other Electronic Components
                              240                     Computers, Office Equipment
                              374                 Internet Services and Retailing
                              485                     Computers, Office Equipment
                              934                               Computer Software
Telecommunications            200                              Telecommunications
Transportation                558             Mail, Package, and Freight Delivery
                              626             Mail, Package, and Freight Delivery
Wholesalers                   135                   Wholesalers: Food and Grocery
                              139   Wholesalers: Electronics and Office Equipment

                                            City                 State  \
Sector
Aerospace & Defense           675      Arlington              Virginia
Apparel                       473      Beaverton                Oregon
Business Services             9         San Jose            California
                              549  San Francisco            California
                              676       Purchase              New York
Chemicals                     373       St. Paul             Minnesota
                              999        Midland              Michigan
Energy                        234    San Antonio                 Texas
                              298         Spring                 Texas
                              365        Findlay                  Ohio
                              513        Houston                 Texas
                              855        Houston                 Texas
Engineering & Construction    726      Arlington                 Texas
                              871          Miami               Florida
Financials                    57        New York              New York
                              235       New York              New York
                              259          Omaha              Nebraska
                              400     Washington  District Of Columbia
                              624      Charlotte        North Carolina
                              642         McLean              Virginia
                              809    Bloomington              Illinois
                              850  San Francisco            California
                              992       New York              New York
Food & Drug Stores            138      Deerfield              Illinois
Food, Beverages & Tobacco     140       Purchase              New York
                              223        Chicago              Illinois
Health Care                   225   Eden Prairie             Minnesota
                              275   Conshohocken          Pennsylvania
                              435     Bloomfield           Connecticut
                              683         Irving                 Texas
                              834     Woonsocket          Rhode Island
Hotels, Restaurants & Leisure 343        Seattle            Washington
                              364        Chicago              Illinois
Household Products            284       New York              New York
                              573     Cincinnati                  Ohio
Industrials                   97          Moline              Illinois
                              98          Irving                 Texas
                              271      Charlotte        North Carolina
Materials                     31       Charlotte        North Carolina
                              384      Cleveland                  Ohio
                              635        Memphis             Tennessee
Media                         461       New York              New York
                              619        Burbank            California
Motor Vehicles & Parts        600        Detroit              Michigan
Retailing                     54         Atlanta               Georgia
                              334    Bentonville              Arkansas
                              482       Issaquah            Washington
                              915        Seattle            Washington
                              965     Menlo Park            California
Technology                    55     Santa Clara            California
                              240      Cupertino            California
                              374  Mountain View            California
                              485     Round Rock                 Texas
                              934        Redmond            Washington
Telecommunications            200       New York              New York
Transportation                558        Atlanta               Georgia
                              626        Memphis             Tennessee
Wholesalers                   135        Houston                 Texas
                              139        Fremont            California

                                   Revenues_M  Profits_M    Assets  \
Sector
Aerospace & Defense           675     80740.0     4770.0  $162.86B
Apparel                       473     51360.0     5700.0   $38.11B
Business Services             9       31800.0     4150.0   $81.61B
                              549     35930.0    19740.0   $94.51B
                              676     28170.0    12870.0   $48.08B
Chemicals                     373     24570.0     4170.0   $39.87B
                              999     42960.0     1120.0   $57.31B
Energy                        234    123970.0     2770.0   $60.14B
                              298    349580.0    33680.0  $453.48B
                              365    140410.0     3440.0   $78.86B
                              513    202790.0    17660.0  $256.94B
                              855    145500.0     2120.0   $72.58B
Engineering & Construction    726     36800.0     4760.0    $36.1B
                              871     35440.0     3930.0   $41.31B
Financials                    57     278910.0    58470.0       $4T
                              235    126850.0    14280.0    $1.68T
                              259    371430.0    89000.0    $1.15T
                              400    152670.0    16980.0    $4.35T
                              624    192430.0    27130.0    $3.26T
                              642    122050.0    11860.0    $3.39T
                              809    122950.0     5290.0  $367.41B
                              850    125400.0    19720.0    $1.93T
                              992    170760.0    12680.0    $2.35T
Food & Drug Stores            138    147660.0    -8640.0   $81.04B
Food, Beverages & Tobacco     140     91850.0     9580.0   $99.47B
                              223     85530.0     1800.0   $53.27B
Health Care                   225    400280.0    14400.0  $298.28B
                              275    293960.0     1510.0    $67.1B
                              435    247120.0     3430.0  $155.88B
                              683    308950.0     3000.0   $67.44B
                              834    372810.0     4610.0  $253.22B
Hotels, Restaurants & Leisure 343     36180.0     3760.0   $31.34B
                              364     25920.0     8220.0   $55.18B
Household Products            284     20100.0     2890.0   $16.05B
                              573     84040.0    14880.0  $122.37B
Industrials                   97      51720.0     7100.0  $107.32B

In [18]:
fortune_shuffled["threshold"] = (
    fortune_shuffled
    .groupby('Sector')["Revenues_M"]
    .transform(
        lambda s: s.quantile(.95)
    )
)

In [19]:
fortune_shuffled

,Rank,Company,Ticker,Sector,Industry,City,State,Revenues_M,Profits_M,Assets,Market_Value,Number_of_Employees,threshold
0,522,Arista Networks,ANET,Technology,Network and Other Communications Equipment,Santa Clara,California,7000.0,2850.0,$14.04B,$97.71B,4410,66032.0
1,738,Upbound Group,UPBD,Retailing,Specialty Retailers: Other,Plano,Texas,4320.0,123.5,$2.65B,$1.38B,11970,148922.0
2,741,Hyster-Yale,HY,Industrials,Industrial Machinery,Cleveland,Ohio,4310.0,142.3,$2.03B,$735.1M,8500,37400.0
3,661,First Horizon,FHN,Financials,Commercial Banks,Memphis,Tennessee,5030.0,775.0,$82.15B,$9.98B,7200,109495.5
4,412,Celanese,CE,Chemicals,Chemicals,Irving,Texas,10280.0,-1520.0,$22.86B,$6.34B,12160,24349.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,107,Abbott Laboratories,ABT,Health Care,Medical Products and Equipment,Abbott Park,Illinois,41950.0,13400.0,$81.41B,$230.06B,114000,245091.0
996,271,Universal Health Services,UHS,Health Care,Health Care: Medical Facilities,King of Prussia,Pennsylvania,15830.0,1140.0,$14.47B,$12.21B,87500,245091.0
997,861,Extra Space Storage,EXR,Financials,Real estate,Salt Lake City,Utah,3380.0,854.7,$28.85B,$31.48B,8010,109495.5
998,436,KeyCorp,KEY,Financials,Commercial Banks,Cleveland,Ohio,9240.0,-161.0,$187.17B,$17.52B,16750,109495.5
999,103,Dow,DOW,Chemicals,Chemicals,Midland,Michigan,42960.0,1120.0,$57.31B,$24.65B,36000,24349.5

In [20]:
top5perc = fortune_shuffled[
    fortune_shuffled["Revenues_M"] >= fortune_shuffled['threshold']
]

top5perc

,Rank,Company,Ticker,Sector,Industry,City,State,Revenues_M,Profits_M,Assets,Market_Value,Number_of_Employees,threshold
9,137,PayPal Holdings,PYPL,Business Services,Financial Data Services,San Jose,California,31800.0,4150.0,$81.61B,$64.55B,24400,24525.0
31,140,Nucor,NUE,Materials,Metals,Charlotte,North Carolina,30730.0,2030.0,$33.94B,$27.77B,32700,18404.0
54,24,Home Depot,HD,Retailing,Specialty Retailers: Other,Atlanta,Georgia,159510.0,14810.0,$96.12B,$364.3B,470100,148922.0
55,31,Nvidia,NVDA,Technology,Semiconductors and Other Electronic Components,Santa Clara,California,130500.0,72880.0,$111.6B,$2.64T,36000,66032.0
57,11,JPMorgan Chase,JPM,Financials,Commercial Banks,New York,New York,278910.0,58470.0,$4T,$685.88B,317230,109495.5
97,89,Deere,DE,Industrials,Construction and Farm Machinery,Moline,Illinois,51720.0,7100.0,$107.32B,$127.39B,55520,37400.0
98,64,Caterpillar,CAT,Industrials,Construction and Farm Machinery,Irving,Texas,64810.0,10790.0,$87.76B,$157.62B,112900,37400.0
135,56,Sysco,SYY,Wholesalers,Wholesalers: Food and Grocery,Houston,Texas,78840.0,1960.0,$24.92B,$36.71B,76000,56188.0
138,26,Walgreens Boots Alliance,WBA,Food & Drug Stores,Food & Drug Stores,Deerfield,Illinois,147660.0,-8640.0,$81.04B,$9.66B,252500,147471.0
139,73,TD Synnex,SNX,Wholesalers,Wholesalers: Electronics and Office Equipment,Fremont,California,58450.0,689.1,$30.27B,$8.65B,25750,56188.0
140,45,PepsiCo,PEP,"Food, Beverages & Tobacco",Food Consumer Products,Purchase,New York,91850.0,9580.0,$99.47B,$205.61B,319000,61365.0
200,30,Verizon Communications,VZ,Telecommunications,Telecommunications,New York,New York,134790.0,17510.0,$384.71B,$190.95B,99600,130366.0
223,50,Archer Daniels Midland,ADM,"Food, Beverages & Tobacco",Food Production,Chicago,Illinois,85530.0,1800.0,$53.27B,$23.05B,43210,61365.0
225,3,UnitedHealth Group,UNH,Health Care,Health Care: Insurance and Managed Care,Eden Prairie,Minnesota,400280.0,14400.0,$298.28B,$479.08B,400000,245091.0
234,34,Valero Energy,VLO,Energy,Petroleum Refining,San Antonio,Texas,123970.0,2770.0,$60.14B,$41.53B,9910,90930.0
235,32,Goldman Sachs Group,GS,Financials,Commercial Banks,New York,New York,126850.0,14280.0,$1.68T,$176.09B,46500,109495.5
240,4,Apple,AAPL,Technology,"Computers, Office Equipment",Cupertino,California,391040.0,93740.0,$364.98B,$3.34T,164000,66032.0
259,6,Berkshire Hathaway,BRK.A,Financials,Insurance: Property and Casualty (Stock),Omaha,Nebraska,371430.0,89000.0,$1.15T,$1.15T,392400,109495.5
271,119,Honeywell International,HON,Industrials,Industrial Machinery,Charlotte,North Carolina,38500.0,5710.0,$75.2B,$137.38B,102000,37400.0
275,10,Cencora,COR,Health Care,Wholesalers: Health Care,Conshohocken,Pennsylvania,293960.0,1510.0,$67.1B,$53.87B,44000,245091.0
284,212,Colgate-Palmolive,CL,Household Products,Household and Personal Products,New York,New York,20100.0,2890.0,$16.05B,$76B,34000,20098.0
298,8,Exxon Mobil,XOM,Energy,Petroleum Refining,Spring,Texas,349580.0,33680.0,$453.48B,$516.05B,60900,90930.0
334,1,Walmart,WMT,Retailing,General Merchandisers,Bentonville,Arkansas,680990.0,19440.0,$260.82B,$703.8B,2100000,148922.0
343,126,Starbucks,SBUX,"Hotels, Restaurants & Leisure",Food Services,Seattle,Washington,36180.0,3760.0,$31.34B,$111.42B,361000,25633.0
364,165,McDonald's,MCD,"Hotels, Restaurants & Leisure",Food Services,Chicago,Illinois,25920.0,8220.0,$55.18B,$223.18B,150000,25633.0
365,29,Marathon Petroleum,MPC,Energy,Petroleum Refining,Findlay,Ohio,140410.0,3440.0,$78.86B,$45.39B,18300,90930.0
373,174,3M,MMM,Chemicals,Chemicals,St. Paul,Minnesota,24570.0,4170.0,$39.87B,$79.2B,61500,24349.5
374,7,Alphabet,GOOGL,Technology,Internet Services and Retailing,Mountain View,California,350020.0,100120.0,$450.26B,$1.89T,183320,66032.0
384,221,Cleveland-Cliffs,CLF,Materials,Metals,Cleveland,Ohio,19180.0,-754.0,$20.95B,$4.06B,30000,18404.0
400,25,Fannie Mae,FNMA,Financials,Diversified Financials,Washington,District Of Columbia,152670.0,16980.0,$4.35T,$7.32B,8200,109495.5
435,13,Cigna Group,CI,Health Care,Health Care: Pharmacy and Other Services,Bloomfield,Connecticut,247120.0,3430.0,$155.88B,$89.19B,72400,245091.0
461,114,Warner Bros. Discovery,WBD,Media,Entertainment,New York,New York,39320.0,-11310.0,$104.56B,$26.34B,35000,39240.0
473,90,Nike,NKE,Apparel,Apparel,Beaverton,Oregon,51360.0,5700.0,$38.11B,$93.89B,79400,24768.5
482,12,Costco Wholesale,COST,Retailing,General Merchandisers,Issaquah,Washington,254450.0,7370.0,$69.83B,$419.63B,333000,148922.0
485,44,Dell Technologies,DELL,Technology,"Computers, Office Equipment",Round Rock,Texas,95570.0,4590.0,$79.75B,$63.61B,108000,66032.0
513,16,Chevron,CVX,Energy,Petroleum Refining,Houston,Texas,202790.0,17660.0,$256.94B,$292.71B,45300,90930.0
549,127,Visa,V,Business Services,Financial Data Services,San Francisco,California,35930.0,19740.0,$94.51B,$685.9B,31600,24525.0
558,47,UPS,UPS,Transportation,"Mail, Package, and Freight Delivery",Atlanta,Georgia,91070.0,5780.0,$70.07B,$93.22B,372180,66850.0
573,51,Procter & Gamble,PG,Household Products,Household and Personal Products,Cincinnati,Ohio,84040.0,14880.0,$122.37B,$399.61B,108000,20098.0
600,18,General Motors,GM,Motor Vehicles & Parts,Motor Vehicles & Parts,Detroit,Michigan,187440.0,6010.0,$279.76B,$46.79B,162000,185235.0
619,46,Walt Disney,DIS,Media,Entertainment,Burbank,California,91360.0,4970.0,$196.22B,$178.43B,205040,39240.0
624,17,Bank of America,BAC,Financials,Commercial Banks,Charlotte,North Carolina,192430.0,27130.0,$3.26T,$317.26B,213190,109495.5
626,49,FedEx,FDX,Transportation,"Mail, Package, and Freight Delivery",Memphis,Tennessee,87690.0,4330.0,$87.01B,$58.41B,422100,66850.0
635,226,International Paper,IP,Materials,"Packaging, Containers",Memphis,Tennessee,18620.0,557.0,$22.8B,$28.07B,37000,18404.0
642,38,Freddie Mac,FMCC,Financials,Diversified Financials,McLean,Virginia,122050.0,11860.0,$3.39T,$3.48B,8090,109495.5
675,54,RTX,RTX,Aerospace & Defense,Aerospace & Defense,Arlington,Virginia,80740.0,4770.0,$162.86B,$176.85B,186000,71040.0
676,152,Mastercard,MA,Business Services,Financial Data Services,Purchase,New York,28170.0,12870.0,$48.08B,$499.73B,35300,24525.0
683,9,McKesson,MCK,Health Care,Wholesalers: Health Care,Irving,Texas,308950.0,3000.0,$67.44B,$84.34B,48000,245091.0
726,123,D.R. Horton,DHI,Engineering & Construction,Homebuilders,Arlington,Texas,36800.0,4760.0,$36.1B,$40.06B,14770,29555.0
809,36,State Farm Insurance,~,Financials,Insurance: Property and Casualty (Mutual),Bloomington,Illinois,122950.0,5290.0,$367.41B,~,67380,109495.5
834,5,CVS Health,CVS,Health Care,Health Care: Pharmacy and Other Services,Woonsocket,Rhode Island,372810.0,4610.0,$253.22B,$85.42B,259500,245091.0
850,33,Wells Fargo,WFC,Financials,Commercial Banks,San Francisco,California,125400.0,19720.0,$1.93T,$234.41B,217500,109495.5
855,28,Phillips 66,PSX,Energy,Petroleum Refining,Houston,Texas,145500.0,2120.0,$72.58B,$50.34B,13200,90930.0
871,129,Lennar,LEN,Engineering & Construction,Homebuilders,Miami,Florida,35440.0,3930.0,$41.31B,$30.16B,13270,29555.0
915,2,Amazon,AMZN,Retailing,Internet Services and Retailing,Seattle,Washington,637960.0,59250.0,$624.89B,$2.02T,1560000,148922.0
934,14,Microsoft,MSFT,Technology,Computer Software,Redmond,Washington,245120.0,88140.0,$512.16B,$2.79T,228000,66032.0
959,59,Lockheed Martin,LMT,Aerospace & Defense,Aerospace & Defense,Bethesda,Maryland,71040.0,5340.0,$55.62B,$104.79B,121000,71040.0
965,22,Meta Platforms,META,Retailing,Internet Services and Retailing,Menlo Park,California,164500.0,62360.0,$276.05B,$1.46T,74070,148922.0
992,21,Citigroup,C,Financials,Commercial Banks,New York,New York,170760.0,12680.0,$2.35T,$133.61B,227850,109495.5
999,103,Dow,DOW,Chemicals,Chemicals,Midland,Michigan,42960.0,1120.0,$57.31B,$24.65B,36000,24349.5

In [21]:
sectors.apply(lambda d, n: df.nlargest(2, "Revenues_M", keep="all"))

TypeError: <lambda>() missing 1 required positional argument: 'n'

# Classwork 17

In [22]:
cereal = pd.read_csv('https://bcdanl.github.io/data/cereals_oatmeal.csv')
cereal

                         Name    Manufacturer  Type  Calories  Fiber  Sugars
0                   100% Bran         Nabisco  Cold        70   10.0       6
1           100% Natural Bran     Quaker Oats  Cold       120    2.0       8
2                    All-Bran       Kellogg's  Cold        70    9.0       5
3   All-Bran with Extra Fiber       Kellogg's  Cold        50   14.0       0
4              Almond Delight  Ralston Purina  Cold       110    1.0       8
..                        ...             ...   ...       ...    ...     ...
72                    Triples   General Mills  Cold       110    0.0       3
73                       Trix   General Mills  Cold       110    0.0      12
74                 Wheat Chex  Ralston Purina  Cold       100    3.0       3
75                   Wheaties   General Mills  Cold       100    3.0       3
76        Wheaties Honey Gold   General Mills  Cold       110    1.0       8

[77 rows x 6 columns]

In [23]:
cereal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          77 non-null     object
 1   Manufacturer  77 non-null     object
 2   Type          77 non-null     object
 3   Calories      77 non-null     int64
 4   Fiber         77 non-null     float64
 5   Sugars        77 non-null     int64
dtypes: float64(1), int64(2), object(3)
memory usage: 3.7+ KB

## Q1
Group the data by Manufacturer, and determine the number of groups and the number of cereals per group.

In [26]:
cereal['Manufacturer'].unique()

array(['Nabisco', 'Quaker Oats', "Kellogg's", 'Ralston Purina',
       'General Mills', 'Post', 'American Home Food Products'],
      dtype=object)

In [27]:
cereal['Manufacturer'].nunique()

7

In [25]:
len(
    cereal.groupby('Manufacturer')
)

7

In [24]:
(
    cereal
    .groupby('Manufacturer')
    .size()
)

Manufacturer
American Home Food Products     1
General Mills                  22
Kellogg's                      23
Nabisco                         6
Post                            9
Quaker Oats                     8
Ralston Purina                  8
dtype: int64

In [40]:
(
    cereal['Manufacturer']
    .value_counts()
)

Manufacturer
Kellogg's                      23
General Mills                  22
Post                            9
Ralston Purina                  8
Quaker Oats                     8
Nabisco                         6
American Home Food Products     1
Name: count, dtype: int64

## Q2
Calculate the mean of the Calories, Fiber, and Sugars for every manufacturer.

In [28]:
q2 = (
    cereal
    .groupby('Manufacturer')
    .agg(
        Calories_mean = ("Calories", "mean"),
        Fiber_mean = ("Fiber", "mean"),
        Sugars_mean = ("Sugars", "mean"),

    )
)

q2

                             Calories_mean  Fiber_mean  Sugars_mean
Manufacturer
American Home Food Products     100.000000    0.000000     3.000000
General Mills                   111.363636    1.272727     7.954545
Kellogg's                       108.695652    2.739130     7.565217
Nabisco                          86.666667    4.000000     1.833333
Post                            108.888889    2.777778     8.777778
Quaker Oats                      95.000000    1.337500     5.250000
Ralston Purina                  115.000000    1.875000     6.125000

## Q3
Create a new DataFrame that includes the maximum Sugars and the minimum Fiber per manufacturer.

In [29]:
q3 = (
    cereal
    .groupby('Manufacturer')
    .agg(
        Sugars_max = ("Sugars", "max"),
        Fiber_min = ("Fiber", "min")
    )
)

q3

                             Sugars_max  Fiber_min
Manufacturer
American Home Food Products           3        0.0
General Mills                        14        0.0
Kellogg's                            15        0.0
Nabisco                               6        1.0
Post                                 15        0.0
Quaker Oats                          12        0.0
Ralston Purina                       11        0.0

## Q4
Add a Normalized_Sugars variable to the cereal DataFrame that standardizes each cereal’s sugar content within its manufacturer group.

In [31]:
cereal['Normalized_Sugars'] = (
    cereal
    .groupby('Manufacturer')['Sugars']
    .transform(
        lambda s: ( s - s.mean() ) / s.std()
    )
)

cereal

,Name,Manufacturer,Type,Calories,Fiber,Sugars,Normalized_Sugars
0,100% Bran,Nabisco,Cold,70,10.0,6,1.458030
1,100% Natural Bran,Quaker Oats,Cold,120,2.0,8,0.540062
2,All-Bran,Kellogg's,Cold,70,9.0,5,-0.569951
3,All-Bran with Extra Fiber,Kellogg's,Cold,50,14.0,0,-1.680872
4,Almond Delight,Ralston Purina,Cold,110,1.0,8,0.526212
...,...,...,...,...,...,...,...
72,Triples,General Mills,Cold,110,0.0,3,-1.279350
73,Trix,General Mills,Cold,110,0.0,12,1.044607
74,Wheat Chex,Ralston Purina,Cold,100,3.0,3,-0.877019
75,Wheaties,General Mills,Cold,100,3.0,3,-1.279350
76,Wheaties Honey Gold,General Mills,Cold,110,1.0,8,0.011737

## Q5
Put the two highest-sugar cereals for every manufacturer in a new DataFrame.

In [32]:
q5 = (
    cereal
    .groupby('Manufacturer')
    .apply(
        lambda df: df.nlargest(2, "Sugars", keep = "all")
    )
)

q5

/tmp/ipykernel_834/3996318948.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

                                                             Name  \
Manufacturer
American Home Food Products 43                              Maypo
General Mills               70                  Total Raisin Bran
                            14                        Cocoa Puffs
                            18                      Count Chocula
Kellogg's                   66                             Smacks
                            6                         Apple Jacks
Nabisco                     0                           100% Bran
                            68            Strawberry Fruit Wheats
Post                        30                       Golden Crisp
                            52              Post Nat. Raisin Bran
Quaker Oats                 10                       Cap'n'Crunch
                            35                   Honey Graham Ohs
Ralston Purina              44   Muesli Raisins; Dates; & Almonds
                            45  Muesli Raisins; Peaches; & Pecans

                                               Manufacturer  Type  Calories  \
Manufacturer
American Home Food Products 43  American Home Food Products   Hot       100
General Mills               70                General Mills  Cold       140
                            14                General Mills  Cold       110
                            18                General Mills  Cold       110
Kellogg's                   66                    Kellogg's  Cold       110
                            6                     Kellogg's  Cold       110
Nabisco                     0                       Nabisco  Cold        70
                            68                      Nabisco  Cold        90
Post                        30                         Post  Cold       100
                            52                         Post  Cold       120
Quaker Oats                 10                  Quaker Oats  Cold       120
                            35                  Quaker Oats  Cold       120
Ralston Purina              44               Ralston Purina  Cold       150
                            45               Ralston Purina  Cold       150

                                Fiber  Sugars  Normalized_Sugars
Manufacturer
American Home Food Products 43    0.0       3                NaN
General Mills               70    4.0      14           1.561042
                            14    0.0      13           1.302825
                            18    0.0      13           1.302825
Kellogg's                   66    1.0      15           1.651892
                            6     1.0      14           1.429708
Nabisco                     0    10.0       6           1.458030
                            68    3.0       5           1.108103
Post                        30    0.0      15           1.359600
                            52    6.0      14           1.141093
Quaker Oats                 10    0.0      12           1.325606
                            35    1.0      11           1.129220
Ralston Purina              44    3.0      11           1.368150
                            45    3.0      11           1.368150

## Q6
Compute the correlation between Calories and Sugars for each manufacturer.

corr() calculates the correlation between SERIES_1 and SERIES_2.

In [33]:
cereal["Calories"].corr( cereal["Sugars"] ) # returns a correlation value

np.float64(0.5623402898034883)

In [34]:

cereal[["Calories", "Sugars"]].corr() # returns a DataFrame of correlation matrix

          Calories   Sugars
Calories   1.00000  0.56234
Sugars     0.56234  1.00000

In [35]:

cereal[["Calories", "Sugars", "Fiber"]].corr() # returns a DataFrame of correlation matrix

          Calories    Sugars     Fiber
Calories  1.000000  0.562340 -0.293413
Sugars    0.562340  1.000000 -0.141205
Fiber    -0.293413 -0.141205  1.000000

In [36]:
q6 = (
    cereal
    .groupby('Manufacturer')[["Calories", "Sugars"]]
    .corr()
)

q6

                                      Calories    Sugars
Manufacturer
American Home Food Products Calories       NaN       NaN
                            Sugars         NaN       NaN
General Mills               Calories  1.000000  0.392839
                            Sugars    0.392839  1.000000
Kellogg's                   Calories  1.000000  0.548607
                            Sugars    0.548607  1.000000
Nabisco                     Calories  1.000000 -0.564692
                            Sugars   -0.564692  1.000000
Post                        Calories  1.000000  0.175624
                            Sugars    0.175624  1.000000
Quaker Oats                 Calories  1.000000  0.795361
                            Sugars    0.795361  1.000000
Ralston Purina              Calories  1.000000  0.769039
                            Sugars    0.769039  1.000000

In [38]:
def calc_corr(df, var_1, var_2):
  return df[var_1].corr( df[var_2] )

(
    cereal
    .groupby("Manufacturer")
    .apply(calc_corr, "Calories", "Sugars")
)

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2914: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
/tmp/ipykernel_834/3608158440.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_corr, "Calories", "Sugars")

Manufacturer
American Home Food Products         NaN
General Mills                  0.392839
Kellogg's                      0.548607
Nabisco                       -0.564692
Post                           0.175624
Quaker Oats                    0.795361
Ralston Purina                 0.769039
dtype: float64

In [39]:
def calc_corr(df, var_1, var_2):
  return df[[var_1, var_2]].corr()

(
    cereal
    .groupby("Manufacturer")
    .apply(calc_corr, "Calories", "Sugars")
)

/tmp/ipykernel_834/4074447678.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calc_corr, "Calories", "Sugars")

                                      Calories    Sugars
Manufacturer
American Home Food Products Calories       NaN       NaN
                            Sugars         NaN       NaN
General Mills               Calories  1.000000  0.392839
                            Sugars    0.392839  1.000000
Kellogg's                   Calories  1.000000  0.548607
                            Sugars    0.548607  1.000000
Nabisco                     Calories  1.000000 -0.564692
                            Sugars   -0.564692  1.000000
Post                        Calories  1.000000  0.175624
                            Sugars    0.175624  1.000000
Quaker Oats                 Calories  1.000000  0.795361
                            Sugars    0.795361  1.000000
Ralston Purina              Calories  1.000000  0.769039
                            Sugars    0.769039  1.000000