<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_class_2026_0327.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Below is to import the pandas library as pd
import pandas as pd

# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

# Below is to read nba.csv as nba DataFrame
nba = pd.read_csv("https://bcdanl.github.io/data/nba.csv",
                  parse_dates = ["Birthday"])

nba

/tmp/ipykernel_1428/153323233.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv("https://bcdanl.github.io/data/nba.csv",

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [2]:
nba['Salary_2x'] = nba['Salary'] + nba['Salary']
nba['Salary_3x'] = nba['Salary'] * 3

In [3]:
nba['Salary_k'] = nba['Salary'] / 1000

In [4]:
nba

,Name,Team,Position,Birthday,Salary,Salary_2x,Salary_3x,Salary_k
0,Shake Milton,Philadelphia 76ers,SG,1996-09-26,1445697,2891394,4337091,1445.697
1,Christian Wood,Detroit Pistons,PF,1995-09-27,1645357,3290714,4936071,1645.357
2,PJ Washington,Charlotte Hornets,PF,1998-08-23,3831840,7663680,11495520,3831.840
3,Derrick Rose,Detroit Pistons,PG,1988-10-04,7317074,14634148,21951222,7317.074
4,Marial Shayok,Philadelphia 76ers,G,1995-07-26,79568,159136,238704,79.568
...,...,...,...,...,...,...,...,...
445,Austin Rivers,Houston Rockets,PG,1992-08-01,2174310,4348620,6522930,2174.310
446,Harry Giles,Sacramento Kings,PF,1998-04-22,2578800,5157600,7736400,2578.800
447,Robin Lopez,Milwaukee Bucks,C,1988-04-01,4767000,9534000,14301000,4767.000
448,Collin Sexton,Cleveland Cavaliers,PG,1999-01-04,4764960,9529920,14294880,4764.960
449,Ricky Rubio,Phoenix Suns,PG,1990-10-21,16200000,32400000,48600000,16200.000

In [5]:
nba.drop(columns = 'Salary_k')

,Name,Team,Position,Birthday,Salary,Salary_2x,Salary_3x
0,Shake Milton,Philadelphia 76ers,SG,1996-09-26,1445697,2891394,4337091
1,Christian Wood,Detroit Pistons,PF,1995-09-27,1645357,3290714,4936071
2,PJ Washington,Charlotte Hornets,PF,1998-08-23,3831840,7663680,11495520
3,Derrick Rose,Detroit Pistons,PG,1988-10-04,7317074,14634148,21951222
4,Marial Shayok,Philadelphia 76ers,G,1995-07-26,79568,159136,238704
...,...,...,...,...,...,...,...
445,Austin Rivers,Houston Rockets,PG,1992-08-01,2174310,4348620,6522930
446,Harry Giles,Sacramento Kings,PF,1998-04-22,2578800,5157600,7736400
447,Robin Lopez,Milwaukee Bucks,C,1988-04-01,4767000,9534000,14301000
448,Collin Sexton,Cleveland Cavaliers,PG,1999-01-04,4764960,9529920,14294880
449,Ricky Rubio,Phoenix Suns,PG,1990-10-21,16200000,32400000,48600000

In [6]:
nba

,Name,Team,Position,Birthday,Salary,Salary_2x,Salary_3x,Salary_k
0,Shake Milton,Philadelphia 76ers,SG,1996-09-26,1445697,2891394,4337091,1445.697
1,Christian Wood,Detroit Pistons,PF,1995-09-27,1645357,3290714,4936071,1645.357
2,PJ Washington,Charlotte Hornets,PF,1998-08-23,3831840,7663680,11495520,3831.840
3,Derrick Rose,Detroit Pistons,PG,1988-10-04,7317074,14634148,21951222,7317.074
4,Marial Shayok,Philadelphia 76ers,G,1995-07-26,79568,159136,238704,79.568
...,...,...,...,...,...,...,...,...
445,Austin Rivers,Houston Rockets,PG,1992-08-01,2174310,4348620,6522930,2174.310
446,Harry Giles,Sacramento Kings,PF,1998-04-22,2578800,5157600,7736400,2578.800
447,Robin Lopez,Milwaukee Bucks,C,1988-04-01,4767000,9534000,14301000,4767.000
448,Collin Sexton,Cleveland Cavaliers,PG,1999-01-04,4764960,9529920,14294880,4764.960
449,Ricky Rubio,Phoenix Suns,PG,1990-10-21,16200000,32400000,48600000,16200.000

In [7]:
nba = nba.drop(columns = 'Salary_k')

In [8]:
nba

,Name,Team,Position,Birthday,Salary,Salary_2x,Salary_3x
0,Shake Milton,Philadelphia 76ers,SG,1996-09-26,1445697,2891394,4337091
1,Christian Wood,Detroit Pistons,PF,1995-09-27,1645357,3290714,4936071
2,PJ Washington,Charlotte Hornets,PF,1998-08-23,3831840,7663680,11495520
3,Derrick Rose,Detroit Pistons,PG,1988-10-04,7317074,14634148,21951222
4,Marial Shayok,Philadelphia 76ers,G,1995-07-26,79568,159136,238704
...,...,...,...,...,...,...,...
445,Austin Rivers,Houston Rockets,PG,1992-08-01,2174310,4348620,6522930
446,Harry Giles,Sacramento Kings,PF,1998-04-22,2578800,5157600,7736400
447,Robin Lopez,Milwaukee Bucks,C,1988-04-01,4767000,9534000,14301000
448,Collin Sexton,Cleveland Cavaliers,PG,1999-01-04,4764960,9529920,14294880
449,Ricky Rubio,Phoenix Suns,PG,1990-10-21,16200000,32400000,48600000

In [9]:
nba.drop(columns = ["Salary_2x", "Salary_3x"])
nba

,Name,Team,Position,Birthday,Salary,Salary_2x,Salary_3x
0,Shake Milton,Philadelphia 76ers,SG,1996-09-26,1445697,2891394,4337091
1,Christian Wood,Detroit Pistons,PF,1995-09-27,1645357,3290714,4936071
2,PJ Washington,Charlotte Hornets,PF,1998-08-23,3831840,7663680,11495520
3,Derrick Rose,Detroit Pistons,PG,1988-10-04,7317074,14634148,21951222
4,Marial Shayok,Philadelphia 76ers,G,1995-07-26,79568,159136,238704
...,...,...,...,...,...,...,...
445,Austin Rivers,Houston Rockets,PG,1992-08-01,2174310,4348620,6522930
446,Harry Giles,Sacramento Kings,PF,1998-04-22,2578800,5157600,7736400
447,Robin Lopez,Milwaukee Bucks,C,1988-04-01,4767000,9534000,14301000
448,Collin Sexton,Cleveland Cavaliers,PG,1999-01-04,4764960,9529920,14294880
449,Ricky Rubio,Phoenix Suns,PG,1990-10-21,16200000,32400000,48600000

In [10]:
nba = nba.drop(columns = ["Salary_2x", "Salary_3x"])
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [11]:
nba.columns

Index(['Name', 'Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [12]:
nba.columns = ['Name', 'Team', 'Position', 'Date of Birth', 'Salary']
nba

               Name                 Team Position Date of Birth    Salary
0      Shake Milton   Philadelphia 76ers       SG    1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF    1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF    1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG    1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G    1995-07-26     79568
..              ...                  ...      ...           ...       ...
445   Austin Rivers      Houston Rockets       PG    1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF    1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C    1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG    1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG    1990-10-21  16200000

[450 rows x 5 columns]

In [13]:
nba.rename(columns= {"Date of Birth" : "Birthday"})

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [14]:
nba

               Name                 Team Position Date of Birth    Salary
0      Shake Milton   Philadelphia 76ers       SG    1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF    1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF    1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG    1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G    1995-07-26     79568
..              ...                  ...      ...           ...       ...
445   Austin Rivers      Houston Rockets       PG    1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF    1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C    1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG    1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG    1990-10-21  16200000

[450 rows x 5 columns]

In [17]:
nba = nba.rename(columns= {"Date of Birth" : "Birthday"})
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [ ]:
(

)

In [18]:
nba_no_birthday = (
    nba
    .rename(columns= {"Birthday": "Date of Birth"})
    .drop(columns = "Date of Birth")
)

nba_no_birthday

               Name                 Team Position    Salary
0      Shake Milton   Philadelphia 76ers       SG   1445697
1    Christian Wood      Detroit Pistons       PF   1645357
2     PJ Washington    Charlotte Hornets       PF   3831840
3      Derrick Rose      Detroit Pistons       PG   7317074
4     Marial Shayok   Philadelphia 76ers        G     79568
..              ...                  ...      ...       ...
445   Austin Rivers      Houston Rockets       PG   2174310
446     Harry Giles     Sacramento Kings       PF   2578800
447     Robin Lopez      Milwaukee Bucks        C   4767000
448   Collin Sexton  Cleveland Cavaliers       PG   4764960
449     Ricky Rubio         Phoenix Suns       PG  16200000

[450 rows x 4 columns]

In [19]:
nba[ 'Name' ]  # Series

0        Shake Milton
1      Christian Wood
2       PJ Washington
3        Derrick Rose
4       Marial Shayok
            ...
445     Austin Rivers
446       Harry Giles
447       Robin Lopez
448     Collin Sexton
449       Ricky Rubio
Name: Name, Length: 450, dtype: object

In [20]:
nba[ ['Name'] ]  # DataFrame

               Name
0      Shake Milton
1    Christian Wood
2     PJ Washington
3      Derrick Rose
4     Marial Shayok
..              ...
445   Austin Rivers
446     Harry Giles
447     Robin Lopez
448   Collin Sexton
449     Ricky Rubio

[450 rows x 1 columns]

In [21]:
nba[ ['Name', 'Team'] ]

               Name                 Team
0      Shake Milton   Philadelphia 76ers
1    Christian Wood      Detroit Pistons
2     PJ Washington    Charlotte Hornets
3      Derrick Rose      Detroit Pistons
4     Marial Shayok   Philadelphia 76ers
..              ...                  ...
445   Austin Rivers      Houston Rockets
446     Harry Giles     Sacramento Kings
447     Robin Lopez      Milwaukee Bucks
448   Collin Sexton  Cleveland Cavaliers
449     Ricky Rubio         Phoenix Suns

[450 rows x 2 columns]

In [22]:
nba_player_name_team = nba[ ['Name', "Team"] ]

In [23]:
nba_player_name_team

               Name                 Team
0      Shake Milton   Philadelphia 76ers
1    Christian Wood      Detroit Pistons
2     PJ Washington    Charlotte Hornets
3      Derrick Rose      Detroit Pistons
4     Marial Shayok   Philadelphia 76ers
..              ...                  ...
445   Austin Rivers      Houston Rockets
446     Harry Giles     Sacramento Kings
447     Robin Lopez      Milwaukee Bucks
448   Collin Sexton  Cleveland Cavaliers
449     Ricky Rubio         Phoenix Suns

[450 rows x 2 columns]

In [24]:
nba_player_team_name = nba[ ['Team', 'Name'] ]
nba_player_team_name

                    Team            Name
0     Philadelphia 76ers    Shake Milton
1        Detroit Pistons  Christian Wood
2      Charlotte Hornets   PJ Washington
3        Detroit Pistons    Derrick Rose
4     Philadelphia 76ers   Marial Shayok
..                   ...             ...
445      Houston Rockets   Austin Rivers
446     Sacramento Kings     Harry Giles
447      Milwaukee Bucks     Robin Lopez
448  Cleveland Cavaliers   Collin Sexton
449         Phoenix Suns     Ricky Rubio

[450 rows x 2 columns]

# Classwork 10

## Question 1

In [25]:
nfl = pd.read_csv("https://bcdanl.github.io/data/nfl.csv")
nfl

                    Name                  Team Position    Birthday   Salary
0           Tremon Smith   Philadelphia Eagles       RB   7/20/1996   570000
1         Shawn Williams    Cincinnati Bengals       SS   5/13/1991  3500000
2            Adam Butler  New England Patriots       DT   4/12/1994   645000
3            Derek Wolfe        Denver Broncos       DE   2/24/1990  8000000
4              Jake Ryan  Jacksonville Jaguars      OLB   2/27/1992  1000000
...                  ...                   ...      ...         ...      ...
1650    Bashaud Breeland    Kansas City Chiefs       CB   1/30/1992   805000
1651         Craig James   Philadelphia Eagles       CB   4/29/1996   570000
1652  Jonotthan Harrison         New York Jets        C   8/25/1991  1500000
1653         Chuma Edoga         New York Jets       OT   5/25/1997   495000
1654        Tajae Sharpe      Tennessee Titans       WR  12/23/1994  2025000

[1655 rows x 5 columns]

What is an effective way to convert the values in its Birthday variable to datetimes?

In [45]:
nfl = pd.read_csv("https://bcdanl.github.io/data/nfl.csv",
                  parse_dates=['Birthday'])
nfl

                    Name                  Team Position   Birthday   Salary
0           Tremon Smith   Philadelphia Eagles       RB 1996-07-20   570000
1         Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
2            Adam Butler  New England Patriots       DT 1994-04-12   645000
3            Derek Wolfe        Denver Broncos       DE 1990-02-24  8000000
4              Jake Ryan  Jacksonville Jaguars      OLB 1992-02-27  1000000
...                  ...                   ...      ...        ...      ...
1650    Bashaud Breeland    Kansas City Chiefs       CB 1992-01-30   805000
1651         Craig James   Philadelphia Eagles       CB 1996-04-29   570000
1652  Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
1653         Chuma Edoga         New York Jets       OT 1997-05-25   495000
1654        Tajae Sharpe      Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 5 columns]

In [46]:
nfl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1655 entries, 0 to 1654
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      1655 non-null   object
 1   Team      1655 non-null   object
 2   Position  1655 non-null   object
 3   Birthday  1655 non-null   datetime64[ns]
 4   Salary    1655 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 64.8+ KB

## Question 2


- How many observations are in nfl?
- What are the mean, median, standard deviation, minimum, and maximum of Salary in nfl?

In [47]:
nfl.shape

(1655, 5)

In [27]:
nfl.shape[0]

1655

In [28]:
nfl['Salary'].describe()

count    1.655000e+03
mean     1.861569e+06
std      2.748519e+06
min      3.780000e+05
25%      5.700000e+05
50%      8.000000e+05
75%      1.839952e+06
max      2.750000e+07
Name: Salary, dtype: float64

In [48]:
nfl[['Salary']].describe()

             Salary
count  1.655000e+03
mean   1.861569e+06
std    2.748519e+06
min    3.780000e+05
25%    5.700000e+05
50%    8.000000e+05
75%    1.839952e+06
max    2.750000e+07

## Question 3

- What are the maximum and minimum values of Salary in nfl?
- What is the 75th percentile of Salary in nfl?

In [49]:
# below syntax works for max(), but I do not recommend in general when working with pandas
max( nfl['Salary'] )

27500000

In [29]:
nfl['Salary'].max()

27500000

In [30]:
nfl['Salary'].min()

378000

In [33]:
nfl['Salary'].quantile(.75)

np.float64(1839952.0)

In [50]:
quantile(nfl['Salary'], .75)

NameError: name 'quantile' is not defined

## Question 4
- Create a new Series that concatenates each player’s Name and Position in the format Name (Position) using a vectorized string operation.
- Create a new Series that shows how much each player’s Salary deviates from the mean salary.

In [34]:
nfl['Name'] + ' (' + nfl['Position'] + ')'

0            Tremon Smith (RB)
1          Shawn Williams (SS)
2             Adam Butler (DT)
3             Derek Wolfe (DE)
4              Jake Ryan (OLB)
                 ...
1650     Bashaud Breeland (CB)
1651          Craig James (CB)
1652    Jonotthan Harrison (C)
1653          Chuma Edoga (OT)
1654         Tajae Sharpe (WR)
Length: 1655, dtype: object

In [35]:
nfl['Salary'] -  nfl['Salary'].mean()

0      -1.291569e+06
1       1.638431e+06
2      -1.216569e+06
3       6.138431e+06
4      -8.615690e+05
            ...
1650   -1.056569e+06
1651   -1.291569e+06
1652   -3.615690e+05
1653   -1.366569e+06
1654    1.634310e+05
Name: Salary, Length: 1655, dtype: float64

## Question 5

- How can we select only the `Name` and `Team` variables from `nfl` as a DataFrame?
- How can we reorder the variables so that `Team` appears before `Name`?

In [36]:
nfl.columns

Index(['Name', 'Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [37]:
nfl_selected = nfl[ ['Name', 'Team'] ]
nfl_selected

                    Name                  Team
0           Tremon Smith   Philadelphia Eagles
1         Shawn Williams    Cincinnati Bengals
2            Adam Butler  New England Patriots
3            Derek Wolfe        Denver Broncos
4              Jake Ryan  Jacksonville Jaguars
...                  ...                   ...
1650    Bashaud Breeland    Kansas City Chiefs
1651         Craig James   Philadelphia Eagles
1652  Jonotthan Harrison         New York Jets
1653         Chuma Edoga         New York Jets
1654        Tajae Sharpe      Tennessee Titans

[1655 rows x 2 columns]

In [38]:
nfl

                    Name                  Team Position   Birthday   Salary
0           Tremon Smith   Philadelphia Eagles       RB 1996-07-20   570000
1         Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
2            Adam Butler  New England Patriots       DT 1994-04-12   645000
3            Derek Wolfe        Denver Broncos       DE 1990-02-24  8000000
4              Jake Ryan  Jacksonville Jaguars      OLB 1992-02-27  1000000
...                  ...                   ...      ...        ...      ...
1650    Bashaud Breeland    Kansas City Chiefs       CB 1992-01-30   805000
1651         Craig James   Philadelphia Eagles       CB 1996-04-29   570000
1652  Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
1653         Chuma Edoga         New York Jets       OT 1997-05-25   495000
1654        Tajae Sharpe      Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 5 columns]

In [39]:
nfl = nfl[
    ['Team', 'Name', 'Position', 'Birthday', 'Salary']
    ]

nfl

                      Team                Name Position   Birthday   Salary
0      Philadelphia Eagles        Tremon Smith       RB 1996-07-20   570000
1       Cincinnati Bengals      Shawn Williams       SS 1991-05-13  3500000
2     New England Patriots         Adam Butler       DT 1994-04-12   645000
3           Denver Broncos         Derek Wolfe       DE 1990-02-24  8000000
4     Jacksonville Jaguars           Jake Ryan      OLB 1992-02-27  1000000
...                    ...                 ...      ...        ...      ...
1650    Kansas City Chiefs    Bashaud Breeland       CB 1992-01-30   805000
1651   Philadelphia Eagles         Craig James       CB 1996-04-29   570000
1652         New York Jets  Jonotthan Harrison        C 1991-08-25  1500000
1653         New York Jets         Chuma Edoga       OT 1997-05-25   495000
1654      Tennessee Titans        Tajae Sharpe       WR 1994-12-23  2025000

[1655 rows x 5 columns]

## Question 6
- Add a new variable Salary_k to nfl that expresses Salary in thousands of dollars.
- Add another new variable Salary_2x to nfl that doubles the original Salary.

In [40]:
nfl['Salary_k'] = nfl['Salary'] / 1000
nfl['Salary_2x'] = nfl['Salary'] * 2
nfl

/tmp/ipykernel_1428/1887696050.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nfl['Salary_k'] = nfl['Salary'] / 1000
/tmp/ipykernel_1428/1887696050.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nfl['Salary_2x'] = nfl['Salary'] * 2

,Team,Name,Position,Birthday,Salary,Salary_k,Salary_2x
0,Philadelphia Eagles,Tremon Smith,RB,1996-07-20,570000,570.0,1140000
1,Cincinnati Bengals,Shawn Williams,SS,1991-05-13,3500000,3500.0,7000000
2,New England Patriots,Adam Butler,DT,1994-04-12,645000,645.0,1290000
3,Denver Broncos,Derek Wolfe,DE,1990-02-24,8000000,8000.0,16000000
4,Jacksonville Jaguars,Jake Ryan,OLB,1992-02-27,1000000,1000.0,2000000
...,...,...,...,...,...,...,...
1650,Kansas City Chiefs,Bashaud Breeland,CB,1992-01-30,805000,805.0,1610000
1651,Philadelphia Eagles,Craig James,CB,1996-04-29,570000,570.0,1140000
1652,New York Jets,Jonotthan Harrison,C,1991-08-25,1500000,1500.0,3000000
1653,New York Jets,Chuma Edoga,OT,1997-05-25,495000,495.0,990000
1654,Tennessee Titans,Tajae Sharpe,WR,1994-12-23,2025000,2025.0,4050000

## Question 7
Remove the variables Salary_k and Salary_2x from nfl.

In [41]:
nfl.columns

Index(['Team', 'Name', 'Position', 'Birthday', 'Salary', 'Salary_k',
       'Salary_2x'],
      dtype='object')

In [42]:
nfl = nfl[['Team', 'Name', 'Position', 'Birthday', 'Salary']]
nfl

                      Team                Name Position   Birthday   Salary
0      Philadelphia Eagles        Tremon Smith       RB 1996-07-20   570000
1       Cincinnati Bengals      Shawn Williams       SS 1991-05-13  3500000
2     New England Patriots         Adam Butler       DT 1994-04-12   645000
3           Denver Broncos         Derek Wolfe       DE 1990-02-24  8000000
4     Jacksonville Jaguars           Jake Ryan      OLB 1992-02-27  1000000
...                    ...                 ...      ...        ...      ...
1650    Kansas City Chiefs    Bashaud Breeland       CB 1992-01-30   805000
1651   Philadelphia Eagles         Craig James       CB 1996-04-29   570000
1652         New York Jets  Jonotthan Harrison        C 1991-08-25  1500000
1653         New York Jets         Chuma Edoga       OT 1997-05-25   495000
1654      Tennessee Titans        Tajae Sharpe       WR 1994-12-23  2025000

[1655 rows x 5 columns]

## Question 7
Rename the variable Birthday to Date of Birth in nfl.

In [43]:
nfl = nfl.rename(columns = {'Birthday' : 'Date of Birth'})
nfl

                      Team                Name Position Date of Birth   Salary
0      Philadelphia Eagles        Tremon Smith       RB    1996-07-20   570000
1       Cincinnati Bengals      Shawn Williams       SS    1991-05-13  3500000
2     New England Patriots         Adam Butler       DT    1994-04-12   645000
3           Denver Broncos         Derek Wolfe       DE    1990-02-24  8000000
4     Jacksonville Jaguars           Jake Ryan      OLB    1992-02-27  1000000
...                    ...                 ...      ...           ...      ...
1650    Kansas City Chiefs    Bashaud Breeland       CB    1992-01-30   805000
1651   Philadelphia Eagles         Craig James       CB    1996-04-29   570000
1652         New York Jets  Jonotthan Harrison        C    1991-08-25  1500000
1653         New York Jets         Chuma Edoga       OT    1997-05-25   495000
1654      Tennessee Titans        Tajae Sharpe       WR    1994-12-23  2025000

[1655 rows x 5 columns]

In [ ]:
# nfl.columns = [...]

# Counting Methods

In [52]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    datetime64[ns]
 4   Salary    450 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 17.7+ KB

In [51]:
nba['Salary'].count()

np.int64(450)

In [53]:
nba[['Salary']].count()

Salary    450
dtype: int64

In [54]:
nba['Team'].value_counts()

Team
Philadelphia 76ers        17
Brooklyn Nets             17
Utah Jazz                 17
Minnesota Timberwolves    17
Charlotte Hornets         16
Detroit Pistons           16
New Orleans Pelicans      16
New York Knicks           16
Boston Celtics            16
Chicago Bulls             16
Toronto Raptors           16
Los Angeles Lakers        16
Atlanta Hawks             15
Miami Heat                15
Denver Nuggets            15
Golden State Warriors     15
Sacramento Kings          15
Phoenix Suns              15
Memphis Grizzlies         15
Washington Wizards        14
Milwaukee Bucks           14
Los Angeles Clippers      14
Houston Rockets           14
San Antonio Spurs         14
Portland Trail Blazers    14
Cleveland Cavaliers       13
Oklahoma City Thunder     13
Orlando Magic             13
Dallas Mavericks          13
Indiana Pacers            13
Name: count, dtype: int64

In [55]:
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [56]:
nba[['Team']].value_counts()

Team
Brooklyn Nets             17
Minnesota Timberwolves    17
Philadelphia 76ers        17
Utah Jazz                 17
Chicago Bulls             16
Boston Celtics            16
New Orleans Pelicans      16
Charlotte Hornets         16
Toronto Raptors           16
New York Knicks           16
Los Angeles Lakers        16
Detroit Pistons           16
Golden State Warriors     15
Atlanta Hawks             15
Sacramento Kings          15
Phoenix Suns              15
Miami Heat                15
Memphis Grizzlies         15
Denver Nuggets            15
Los Angeles Clippers      14
Milwaukee Bucks           14
Houston Rockets           14
San Antonio Spurs         14
Washington Wizards        14
Portland Trail Blazers    14
Cleveland Cavaliers       13
Indiana Pacers            13
Dallas Mavericks          13
Orlando Magic             13
Oklahoma City Thunder     13
Name: count, dtype: int64

In [57]:
nba['Team'].value_counts()

Team
Philadelphia 76ers        17
Brooklyn Nets             17
Utah Jazz                 17
Minnesota Timberwolves    17
Charlotte Hornets         16
Detroit Pistons           16
New Orleans Pelicans      16
New York Knicks           16
Boston Celtics            16
Chicago Bulls             16
Toronto Raptors           16
Los Angeles Lakers        16
Atlanta Hawks             15
Miami Heat                15
Denver Nuggets            15
Golden State Warriors     15
Sacramento Kings          15
Phoenix Suns              15
Memphis Grizzlies         15
Washington Wizards        14
Milwaukee Bucks           14
Los Angeles Clippers      14
Houston Rockets           14
San Antonio Spurs         14
Portland Trail Blazers    14
Cleveland Cavaliers       13
Oklahoma City Thunder     13
Orlando Magic             13
Dallas Mavericks          13
Indiana Pacers            13
Name: count, dtype: int64