<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_class_2026_0325.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
nba = pd.read_csv("https://bcdanl.github.io/data/nba.csv")

In [2]:
type(nba)

pandas.core.frame.DataFrame

In [3]:
nba

               Name                 Team Position  Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG   9/26/96   1445697
1    Christian Wood      Detroit Pistons       PF   9/27/95   1645357
2     PJ Washington    Charlotte Hornets       PF   8/23/98   3831840
3      Derrick Rose      Detroit Pistons       PG   10/4/88   7317074
4     Marial Shayok   Philadelphia 76ers        G   7/26/95     79568
..              ...                  ...      ...       ...       ...
445   Austin Rivers      Houston Rockets       PG    8/1/92   2174310
446     Harry Giles     Sacramento Kings       PF   4/22/98   2578800
447     Robin Lopez      Milwaukee Bucks        C    4/1/88   4767000
448   Collin Sexton  Cleveland Cavaliers       PG    1/4/99   4764960
449     Ricky Rubio         Phoenix Suns       PG  10/21/90  16200000

[450 rows x 5 columns]

In [4]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    object
 4   Salary    450 non-null    int64
dtypes: int64(1), object(4)
memory usage: 17.7+ KB

In [5]:
nba = pd.read_csv("https://bcdanl.github.io/data/nba.csv",
                  parse_dates = ["Birthday"])
nba

/tmp/ipykernel_1056/2686974663.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv("https://bcdanl.github.io/data/nba.csv",

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [6]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    datetime64[ns]
 4   Salary    450 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 17.7+ KB

In [7]:
from google.colab import drive, files
drive.mount('/content/drive')
files.upload()

Mounted at /content/drive

Saving taylor_albums.csv to taylor_albums.csv

{'taylor_albums.csv': b"album_name,ep,album_release,metacritic_score,user_score\nTaylor Swift,FALSE,2006-10-24,67,8.4\nThe Taylor Swift Holiday Collection,TRUE,2007-10-14,NA,NA\nBeautiful Eyes,TRUE,2008-07-15,NA,NA\nFearless,FALSE,2008-11-11,73,8.4\nSpeak Now,FALSE,2010-10-25,77,8.6\nRed,FALSE,2012-10-22,77,8.6\n1989,FALSE,2014-10-27,76,8.3\nreputation,FALSE,2017-11-10,71,8.3\nLover,FALSE,2019-08-23,79,8.4\nfolklore,FALSE,2020-07-24,88,9\nevermore,FALSE,2020-12-11,85,8.9\nFearless (Taylor's Version),FALSE,2021-04-09,82,8.9\nRed (Taylor's Version),FALSE,2021-11-12,91,8.9\nMidnights,FALSE,2022-10-21,85,8.3\nSpeak Now (Taylor's Version),FALSE,2023-07-07,81,9.2\n1989 (Taylor's Version),FALSE,2023-10-27,90,NA\nTHE TORTURED POETS DEPARTMENT,FALSE,2024-04-19,76,NA\n"}

In [8]:
taylor = pd.read_csv("/content/taylor_albums.csv")

In [9]:
taylor

,album_name,ep,album_release,metacritic_score,user_score
0,Taylor Swift,False,2006-10-24,67.0,8.4
1,The Taylor Swift Holiday Collection,True,2007-10-14,NaN,NaN
2,Beautiful Eyes,True,2008-07-15,NaN,NaN
3,Fearless,False,2008-11-11,73.0,8.4
4,Speak Now,False,2010-10-25,77.0,8.6
5,Red,False,2012-10-22,77.0,8.6
6,1989,False,2014-10-27,76.0,8.3
7,reputation,False,2017-11-10,71.0,8.3
8,Lover,False,2019-08-23,79.0,8.4
9,folklore,False,2020-07-24,88.0,9.0
10,evermore,False,2020-12-11,85.0,8.9
11,Fearless (Taylor's Version),False,2021-04-09,82.0,8.9
12,Red (Taylor's Version),False,2021-11-12,91.0,8.9
13,Midnights,False,2022-10-21,85.0,8.3
14,Speak Now (Taylor's Version),False,2023-07-07,81.0,9.2
15,1989 (Taylor's Version),False,2023-10-27,90.0,NaN
16,THE TORTURED POETS DEPARTMENT,False,2024-04-19,76.0,NaN

In [10]:
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [11]:
from google.colab import data_table
data_table.enable_dataframe_formatter()  # Enabling an interactive DataFrame display

nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [12]:
# Below is to import the pandas library as pd
import pandas as pd

# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

# Below is to read nba.csv as nba DataFrame
nba = pd.read_csv("https://bcdanl.github.io/data/nba.csv",
                  parse_dates = ["Birthday"])

/tmp/ipykernel_1056/788510545.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv("https://bcdanl.github.io/data/nba.csv",

In [13]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    datetime64[ns]
 4   Salary    450 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 17.7+ KB

In [14]:
nba.count()

Name        450
Team        450
Position    450
Birthday    450
Salary      450
dtype: int64

In [15]:
nba.shape()

TypeError: 'tuple' object is not callable

In [16]:
nba.shape

(450, 5)

In [17]:
nba.columns

Index(['Name', 'Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [18]:
nba.describe()

                  Birthday        Salary
count                  450  4.500000e+02
mean   1993-11-24 02:01:36  7.653584e+06
min    1977-01-26 00:00:00  7.956800e+04
25%    1991-03-16 12:00:00  1.618520e+06
50%    1994-04-29 00:00:00  3.303074e+06
75%    1997-02-17 12:00:00  1.012957e+07
max    2000-12-23 00:00:00  4.023176e+07
std                    NaN  9.288810e+06

In [19]:
type(nba.describe())

pandas.core.frame.DataFrame

In [20]:
nba.describe(include="all")

,Name,Team,Position,Birthday,Salary
count,450,450,450,450,4.500000e+02
unique,450,30,9,NaN,NaN
top,Ricky Rubio,Philadelphia 76ers,PG,NaN,NaN
freq,1,17,98,NaN,NaN
mean,NaN,NaN,NaN,1993-11-24 02:01:36,7.653584e+06
min,NaN,NaN,NaN,1977-01-26 00:00:00,7.956800e+04
25%,NaN,NaN,NaN,1991-03-16 12:00:00,1.618520e+06
50%,NaN,NaN,NaN,1994-04-29 00:00:00,3.303074e+06
75%,NaN,NaN,NaN,1997-02-17 12:00:00,1.012957e+07
max,NaN,NaN,NaN,2000-12-23 00:00:00,4.023176e+07
std,NaN,NaN,NaN,NaN,9.288810e+06

In [21]:
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [22]:
nba.max()

Name             Zylan Cheatham
Team         Washington Wizards
Position                     SG
Birthday    2000-12-23 00:00:00
Salary                 40231758
dtype: object

In [23]:
nba.min()

Name               Aaron Gordon
Team              Atlanta Hawks
Position                      C
Birthday    1977-01-26 00:00:00
Salary                    79568
dtype: object

In [24]:
type(nba.min())

pandas.core.series.Series

In [25]:
nba.sum()

TypeError: 'DatetimeArray' with dtype datetime64[ns] does not support reduction 'sum'

In [26]:
nba.mean()

TypeError: Could not convert ["Shake MiltonChristian WoodPJ WashingtonDerrick RoseMarial ShayokDraymond GreenKendrick NunnCedi OsmanBrook LopezTorrey CraigJordan ClarksonAlex CarusoNorvel PelleTyler JohnsonAlec BurksJaMychal GreenDwight HowardNikola JokicChris BoucherMarcus MorrisKevin HuerterRui HachimuraGeorge HillNickeil Alexander-WalkerJaylen HoardTyler CookOtto PorterLangston GallowayEvan TurnerNorman PowellNicolas ClaxtonMichael FrazierPaul MillsapFurkan KorkmazTrey BurkeBradley BealThomas BryantDean WadeChris PaulJosh HartLaMarcus AldridgeDaQuan JeffriesHamidou DialloJamal MurrayDarius BazleyRobert FranksGerald GreenThaddeus YoungSviatoslav MykhailiukIan MahinmiDeonte BurtonMarkelle FultzAaron GordonDzanan MusaPatrick McCawBismack BiyomboJaVale McGeeJuwan MorganMarc GasolMarcus SmartRudy GobertWesley IwunduDwight PowellGoran DragicTheo PinsonDanilo GallinariJoe InglesJarrett CulverRobert CovingtonDamyean DotsonPatrick BeverleyKevin LoveQuinn CookJustin Wright-ForemanNoah VonlehTyus JonesDewayne DedmonMalcolm BrogdonBen McLemoreWilson ChandlerIsaac BongaAdam MokokaLonzo BallJalen BrunsonJohn CollinsMarvin WilliamsBrad WanamakerDonte DiVincenzoOmari SpellmanJoe HarrisRoyce O'NealeDeandre AytonCory JosephMalcolm MillerJustise WinslowKevin DurantEvan FournierChris SilvaVince CarterCody ZellerBrian BowenAaron HolidayTroy DanielsBuddy HieldTerance MannJohn KoncharKZ OkpalaDenzel ValentineMarquese ChrissAnthony DavisNemanja BjelicaChandler ParsonsCourtney LeeMyles TurnerKyle O'QuinnBryn ForbesDuncan RobinsonDevin BookerGrant WilliamsDeMarcus CousinsDeMar DeRozanKristaps PorzingisBrandon KnightThabo SefoloshaDavid NwabaQuinndary WeatherspoonDewan HernandezIsaiah ThomasBruce BrownKeldon JohnsonDamian JonesLuguentz DortTerence DavisChandler HutchisonSteven AdamsJordan PooleSekou DoumbouyaZion WilliamsonMike MuscalaSkal LabissiereMeyers LeonardReggie JacksonAlfonzo McKinnieYuta WatanabeKentavious Caldwell-PopeKelan MartinOG AnunobyTyler HerroRichaun HolmesTyson ChandlerSolomon HillKeita Bates-DiopKelly OlynykJaxson HayesCJ McCollumDarius MillerLuka DoncicDeMarre CarrollCristiano FelicioZach LaVineTremont WatersDejounte MurrayJerome RobinsonRudy GayRyan BroekhoffJake LaymanCameron JohnsonAllen CrabbeJustin JamesEmmanuel MudiayAvery BradleyVictor OladipoCaleb MartinCoby WhiteIsaiah HartensteinWill BartonDwayne BaconHarrison BarnesTim FrazierJimmy ButlerGary HarrisThon MakerShai Gilgeous-AlexanderHassan WhitesideKarl-Anthony TownsKy BowmanBen SimmonsTerrence RossJordan McLaughlinDaniel TheisJonathan IsaacCheick DialloSerge IbakaAmile JeffersonCam ReddishDe'Anthony MeltonUdonis HaslemCharlie BrownElie OkoboGordon HaywardMarco BelinelliJavonte GreenRondae Hollis-JeffersonCarmelo AnthonyDanny GreenStephen CurryEric PaschallDaniel GaffordAnfernee SimonsFrank KaminskyLuke KennardJosh OkogieRodney HoodDe'Andre HunterKlay ThompsonJrue HolidayPJ DozierAndre DrummondJared HarperRussell WestbrookTony BradleyOshae BrissettGary ClarkPascal SiakamEric BledsoeTomas SatoranskyDavis BertansAmir CoffeyIgnas BrazdeikisIvan RabbKhris MiddletonKevin KnoxJeff GreenErsan IlyasovaCaleb SwaniganAl HorfordClint CapelaGeorges NiangWesley MatthewsRajon RondoDelon WrightJa MorantFred VanVleetBrandon ClarkeMiye OniJulius RandleGlenn Robinson IIIDillon BrooksZylan CheathamMarkieff MorrisMalik BeasleyJohn WallVlatko CancarAlize JohnsonAndrew WigginsKhyri ThomasMitchell RobinsonDamian LillardNassir LittleMikal BridgesKyle AndersonGarrett TempleKyle KorverAl-Farouq AminuJames HardenDerrick WhiteJaKarr SampsonDario SaricIvica ZubacJuan HernangomezJarrell BrantleyEric GordonNaz ReidJustin RobinsonGrayson AllenTrevor ArizaBrandon GoodwinE'Twaun MooreMario HezonjaHenry EllensonJohnathan MotleyJames EnnisAndre RobersonGarrison MathewsJahlil OkaforMfiondu KabengeleTreveon GrahamSeth CurryD'Angelo RussellJustin HolidayTyrone WallaceMiles BridgesBogdan BogdanovicMatt ThomasJordan BellWenyen GabrielTony SnellShaquille HarrisonYogi FerrellMike ScottJarred VanderbiltJeff TeagueZach NorvellMaxi KleberMatisse ThybulleRyan ArcidiaconoWayne EllingtonKawhi LeonardMontrezl HarrellJusuf NurkicMatthew DellavedovaCody MartinZhaire SmithRJ BarrettLonnie WalkerTaurean PrinceElfrid PaytonBlake GriffinMarko GuduricZach CollinsStanley JohnsonBoban MarjanovicJosh MagetteKyle LowryDarius GarlandFrank JacksonDragan BenderKenrich WilliamsJerami GrantAllonzo TrierPat ConnaughtonDomantas SabonisDylan WindlerAntonius ClevelandDamion LeeKhem BirchAron BaynesKemba WalkerNerlens NoelJabari ParkerCarsen EdwardsAnthony TolliverLauri MarkkanenKris DunnReggie BullockMike ConleyJaylen NowellGorgui DiengPatrick PattersonJarrett AllenBobby PortisJoel EmbiidJonas ValanciunasChris ChiozzaKent BazemoreTristan ThompsonMason PlumleeShabazz NapierEdmond SumnerAlex LenJosh RichardsonBojan BogdanovicIman ShumpertDaryl MaconRodney McGruderBam AdebayoJacob EvansNigel Williams-GossTerrance FergusonMichael Carter-WilliamsBol BolWillie Cauley-SteinNikola VucevicNicolas BatumKyrie IrvingJeremy LambDonovan MitchellThanasis AntetokounmpoJames JohnsonMonte MorrisTerry RozierDeAndre JordanJae CrowderJosh GrayGoga BitadzeKobi SimmonsDerrick FavorsLandry ShametJalen McDanielsBruno CabocloDrew EubanksRaul NetoJalen LecqueGiannis AntetokounmpoMalik MonkTacko FallJustin JacksonPaul GeorgeJayson TatumAdmiral SchofieldLouis KingKostas AntetokounmpoRodions KurucsSpencer DinwiddieDoug McDermottRomeo LangfordCaris LeVertMichael Kidd-GilchristLeBron JamesTaj GibsonTy JeromeChris ClemonsLuke KornetTrey LylesSterling BrownAndre IguodalaVincent PoirierFrank NtilikinaJordan McRaeEnes KanterJohn HensonJaylen BrownJonah BoldenChimezie MetuTobias HarrisSemi OjeleyeJevon CarterBrandon IngramMoritz WagnerDorian Finney-SmithDanuel HouseNicolo MelliTalen Horton-TuckerEd DavisKyle GuyKadeem AllenDante ExumAbdel NaderBruno FernandoDion WaitersJared DudleyMax StrusKevon LooneyWilly HernangomezMelvin FrazierAustin RiversHarry GilesRobin LopezCollin SextonRicky Rubio"
 'Philadelphia 76ersDetroit PistonsCharlotte HornetsDetroit PistonsPhiladelphia 76ersGolden State WarriorsMiami HeatCleveland CavaliersMilwaukee BucksDenver NuggetsCleveland CavaliersLos Angeles LakersPhiladelphia 76ersPhoenix SunsGolden State WarriorsLos Angeles ClippersLos Angeles LakersDenver NuggetsToronto RaptorsNew York KnicksAtlanta HawksWashington WizardsMilwaukee BucksNew Orleans PelicansPortland Trail BlazersCleveland CavaliersChicago BullsDetroit PistonsAtlanta HawksToronto RaptorsBrooklyn NetsHouston RocketsDenver NuggetsPhiladelphia 76ersPhiladelphia 76ersWashington WizardsWashington WizardsCleveland CavaliersOklahoma City ThunderNew Orleans PelicansSan Antonio SpursSacramento KingsOklahoma City ThunderDenver NuggetsOklahoma City ThunderCharlotte HornetsHouston RocketsChicago BullsDetroit PistonsWashington WizardsOklahoma City ThunderOrlando MagicOrlando MagicBrooklyn NetsToronto RaptorsCharlotte HornetsLos Angeles LakersUtah JazzToronto RaptorsBoston CelticsUtah JazzOrlando MagicDallas MavericksMiami HeatBrooklyn NetsOklahoma City ThunderUtah JazzMinnesota TimberwolvesMinnesota TimberwolvesNew York KnicksLos Angeles ClippersCleveland CavaliersLos Angeles LakersUtah JazzMinnesota TimberwolvesMemphis GrizzliesSacramento KingsIndiana PacersHouston RocketsBrooklyn NetsWashington WizardsChicago BullsNew Orleans PelicansDallas MavericksAtlanta HawksCharlotte HornetsBoston CelticsMilwaukee BucksGolden State WarriorsBrooklyn NetsUtah JazzPhoenix SunsSacramento KingsToronto RaptorsMiami HeatBrooklyn NetsOrlando MagicMiami HeatAtlanta HawksCharlotte HornetsIndiana PacersIndiana PacersLos Angeles LakersSacramento KingsLos Angeles ClippersMemphis GrizzliesMiami HeatChicago BullsGolden State WarriorsLos Angeles LakersSacramento KingsAtlanta HawksDallas MavericksIndiana PacersPhiladelphia 76ersSan Antonio SpursMiami HeatPhoenix SunsBoston CelticsLos Angeles LakersSan Antonio SpursDallas MavericksCleveland CavaliersHouston RocketsBrooklyn NetsSan Antonio SpursToronto RaptorsWashington WizardsDetroit PistonsSan Antonio SpursAtlanta HawksOklahoma City ThunderToronto RaptorsChicago BullsOklahoma City ThunderGolden State WarriorsDetroit PistonsNew Orleans PelicansOklahoma City ThunderPortland Trail BlazersMiami HeatDetroit PistonsCleveland CavaliersMemphis GrizzliesLos Angeles LakersMinnesota TimberwolvesToronto RaptorsMiami HeatSacramento KingsHouston RocketsMemphis GrizzliesMinnesota TimberwolvesMiami HeatNew Orleans PelicansPortland Trail BlazersNew Orleans PelicansDallas MavericksSan Antonio SpursChicago BullsChicago BullsBoston CelticsSan Antonio SpursLos Angeles ClippersSan Antonio SpursDallas MavericksMinnesota TimberwolvesPhoenix SunsAtlanta HawksSacramento KingsUtah JazzLos Angeles LakersIndiana PacersCharlotte HornetsChicago BullsHouston RocketsDenver NuggetsCharlotte HornetsSacramento KingsDetroit PistonsMiami HeatDenver NuggetsDetroit PistonsOklahoma City ThunderPortland Trail BlazersMinnesota TimberwolvesGolden State WarriorsPhiladelphia 76ersOrlando MagicMinnesota TimberwolvesBoston CelticsOrlando MagicPhoenix SunsToronto RaptorsOrlando MagicAtlanta HawksMemphis GrizzliesMiami HeatAtlanta HawksPhoenix SunsBoston CelticsSan Antonio SpursBoston CelticsToronto RaptorsPortland Trail BlazersLos Angeles LakersGolden State WarriorsGolden State WarriorsChicago BullsPortland Trail BlazersPhoenix SunsDetroit PistonsMinnesota TimberwolvesPortland Trail BlazersAtlanta HawksGolden State WarriorsNew Orleans PelicansDenver NuggetsDetroit PistonsPhoenix SunsHouston RocketsUtah JazzToronto RaptorsHouston RocketsToronto RaptorsMilwaukee BucksChicago BullsWashington WizardsLos Angeles ClippersNew York KnicksNew York KnicksMilwaukee BucksNew York KnicksUtah JazzMilwaukee BucksSacramento KingsPhiladelphia 76ersHouston RocketsUtah JazzMilwaukee BucksLos Angeles LakersDallas MavericksMemphis GrizzliesToronto RaptorsMemphis GrizzliesUtah JazzNew York KnicksGolden State WarriorsMemphis GrizzliesNew Orleans PelicansDetroit PistonsDenver NuggetsWashington WizardsDenver NuggetsIndiana PacersMinnesota TimberwolvesDetroit PistonsNew York KnicksPortland Trail BlazersPortland Trail BlazersPhoenix SunsMemphis GrizzliesBrooklyn NetsMilwaukee BucksOrlando MagicHouston RocketsSan Antonio SpursIndiana PacersPhoenix SunsLos Angeles ClippersDenver NuggetsUtah JazzHouston RocketsMinnesota TimberwolvesWashington WizardsMemphis GrizzliesSacramento KingsAtlanta HawksNew Orleans PelicansPortland Trail BlazersBrooklyn NetsLos Angeles ClippersPhiladelphia 76ersOklahoma City ThunderWashington WizardsNew Orleans PelicansLos Angeles ClippersMinnesota TimberwolvesDallas MavericksGolden State WarriorsIndiana PacersAtlanta HawksCharlotte HornetsSacramento KingsToronto RaptorsMinnesota TimberwolvesSacramento KingsDetroit PistonsChicago BullsSacramento KingsPhiladelphia 76ersDenver NuggetsMinnesota TimberwolvesLos Angeles LakersDallas MavericksPhiladelphia 76ersChicago BullsNew York KnicksLos Angeles ClippersLos Angeles ClippersPortland Trail BlazersCleveland CavaliersCharlotte HornetsPhiladelphia 76ersNew York KnicksSan Antonio SpursBrooklyn NetsNew York KnicksDetroit PistonsMemphis GrizzliesPortland Trail BlazersToronto RaptorsDallas MavericksOrlando MagicToronto RaptorsCleveland CavaliersNew Orleans PelicansMilwaukee BucksNew Orleans PelicansDenver NuggetsNew York KnicksMilwaukee BucksIndiana PacersCleveland CavaliersDallas MavericksGolden State WarriorsOrlando MagicPhoenix SunsBoston CelticsOklahoma City ThunderAtlanta HawksBoston CelticsPortland Trail BlazersChicago BullsChicago BullsNew York KnicksUtah JazzMinnesota TimberwolvesMinnesota TimberwolvesLos Angeles ClippersBrooklyn NetsNew York KnicksPhiladelphia 76ersMemphis GrizzliesWashington WizardsPortland Trail BlazersCleveland CavaliersDenver NuggetsMinnesota TimberwolvesIndiana PacersAtlanta HawksPhiladelphia 76ersUtah JazzBrooklyn NetsMiami HeatLos Angeles ClippersMiami HeatGolden State WarriorsUtah JazzOklahoma City ThunderOrlando MagicDenver NuggetsGolden State WarriorsOrlando MagicCharlotte HornetsBrooklyn NetsIndiana PacersUtah JazzMilwaukee BucksMiami HeatDenver NuggetsCharlotte HornetsBrooklyn NetsMemphis GrizzliesNew Orleans PelicansIndiana PacersCharlotte HornetsNew Orleans PelicansLos Angeles ClippersCharlotte HornetsMemphis GrizzliesSan Antonio SpursPhiladelphia 76ersPhoenix SunsMilwaukee BucksCharlotte HornetsBoston CelticsDallas MavericksLos Angeles ClippersBoston CelticsWashington WizardsDetroit PistonsLos Angeles LakersBrooklyn NetsBrooklyn NetsIndiana PacersBoston CelticsBrooklyn NetsCharlotte HornetsLos Angeles LakersNew York KnicksPhoenix SunsHouston RocketsChicago BullsSan Antonio SpursMilwaukee BucksMemphis GrizzliesBoston CelticsNew York KnicksWashington WizardsBoston CelticsCleveland CavaliersBoston CelticsPhiladelphia 76ersSan Antonio SpursPhiladelphia 76ersBoston CelticsPhoenix SunsNew Orleans PelicansWashington WizardsDallas MavericksHouston RocketsNew Orleans PelicansLos Angeles LakersUtah JazzSacramento KingsNew York KnicksUtah JazzOklahoma City ThunderAtlanta HawksMiami HeatLos Angeles LakersChicago BullsGolden State WarriorsCharlotte HornetsOrlando MagicHouston RocketsSacramento KingsMilwaukee BucksCleveland CavaliersPhoenix Suns'
 'SGPFPFPGGPFSGSFCSFPGPGFCPGSGPFCCPFPFSGPFPGSGSFPFSFPGPGSGPFGPFSGPGSGCPFPGSFCSGSFPGPFFSFPFSFCSGPGPFSFSFCCFCPGCSFCPGSGPFPFSGPFSGPGCPGGCPGCPGSGPFPGGPGPGPFPFPGSGPFSFPFCPGSFPFPFSFPFPFCSGPGSGSGSGSGSFSFPFCPFSFSGCCSGPFSGPFCSFPFPGPFSFGCPGSGSFCGSGSFCSGSFFCCCPGSFSFSGSFSFSGCCSFSFCCSGSFPGPFCPGPGPGSGPFSGPFPFSGSGPGPGPGSFSGCSFSGPFPGSFSGCPGCCPGPGSFPGCPFCCPFSFPGCSGPGPFSFSFSFPFSGPGPFCSGCSGSGSFSFSGPGPGCPGPGCSFPFPFPGPGPFGSFPFSFPFPFPFPFCCPFSFPGPGPGPGPFSGCSFSFSFPFSGPGSFPFSFSGCPGPFSFPFPGPFPFPGPGSFPFCPFPFPGFPGSGSFPGPGPFPFPFSFSFSGCCSGPGPGSGPGSFSGSGCPFSFPGPGPFPFPGSGCSGPGSGSFCCPGSFSGSGSGSFPGPFSGCPFCPGPGPGPGPFPFPFPGSGCGFSGSGCCPGCPFSGPFPFPGSFPGSGCPFCCCCPGSFCCPGPGCSFSFPGSGSGCSGPGSFPGCCCSFPGSFSGSFPFPGPGCSFPGCPGCSGPFSFPFPGGPFSGCPFSFPFSFFPFPFPGPFSGSFPFPFCGSGCPFSFSFCPGPGCCSFPFPFPFPFPGPFCPFSFCGFCGPGPGSFCSGPFSGCCSGPGPFCPGPG'] to numeric

In [27]:
nba.median()

TypeError: Cannot convert [['Shake Milton' 'Christian Wood' 'PJ Washington' ... 'Robin Lopez'
  'Collin Sexton' 'Ricky Rubio']
 ['Philadelphia 76ers' 'Detroit Pistons' 'Charlotte Hornets' ...
  'Milwaukee Bucks' 'Cleveland Cavaliers' 'Phoenix Suns']
 ['SG' 'PF' 'PF' ... 'C' 'PG' 'PG']] to numeric

In [28]:
nba.quantile(0.75) # 0 to 1

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [29]:
nba.std()

TypeError: could not convert string to float: 'Shake Milton'

In [30]:
nba.sum(numeric_only = True)

Salary    3444112694
dtype: int64

In [31]:
nba.mean(numeric_only = True)

Salary    7.653584e+06
dtype: float64

In [32]:
nba.median(numeric_only = True)

Salary    3303074.5
dtype: float64

In [33]:
nba.quantile(0.75, numeric_only=True)

Salary    10129574.25
Name: 0.75, dtype: float64

In [34]:
nba.std(numeric_only = True)

Salary    9.288810e+06
dtype: float64

In [35]:
nba.columns

Index(['Name', 'Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [36]:
nba["Salary"]

0       1445697
1       1645357
2       3831840
3       7317074
4         79568
         ...
445     2174310
446     2578800
447     4767000
448     4764960
449    16200000
Name: Salary, Length: 450, dtype: int64

In [37]:
type(nba["Salary"])

pandas.core.series.Series

In [38]:
nba["Salary"]

0       1445697
1       1645357
2       3831840
3       7317074
4         79568
         ...
445     2174310
446     2578800
447     4767000
448     4764960
449    16200000
Name: Salary, Length: 450, dtype: int64

In [39]:
nba["Salary"] + nba["Salary"]

0       2891394
1       3290714
2       7663680
3      14634148
4        159136
         ...
445     4348620
446     5157600
447     9534000
448     9529920
449    32400000
Name: Salary, Length: 450, dtype: int64

In [40]:
1645357 + 1645357

3290714

In [41]:
nba["Salary"] + nba["Salary"]

0       2891394
1       3290714
2       7663680
3      14634148
4        159136
         ...
445     4348620
446     5157600
447     9534000
448     9529920
449    32400000
Name: Salary, Length: 450, dtype: int64

In [42]:
"SUNY" + " Geneseo"

'SUNY Geneseo'

In [43]:
nba["Name"] + " (" + nba["Position"] + ")"

0        Shake Milton (SG)
1      Christian Wood (PF)
2       PJ Washington (PF)
3        Derrick Rose (PG)
4        Marial Shayok (G)
              ...
445     Austin Rivers (PG)
446       Harry Giles (PF)
447        Robin Lopez (C)
448     Collin Sexton (PG)
449       Ricky Rubio (PG)
Length: 450, dtype: object

In [44]:
nba["Salary"].mean()

np.float64(7653583.764444444)

In [46]:
nba["Salary"]

0       1445697
1       1645357
2       3831840
3       7317074
4         79568
         ...
445     2174310
446     2578800
447     4767000
448     4764960
449    16200000
Name: Salary, Length: 450, dtype: int64

In [45]:
nba["Salary"] - nba["Salary"].mean()

0     -6.207887e+06
1     -6.008227e+06
2     -3.821744e+06
3     -3.365098e+05
4     -7.574016e+06
           ...
445   -5.479274e+06
446   -5.074784e+06
447   -2.886584e+06
448   -2.888624e+06
449    8.546416e+06
Name: Salary, Length: 450, dtype: float64

In [48]:
2.886584e+06

2886584.0

In [49]:
2.886584e-06

2.886584e-06

In [50]:
2.888e-03

0.002888

In [51]:
nba['Salary_k'] = nba['Salary'] / 1000

In [52]:
nba

,Name,Team,Position,Birthday,Salary,Salary_k
0,Shake Milton,Philadelphia 76ers,SG,1996-09-26,1445697,1445.697
1,Christian Wood,Detroit Pistons,PF,1995-09-27,1645357,1645.357
2,PJ Washington,Charlotte Hornets,PF,1998-08-23,3831840,3831.840
3,Derrick Rose,Detroit Pistons,PG,1988-10-04,7317074,7317.074
4,Marial Shayok,Philadelphia 76ers,G,1995-07-26,79568,79.568
...,...,...,...,...,...,...
445,Austin Rivers,Houston Rockets,PG,1992-08-01,2174310,2174.310
446,Harry Giles,Sacramento Kings,PF,1998-04-22,2578800,2578.800
447,Robin Lopez,Milwaukee Bucks,C,1988-04-01,4767000,4767.000
448,Collin Sexton,Cleveland Cavaliers,PG,1999-01-04,4764960,4764.960
449,Ricky Rubio,Phoenix Suns,PG,1990-10-21,16200000,16200.000

In [53]:
nba['Salary_2x'] = nba['Salary'] + nba['Salary']
nba['Salary_3x'] = nba['Salary'] * 3

In [54]:
nba

,Name,Team,Position,Birthday,Salary,Salary_k,Salary_2x,Salary_3x
0,Shake Milton,Philadelphia 76ers,SG,1996-09-26,1445697,1445.697,2891394,4337091
1,Christian Wood,Detroit Pistons,PF,1995-09-27,1645357,1645.357,3290714,4936071
2,PJ Washington,Charlotte Hornets,PF,1998-08-23,3831840,3831.840,7663680,11495520
3,Derrick Rose,Detroit Pistons,PG,1988-10-04,7317074,7317.074,14634148,21951222
4,Marial Shayok,Philadelphia 76ers,G,1995-07-26,79568,79.568,159136,238704
...,...,...,...,...,...,...,...,...
445,Austin Rivers,Houston Rockets,PG,1992-08-01,2174310,2174.310,4348620,6522930
446,Harry Giles,Sacramento Kings,PF,1998-04-22,2578800,2578.800,5157600,7736400
447,Robin Lopez,Milwaukee Bucks,C,1988-04-01,4767000,4767.000,9534000,14301000
448,Collin Sexton,Cleveland Cavaliers,PG,1999-01-04,4764960,4764.960,9529920,14294880
449,Ricky Rubio,Phoenix Suns,PG,1990-10-21,16200000,16200.000,32400000,48600000