<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_class_2026_0413.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np

# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

ncaa = pd.DataFrame({
    'Team': ['Lakers', 'Celtics', 'Lakers', 'Bulls', 'Heat', 'Bulls', 'Lakers', 'Heat', np.nan, 'Celtics'],
    'Position': ['CG', 'F', 'G', 'C', 'G', 'F', 'F', 'C', 'G', 'F'],
    'Age': [25, 29, 25, 31, 27, 22, 30, 27, 24, 29],
    'College': ['Duke', 'Kentucky', np.nan, 'UCLA', 'Duke', 'Gonzaga', 'Arizona', np.nan, 'Duke', 'Kentucky']
})

ncaa

      Team Position  Age   College
0   Lakers       CG   25      Duke
1  Celtics        F   29  Kentucky
2   Lakers        G   25       NaN
3    Bulls        C   31      UCLA
4     Heat        G   27      Duke
5    Bulls        F   22   Gonzaga
6   Lakers        F   30   Arizona
7     Heat        C   27       NaN
8      NaN        G   24      Duke
9  Celtics        F   29  Kentucky

In [2]:
ncaa['College'].value_counts()

College
Duke        3
Kentucky    2
UCLA        1
Gonzaga     1
Arizona     1
Name: count, dtype: int64

In [3]:
ncaa['College'].value_counts(dropna = False)

College
Duke        3
Kentucky    2
NaN         2
UCLA        1
Gonzaga     1
Arizona     1
Name: count, dtype: int64

In [4]:
ncaa['College'].value_counts(normalize = True)

College
Duke        0.375
Kentucky    0.250
UCLA        0.125
Gonzaga     0.125
Arizona     0.125
Name: proportion, dtype: float64

In [7]:
ncaa['College'].value_counts(sort = True)

College
Duke        3
Kentucky    2
UCLA        1
Gonzaga     1
Arizona     1
Name: count, dtype: int64

In [13]:
ncaa['Position'].value_counts()

Position
F     4
G     3
C     2
CG    1
Name: count, dtype: int64

In [12]:
ncaa['Position'].value_counts(sort = False)

Position
CG    1
F     4
G     3
C     2
Name: count, dtype: int64

In [15]:
ncaa['Team'].value_counts()  # ascending = False

Team
Lakers     3
Celtics    2
Bulls      2
Heat       2
Name: count, dtype: int64

In [14]:
ncaa['Team'].value_counts(ascending = True)

Team
Celtics    2
Bulls      2
Heat       2
Lakers     3
Name: count, dtype: int64

In [16]:
ncaa['Age'].value_counts(bins = 4)

(28.75, 31.0]     4
(21.99, 24.25]    2
(24.25, 26.5]     2
(26.5, 28.75]     2
Name: count, dtype: int64

In [17]:
ncaa['Age'].value_counts(bins = 3)

(21.99, 25.0]    4
(28.0, 31.0]     4
(25.0, 28.0]     2
Name: count, dtype: int64

In [18]:
ncaa['Age'].value_counts(bins = 3, sort = False)

(21.99, 25.0]    4
(25.0, 28.0]     2
(28.0, 31.0]     4
Name: count, dtype: int64

In [19]:
ncaa[['Team', 'Position']].value_counts()

Team     Position
Celtics  F           2
Bulls    C           1
         F           1
Heat     C           1
         G           1
Lakers   CG          1
         F           1
         G           1
Name: count, dtype: int64

In [20]:
ncaa[['Team', 'Position']].value_counts(normalize = True)

Team     Position
Celtics  F           0.222222
Bulls    C           0.111111
         F           0.111111
Heat     C           0.111111
         G           0.111111
Lakers   CG          0.111111
         F           0.111111
         G           0.111111
Name: proportion, dtype: float64

# Classwork 13

In [21]:
emp = pd.read_csv(
    "https://bcdanl.github.io/data/employment.csv"
)

emp

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male     8/6/93       NaN   True     Marketing
1        Thomas    Male    3/31/96   61933.0   True           NaN
2         Maria  Female        NaN  130590.0  False       Finance
3         Jerry     NaN     3/4/05  138705.0   True       Finance
4         Larry    Male    1/24/98  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male    1/31/84   42392.0  False       Finance
997     Russell    Male    5/20/13   96914.0  False       Product
998       Larry    Male    4/20/13   60500.0  False  Business Dev
999      Albert    Male    5/15/12  129949.0   True         Sales
1000        NaN     NaN        NaN       NaN    NaN           NaN

[1001 rows x 6 columns]

In [22]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    object
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: float64(1), object(5)
memory usage: 47.1+ KB

In [23]:
emp = emp.astype(
    {
        'Gender':'category',
        'Start Date': 'datetime64[ns]',
        'Mgmt': bool,
        'Team': 'category'
    }
)

In [25]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    category
dtypes: bool(1), category(2), datetime64[ns](1), float64(1), object(1)
memory usage: 27.0+ KB

## Q1
Write code to count how many employees belong to each team.

In [26]:
q1 = emp['Team'].value_counts()

q1

Team
IT              106
Finance         102
Business Dev    101
Marketing        98
Product          95
Sales            94
Engineering      92
HR               91
Distribution     90
Legal            88
Name: count, dtype: int64

## Q2
Write code to display the proportion of employees in each gender category.

In [28]:
q2 = emp['Gender'].value_counts(normalize = True, dropna = False)
q2

Gender
Female    0.430569
Male      0.422577
NaN       0.146853
Name: proportion, dtype: float64

## Q3
Write code to identify the team with the largest portion of senior managers.

In [32]:
q3 = (
    emp[['Team' ,'Mgmt']]
    .value_counts(normalize = True)
    .reset_index()
    .query('Mgmt == True')
    .nlargest(1, 'proportion')
)

q3

           Team  Mgmt  proportion
1  Business Dev  True    0.058516

## Q4
Write code to count the number of employees with salary more than $100,000 for each gender.

In [33]:
emp['high_salary'] = np.where(
    emp['Salary'] > 100_000 ,
    True,
    False
)

emp

     First Name  Gender Start Date    Salary   Mgmt          Team  high_salary
0       Douglas    Male 1993-08-06       NaN   True     Marketing        False
1        Thomas    Male 1996-03-31   61933.0   True           NaN        False
2         Maria  Female        NaT  130590.0  False       Finance         True
3         Jerry     NaN 2005-03-04  138705.0   True       Finance         True
4         Larry    Male 1998-01-24  101004.0   True            IT         True
...         ...     ...        ...       ...    ...           ...          ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance        False
997     Russell    Male 2013-05-20   96914.0  False       Product        False
998       Larry    Male 2013-04-20   60500.0  False  Business Dev        False
999      Albert    Male 2012-05-15  129949.0   True         Sales         True
1000        NaN     NaN        NaT       NaN   True           NaN        False

[1001 rows x 7 columns]

In [38]:
# True if a value of emp['Salary'] is missing
emp['Salary'].isna()

0        True
1       False
2       False
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000     True
Name: Salary, Length: 1001, dtype: bool

In [36]:
# True if a value of emp['Salary'] is not missing
~( emp['Salary'].isna() )

0       False
1        True
2        True
3        True
4        True
        ...
996      True
997      True
998      True
999      True
1000    False
Name: Salary, Length: 1001, dtype: bool

In [44]:
emp['high_salary'] = np.where(
    emp['Salary'] > 100_000,
    True,
    False
)

emp['high_salary'] = np.where(
    emp['Salary'].isna(),
    np.nan,
    emp['high_salary']
)

emp

     First Name  Gender Start Date    Salary   Mgmt          Team  high_salary
0       Douglas    Male 1993-08-06       NaN   True     Marketing          NaN
1        Thomas    Male 1996-03-31   61933.0   True           NaN          0.0
2         Maria  Female        NaT  130590.0  False       Finance          1.0
3         Jerry     NaN 2005-03-04  138705.0   True       Finance          1.0
4         Larry    Male 1998-01-24  101004.0   True            IT          1.0
...         ...     ...        ...       ...    ...           ...          ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance          0.0
997     Russell    Male 2013-05-20   96914.0  False       Product          0.0
998       Larry    Male 2013-04-20   60500.0  False  Business Dev          0.0
999      Albert    Male 2012-05-15  129949.0   True         Sales          1.0
1000        NaN     NaN        NaT       NaN   True           NaN          NaN

[1001 rows x 7 columns]

In [46]:
emp

     First Name  Gender Start Date    Salary   Mgmt          Team  high_salary
0       Douglas    Male 1993-08-06       NaN   True     Marketing          NaN
1        Thomas    Male 1996-03-31   61933.0   True           NaN          0.0
2         Maria  Female        NaT  130590.0  False       Finance          1.0
3         Jerry     NaN 2005-03-04  138705.0   True       Finance          1.0
4         Larry    Male 1998-01-24  101004.0   True            IT          1.0
...         ...     ...        ...       ...    ...           ...          ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance          0.0
997     Russell    Male 2013-05-20   96914.0  False       Product          0.0
998       Larry    Male 2013-04-20   60500.0  False  Business Dev          0.0
999      Albert    Male 2012-05-15  129949.0   True         Sales          1.0
1000        NaN     NaN        NaT       NaN   True           NaN          NaN

[1001 rows x 7 columns]

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN   True           NaN

[1001 rows x 6 columns]

In [45]:
emp["Team"].isna()

0       False
1        True
2       False
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000     True
Name: Team, Length: 1001, dtype: bool

In [47]:
emp["Start Date"].isna()

0       False
1       False
2        True
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000     True
Name: Start Date, Length: 1001, dtype: bool

In [52]:
emp["Team"].notna()

0        True
1       False
2        True
3        True
4        True
        ...
996      True
997      True
998      True
999      True
1000    False
Name: Team, Length: 1001, dtype: bool

In [53]:
~emp["Team"].isna()

0        True
1       False
2        True
3        True
4        True
        ...
996      True
997      True
998      True
999      True
1000    False
Name: Team, Length: 1001, dtype: bool

In [54]:
emp[
    ~emp["Team"].isna()
]

    First Name  Gender Start Date    Salary   Mgmt          Team
0      Douglas    Male 1993-08-06       NaN   True     Marketing
2        Maria  Female        NaT  130590.0  False       Finance
3        Jerry     NaN 2005-03-04  138705.0   True       Finance
4        Larry    Male 1998-01-24  101004.0   True            IT
5       Dennis    Male 1987-04-18  115163.0  False         Legal
..         ...     ...        ...       ...    ...           ...
995      Henry     NaN 2014-11-23  132483.0  False  Distribution
996    Phillip    Male 1984-01-31   42392.0  False       Finance
997    Russell    Male 2013-05-20   96914.0  False       Product
998      Larry    Male 2013-04-20   60500.0  False  Business Dev
999     Albert    Male 2012-05-15  129949.0   True         Sales

[957 rows x 6 columns]

In [55]:
emp["Mgmt"].isna().sum()

np.int64(0)

In [56]:

emp["Mgmt"].value_counts(dropna = False)

Mgmt
True     536
False    465
Name: count, dtype: int64