<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_script_2025_0228.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Join - Duplicate Keys

In [1]:
import pandas as pd

In [2]:
x = pd.DataFrame({
    'key':[1, 2, 2, 3],
    'val_x':['x1', 'x2', 'x3', 'x4']})

y = pd.DataFrame({
    'key':[1, 2],
    'val_y':['y1', 'y2'] })
one_to_many = x.merge(y, on='key',
                         how='left')

In [3]:
x

   key val_x
0    1    x1
1    2    x2
2    2    x3
3    3    x4

In [4]:
y

   key val_y
0    1    y1
1    2    y2

In [5]:
x.merge(y, on = 'key', how = 'left')

   key val_x val_y
0    1    x1    y1
1    2    x2    y2
2    2    x3    y2
3    3    x4   NaN

In [6]:
x = pd.DataFrame({
  'key':[1, 2, 2, 3],
  'val_x':['x1','x2','x3','x4']})

y = pd.DataFrame({
  'key': [1, 2, 2, 3],
  'val_y': ['y1', 'y2', 'y3', 'y4'] })

In [7]:
x

   key val_x
0    1    x1
1    2    x2
2    2    x3
3    3    x4

In [8]:
y

   key val_y
0    1    y1
1    2    y2
2    2    y3
3    3    y4

In [9]:
x.merge(y, on = 'key', how = 'left')

   key val_x val_y
0    1    x1    y1
1    2    x2    y2
2    2    x2    y3
3    2    x3    y2
4    2    x3    y3
5    3    x4    y4

In [14]:
x = pd.DataFrame({
  'key_x': [1, 2, 3],
  'val_x': ['x1', 'x2', 'x3']
})


y = pd.DataFrame({
  'key_y': [1, 2],
  'val_y': ['y1', 'y2'] })

In [15]:
x

   key_x val_x
0      1    x1
1      2    x2
2      3    x3

In [16]:
y

   key_y val_y
0      1    y1
1      2    y2

In [17]:
keys_xy = x.merge(y,
                  left_on = 'key_x',
                  right_on = 'key_y',
                  how = 'left')

In [18]:
keys_xy

   key_x val_x  key_y val_y
0      1    x1    1.0    y1
1      2    x2    2.0    y2
2      3    x3    NaN   NaN

# CW 7. Pt.2

In [20]:
from google.colab import data_table
data_table.enable_dataframe_formatter()

In [19]:
flights = pd.read_csv("https://bcdanl.github.io/data/flights.zip")
airlines = pd.read_csv("https://bcdanl.github.io/data/flights-airlines.csv")
airports = pd.read_csv("https://bcdanl.github.io/data/flights-airports.csv")
planes = pd.read_csv("https://bcdanl.github.io/data/flights-planes.csv")
weather = pd.read_csv("https://bcdanl.github.io/data/flights-weather.csv")

## Q3

In [21]:
flights

Warning: total number of rows (336776) exceeds max_rows (20000). Falling back to pandas display.

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z

In [22]:
weather

Warning: total number of rows (26115) exceeds max_rows (20000). Falling back to pandas display.

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,EWR,2013,1,1,1,39.02,26.06,59.37,270.0,10.35702,NaN,0.0,1012.0,10.0,2013-01-01T06:00:00Z
1,EWR,2013,1,1,2,39.02,26.96,61.63,250.0,8.05546,NaN,0.0,1012.3,10.0,2013-01-01T07:00:00Z
2,EWR,2013,1,1,3,39.02,28.04,64.43,240.0,11.50780,NaN,0.0,1012.5,10.0,2013-01-01T08:00:00Z
3,EWR,2013,1,1,4,39.92,28.04,62.21,250.0,12.65858,NaN,0.0,1012.2,10.0,2013-01-01T09:00:00Z
4,EWR,2013,1,1,5,39.02,28.04,64.43,260.0,12.65858,NaN,0.0,1011.9,10.0,2013-01-01T10:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26110,LGA,2013,12,30,14,35.96,19.94,51.78,340.0,13.80936,21.86482,0.0,1017.1,10.0,2013-12-30T19:00:00Z
26111,LGA,2013,12,30,15,33.98,17.06,49.51,330.0,17.26170,21.86482,0.0,1018.8,10.0,2013-12-30T20:00:00Z
26112,LGA,2013,12,30,16,32.00,15.08,49.19,340.0,14.96014,23.01560,0.0,1019.5,10.0,2013-12-30T21:00:00Z
26113,LGA,2013,12,30,17,30.92,12.92,46.74,320.0,17.26170,NaN,0.0,1019.9,10.0,2013-12-30T22:00:00Z
26114,LGA,2013,12,30,18,28.94,10.94,46.41,330.0,18.41248,NaN,0.0,1020.9,10.0,2013-12-30T23:00:00Z

In [23]:
weather.columns

Index(['origin', 'year', 'month', 'day', 'hour', 'temp', 'dewp', 'humid',
       'wind_dir', 'wind_speed', 'wind_gust', 'precip', 'pressure', 'visib',
       'time_hour'],
      dtype='object')

In [24]:
flights_weather = (
    flights.merge(weather,
                  on = ['origin', 'year', 'month', 'day', 'hour'],
                  how = 'left')
)

flights_weather

Warning: total number of rows (336776) exceeds max_rows (20000). Falling back to pandas display.

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour_y
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,39.02,28.04,64.43,260.0,12.65858,NaN,0.0,1011.9,10.0,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,39.92,24.98,54.81,250.0,14.96014,21.86482,0.0,1011.4,10.0,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,...,39.02,26.96,61.63,260.0,14.96014,NaN,0.0,1012.1,10.0,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,...,39.02,26.96,61.63,260.0,14.96014,NaN,0.0,1012.1,10.0,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,...,39.92,24.98,54.81,260.0,16.11092,23.01560,0.0,1011.7,10.0,2013-01-01T11:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,...,68.00,55.04,63.21,190.0,11.50780,NaN,0.0,1016.6,10.0,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,...,64.94,53.06,65.37,200.0,6.90468,NaN,0.0,1015.8,10.0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,...,69.08,48.02,46.99,70.0,5.75390,NaN,0.0,1016.7,10.0,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,...,66.92,48.92,52.35,70.0,8.05546,NaN,0.0,1017.5,10.0,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,...,60.98,51.08,69.86,NaN,5.75390,NaN,0.0,1018.6,10.0,2013-09-30T12:00:00Z

Warning: Total number of columns (29) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (336776) exceeds max_rows (20000). Limiting to first (20000) rows.

## Q4

In [25]:
airlines

   carrier                         name
0       9E            Endeavor Air Inc.
1       AA       American Airlines Inc.
2       AS         Alaska Airlines Inc.
3       B6              JetBlue Airways
4       DL         Delta Air Lines Inc.
5       EV     ExpressJet Airlines Inc.
6       F9       Frontier Airlines Inc.
7       FL  AirTran Airways Corporation
8       HA       Hawaiian Airlines Inc.
9       MQ                    Envoy Air
10      OO        SkyWest Airlines Inc.
11      UA        United Air Lines Inc.
12      US              US Airways Inc.
13      VX               Virgin America
14      WN       Southwest Airlines Co.
15      YV           Mesa Airlines Inc.

In [29]:
df(
    flights
    .merge(airlines,
           on = 'carrier',
           how = 'left')   # to not lose any info from flights
    .nlargest(5, 'dep_delay', keep = 'all')[['carrier', 'name', 'dep_delay', 'time_hour', 'origin', 'dest']]
)

## Q5

In [37]:
import numpy as np

df = (
    flights
    .query('carrier == "DL" | carrier == "UA" ')
)
df['long_delay'] = np.where(df['dep_delay'] > 30, 1, 0)

df2 = df[['carrier', 'long_delay', 'dep_delay']]
df2

Warning: total number of rows (106775) exceeds max_rows (20000). Falling back to pandas display.

<ipython-input-37-60ad7ac42af9>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['long_delay'] = np.where(df['dep_delay'] > 30, 1, 0)

       carrier  long_delay  dep_delay
0           UA           0        2.0
1           UA           0        4.0
4           DL           0       -6.0
5           UA           0       -4.0
12          UA           0       -2.0
...        ...         ...        ...
336728      UA           0       -4.0
336737      UA           0       -1.0
336744      DL           0       21.0
336755      UA           0       -7.0
336762      UA           1       80.0

[106775 rows x 3 columns]

Warning: total number of rows (106775) exceeds max_rows (20000). Limiting to first (20000) rows.

In [39]:
df2.query('carrier == "DL"')['long_delay'].mean()

0.10355435460403242

In [40]:
df2.query('carrier == "UA"')['long_delay'].mean()

0.129838915878292

In [38]:
(
    df2[['carrier', 'long_delay']]
    .value_counts()
    .reset_index()
    .sort_values(['carrier', 'long_delay'], ascending = [True, False])
)

  carrier  long_delay  count
3      DL           1   4982
1      DL           0  43128
2      UA           1   7617
0      UA           0  51048