<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_script_2025_0214.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Below is to import the pandas library as pd
import pandas as pd

# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

# Below is to read nba.csv as nba DataFrame
nba = pd.read_csv("https://bcdanl.github.io/data/nba.csv",
                  parse_dates = ["Birthday"])

<ipython-input-1-f4b4f02b546c>:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv("https://bcdanl.github.io/data/nba.csv",

In [2]:
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [3]:
nba.sort_values("Name")

                  Name                   Team Position   Birthday    Salary
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
..                 ...                    ...      ...        ...       ...
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568

[450 rows x 5 columns]

In [4]:
nba.sort_values("Salary")

,Name,Team,Position,Birthday,Salary
395,Tacko Fall,Boston Celtics,C,1995-12-10,79568
229,Ivan Rabb,New York Knicks,PF,1997-02-04,79568
73,Justin Wright-Foreman,Utah Jazz,G,1997-10-27,79568
31,Michael Frazier,Houston Rockets,G,1994-03-08,79568
400,Louis King,Detroit Pistons,F,1999-04-06,79568
...,...,...,...,...,...
251,John Wall,Washington Wizards,PG,1990-09-06,38199000
264,James Harden,Houston Rockets,PG,1989-08-26,38199000
38,Chris Paul,Oklahoma City Thunder,PG,1985-05-06,38506482
219,Russell Westbrook,Houston Rockets,PG,1988-11-12,38506482
205,Stephen Curry,Golden State Warriors,PG,1988-03-14,40231758

In [5]:
nba.sort_values(["Name"], ascending = False)

                  Name                   Team Position   Birthday    Salary
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
..                 ...                    ...      ...        ...       ...
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636

[450 rows x 5 columns]

In [6]:
(
    nba
    .sort_values(["Salary"])
    .head(5)
)

                      Name             Team Position   Birthday  Salary
395             Tacko Fall   Boston Celtics        C 1995-12-10   79568
229              Ivan Rabb  New York Knicks       PF 1997-02-04   79568
73   Justin Wright-Foreman        Utah Jazz        G 1997-10-27   79568
31         Michael Frazier  Houston Rockets        G 1994-03-08   79568
400             Louis King  Detroit Pistons        F 1999-04-06   79568

In [7]:
nba.nsmallest(5, "Salary")

               Name                    Team Position   Birthday  Salary
4     Marial Shayok      Philadelphia 76ers        G 1995-07-26   79568
12     Norvel Pelle      Philadelphia 76ers       FC 1993-02-03   79568
24     Jaylen Hoard  Portland Trail Blazers       SF 1999-03-30   79568
25       Tyler Cook     Cleveland Cavaliers       PF 1997-09-23   79568
31  Michael Frazier         Houston Rockets        G 1994-03-08   79568

In [8]:
nba.nsmallest(5, "Salary", keep = "all")

,Name,Team,Position,Birthday,Salary
4,Marial Shayok,Philadelphia 76ers,G,1995-07-26,79568
12,Norvel Pelle,Philadelphia 76ers,FC,1993-02-03,79568
24,Jaylen Hoard,Portland Trail Blazers,SF,1999-03-30,79568
25,Tyler Cook,Cleveland Cavaliers,PF,1997-09-23,79568
31,Michael Frazier,Houston Rockets,G,1994-03-08,79568
37,Dean Wade,Cleveland Cavaliers,PF,1996-11-20,79568
45,Robert Franks,Charlotte Hornets,F,1996-12-18,79568
73,Justin Wright-Foreman,Utah Jazz,G,1997-10-27,79568
81,Adam Mokoka,Chicago Bulls,G,1998-07-18,79568
97,Chris Silva,Miami Heat,PF,1996-09-19,79568
100,Brian Bowen,Indiana Pacers,SG,1998-10-02,79568
105,John Konchar,Memphis Grizzlies,SG,1996-03-22,79568
125,Quinndary Weatherspoon,San Antonio Spurs,G,1996-09-10,79568
131,Luguentz Dort,Oklahoma City Thunder,G,1999-04-19,79568
143,Yuta Watanabe,Memphis Grizzlies,SF,1994-10-13,79568
145,Kelan Martin,Minnesota Timberwolves,SF,1995-08-03,79568
160,Tremont Waters,Boston Celtics,PG,1998-01-10,79568
185,Ky Bowman,Golden State Warriors,PG,1997-06-16,79568
188,Jordan McLaughlin,Minnesota Timberwolves,PG,1996-04-09,79568
197,Charlie Brown,Atlanta Hawks,SG,1997-02-02,79568
216,PJ Dozier,Denver Nuggets,PG,1996-10-25,79568
218,Jared Harper,Phoenix Suns,PG,1997-09-14,79568
221,Oshae Brissett,Toronto Raptors,SF,1998-06-20,79568
227,Amir Coffey,Los Angeles Clippers,G,1997-06-17,79568
229,Ivan Rabb,New York Knicks,PF,1997-02-04,79568
248,Zylan Cheatham,New Orleans Pelicans,SF,1995-11-17,79568
270,Jarrell Brantley,Utah Jazz,PF,1996-06-07,79568
276,Brandon Goodwin,Atlanta Hawks,PG,1995-10-02,79568
279,Henry Ellenson,Brooklyn Nets,PF,1997-01-13,79568
280,Johnathan Motley,Los Angeles Clippers,PF,1995-05-04,79568
283,Garrison Mathews,Washington Wizards,SG,1996-10-24,79568
295,Wenyen Gabriel,Sacramento Kings,PF,1997-03-26,79568
302,Zach Norvell,Los Angeles Lakers,SG,1997-12-09,79568
322,Josh Magette,Orlando Magic,PG,1989-11-28,79568
333,Antonius Cleveland,Dallas Mavericks,SG,1994-02-02,79568
334,Damion Lee,Golden State Warriors,SG,1992-10-21,79568
353,Chris Chiozza,Washington Wizards,PG,1995-11-21,79568
363,Daryl Macon,Miami Heat,SG,1995-11-29,79568
370,Bol Bol,Denver Nuggets,C,1999-11-16,79568
383,Josh Gray,New Orleans Pelicans,PG,1993-09-09,79568
385,Kobi Simmons,Charlotte Hornets,PG,1997-07-04,79568
390,Drew Eubanks,San Antonio Spurs,PF,1997-02-01,79568
395,Tacko Fall,Boston Celtics,C,1995-12-10,79568
400,Louis King,Detroit Pistons,F,1999-04-06,79568
401,Kostas Antetokounmpo,Los Angeles Lakers,PF,1997-11-20,79568
411,Chris Clemons,Houston Rockets,SG,1997-07-23,79568
434,Kyle Guy,Sacramento Kings,G,1997-08-11,79568
435,Kadeem Allen,New York Knicks,PG,1993-01-15,79568
441,Max Strus,Chicago Bulls,SG,1996-03-28,79568

In [9]:
nba.nlargest(5, "Salary")

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
251          John Wall     Washington Wizards       PG 1990-09-06  38199000
264       James Harden        Houston Rockets       PG 1989-08-26  38199000

In [10]:
nba.nlargest(4, "Salary")

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
251          John Wall     Washington Wizards       PG 1990-09-06  38199000

In [12]:
nba.nlargest(4, "Salary", keep = "all")

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
251          John Wall     Washington Wizards       PG 1990-09-06  38199000
264       James Harden        Houston Rockets       PG 1989-08-26  38199000

In [13]:
nba.sort_values(["Team", "Name"])

                Name                Team Position   Birthday    Salary
359         Alex Len       Atlanta Hawks        C 1993-06-16   4160000
167     Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
194      Cam Reddish       Atlanta Hawks       SF 1999-09-01   4245720
..               ...                 ...      ...        ...       ...
418     Jordan McRae  Washington Wizards       PG 1991-03-28   1645357
273  Justin Robinson  Washington Wizards       PG 1997-10-12    898310
428    Moritz Wagner  Washington Wizards        C 1997-04-26   2063520
21     Rui Hachimura  Washington Wizards       PF 1998-02-08   4469160
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000

[450 rows x 5 columns]

In [14]:
nba.sort_values(["Team", "Name"],
                ascending=False)

                Name                Team Position   Birthday    Salary
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000
21     Rui Hachimura  Washington Wizards       PF 1998-02-08   4469160
428    Moritz Wagner  Washington Wizards        C 1997-04-26   2063520
273  Justin Robinson  Washington Wizards       PG 1997-10-12    898310
418     Jordan McRae  Washington Wizards       PG 1991-03-28   1645357
..               ...                 ...      ...        ...       ...
194      Cam Reddish       Atlanta Hawks       SF 1999-09-01   4245720
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568
167     Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
359         Alex Len       Atlanta Hawks        C 1993-06-16   4160000

[450 rows x 5 columns]

In [16]:
nba.sort_values(["Team", "Name"],
                ascending=[False, True])

                  Name                Team Position   Birthday    Salary
399  Admiral Schofield  Washington Wizards       SF 1997-03-30   1000000
35        Bradley Beal  Washington Wizards       SG 1993-06-28  27093018
353      Chris Chiozza  Washington Wizards       PG 1995-11-21     79568
226      Davis Bertans  Washington Wizards       PF 1992-11-12   7000000
283   Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
..                 ...                 ...      ...        ...       ...
339      Jabari Parker       Atlanta Hawks       PF 1995-03-15   6500000
84        John Collins       Atlanta Hawks       PF 1997-09-23   2686560
20       Kevin Huerter       Atlanta Hawks       SG 1998-08-27   2636280
290     Tyrone Wallace       Atlanta Hawks       PG 1994-06-10   1620564
98        Vince Carter       Atlanta Hawks       PF 1977-01-26   2564753

[450 rows x 5 columns]

In [20]:
nba_top = nba.sort_values(["Team", "Salary"],
                ascending=[True, False])
nba_top

                  Name                Team Position   Birthday    Salary
111   Chandler Parsons       Atlanta Hawks       SF 1988-10-25  25102512
28         Evan Turner       Atlanta Hawks       PG 1988-10-27  18606556
167       Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
213    De'Andre Hunter       Atlanta Hawks       SF 1997-12-02   7068360
339      Jabari Parker       Atlanta Hawks       PF 1995-03-15   6500000
..                 ...                 ...      ...        ...       ...
80         Isaac Bonga  Washington Wizards       PG 1999-11-08   1416852
399  Admiral Schofield  Washington Wizards       SF 1997-03-30   1000000
273    Justin Robinson  Washington Wizards       PG 1997-10-12    898310
283   Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
353      Chris Chiozza  Washington Wizards       PG 1995-11-21     79568

[450 rows x 5 columns]

In [21]:
nba_top.sort_index()

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [22]:
nba.sort_index(ascending = False)

               Name                 Team Position   Birthday    Salary
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
..              ...                  ...      ...        ...       ...
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697

[450 rows x 5 columns]

In [23]:
nba.sort_index(axis = "columns")

      Birthday            Name Position    Salary                 Team
0   1996-09-26    Shake Milton       SG   1445697   Philadelphia 76ers
1   1995-09-27  Christian Wood       PF   1645357      Detroit Pistons
2   1998-08-23   PJ Washington       PF   3831840    Charlotte Hornets
3   1988-10-04    Derrick Rose       PG   7317074      Detroit Pistons
4   1995-07-26   Marial Shayok        G     79568   Philadelphia 76ers
..         ...             ...      ...       ...                  ...
445 1992-08-01   Austin Rivers       PG   2174310      Houston Rockets
446 1998-04-22     Harry Giles       PF   2578800     Sacramento Kings
447 1988-04-01     Robin Lopez        C   4767000      Milwaukee Bucks
448 1999-01-04   Collin Sexton       PG   4764960  Cleveland Cavaliers
449 1990-10-21     Ricky Rubio       PG  16200000         Phoenix Suns

[450 rows x 5 columns]

In [24]:
nba.sort_index(axis = 1) # column-wise

      Birthday            Name Position    Salary                 Team
0   1996-09-26    Shake Milton       SG   1445697   Philadelphia 76ers
1   1995-09-27  Christian Wood       PF   1645357      Detroit Pistons
2   1998-08-23   PJ Washington       PF   3831840    Charlotte Hornets
3   1988-10-04    Derrick Rose       PG   7317074      Detroit Pistons
4   1995-07-26   Marial Shayok        G     79568   Philadelphia 76ers
..         ...             ...      ...       ...                  ...
445 1992-08-01   Austin Rivers       PG   2174310      Houston Rockets
446 1998-04-22     Harry Giles       PF   2578800     Sacramento Kings
447 1988-04-01     Robin Lopez        C   4767000      Milwaukee Bucks
448 1999-01-04   Collin Sexton       PG   4764960  Cleveland Cavaliers
449 1990-10-21     Ricky Rubio       PG  16200000         Phoenix Suns

[450 rows x 5 columns]

In [26]:
nba_top.sort_index(axis = 0) # row-wise

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

# setting index

In [27]:
nba.set_index(keys = "Name")

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [31]:
nba_name = nba.set_index(keys = "Name")
nba_name.columns

Index(['Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [32]:
nba_name['Name']

KeyError: 'Name'

In [33]:
nba_name.reset_index()

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [34]:
nba_name

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [35]:
nba_name_to_original = nba_name.reset_index()

nba_name_to_original

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [36]:
nba2 = nba.set_index("Name")
nba2

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [37]:
nba2.reset_index(inplace=True)    # Useful for the method chaining

In [38]:
nba2

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [39]:
(
    nba
    .set_index("Name")
    .reset_index(inplace=True)
)

In [40]:
# The two lines below are equivalent
nba = nba.set_index("Name")
# nba.set_index("Name", inplace = True)

In [41]:
nba

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [42]:
nba.loc["LeBron James"]

Team         Los Angeles Lakers
Position                     PF
Birthday    1984-12-30 00:00:00
Salary                 37436858
Name: LeBron James, dtype: object

In [43]:
nba.loc[ ["Kawhi Leonard", "Paul George"] ]

                               Team Position   Birthday    Salary
Name
Kawhi Leonard  Los Angeles Clippers       SF 1991-06-29  32742000
Paul George    Los Angeles Clippers       SF 1990-05-02  33005556

In [44]:
nba.loc[ ["LeBron James"] ]

                            Team Position   Birthday    Salary
Name
LeBron James  Los Angeles Lakers       PF 1984-12-30  37436858

In [48]:
(
    nba
    .sort_index()
    .loc[["Otto Porter":"Patrick Beverley"]] # error
)

SyntaxError: invalid syntax (<ipython-input-48-3ef6e3a02a36>, line 4)

In [49]:
(
    nba
    .sort_index()
    .loc["Otto Porter":"Patrick Beverley"]
)

                                  Team Position   Birthday    Salary
Name
Otto Porter              Chicago Bulls       SF 1993-06-03  27250576
PJ Dozier               Denver Nuggets       PG 1996-10-25     79568
PJ Washington        Charlotte Hornets       PF 1998-08-23   3831840
Pascal Siakam          Toronto Raptors       PF 1994-04-02   2351838
Pat Connaughton        Milwaukee Bucks       SG 1993-01-06   1723050
Patrick Beverley  Los Angeles Clippers       PG 1988-07-12  12345680

In [50]:
(
    nba
    .sort_index()
    .loc["Zach Collins":]
)

                                   Team Position   Birthday    Salary
Name
Zach Collins     Portland Trail Blazers        C 1997-11-19   4240200
Zach LaVine               Chicago Bulls       PG 1995-03-10  19500000
Zach Norvell         Los Angeles Lakers       SG 1997-12-09     79568
Zhaire Smith         Philadelphia 76ers       SG 1999-06-04   3058800
Zion Williamson    New Orleans Pelicans        F 2000-07-06   9757440
Zylan Cheatham     New Orleans Pelicans       SF 1995-11-17     79568

In [51]:
(
    nba
    .sort_index()
    .loc[:"Al Horford"]
)

                                    Team Position   Birthday    Salary
Name
Aaron Gordon               Orlando Magic       PF 1995-09-16  19863636
Aaron Holiday             Indiana Pacers       PG 1996-09-30   2239200
Abdel Nader        Oklahoma City Thunder       SF 1993-09-25   1618520
Adam Mokoka                Chicago Bulls        G 1998-07-18     79568
Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
Al Horford            Philadelphia 76ers        C 1986-06-03  28000000

In [52]:
nba.iloc[ 300 ]

Team             Denver Nuggets
Position                     PF
Birthday    1999-04-03 00:00:00
Salary                  1416852
Name: Jarred Vanderbilt, dtype: object

In [53]:

nba.iloc[ [100, 200, 300, 400] ]

                                Team Position   Birthday   Salary
Name
Brian Bowen           Indiana Pacers       SG 1998-10-02    79568
Marco Belinelli    San Antonio Spurs       SF 1986-03-25  5846154
Jarred Vanderbilt     Denver Nuggets       PF 1999-04-03  1416852
Louis King           Detroit Pistons        F 1999-04-06    79568

In [54]:
nba.iloc[0]

Team         Philadelphia 76ers
Position                     SG
Birthday    1996-09-26 00:00:00
Salary                  1445697
Name: Shake Milton, dtype: object

In [55]:
nba

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [56]:
nba.iloc[:2]

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357

# CW 5, 4-7

In [58]:
nfl = pd.read_csv("https://bcdanl.github.io/data/nfl.csv",
                  parse_dates=['Birthday'])
nfl

                    Name                  Team Position   Birthday   Salary
0           Tremon Smith   Philadelphia Eagles       RB 1996-07-20   570000
1         Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
2            Adam Butler  New England Patriots       DT 1994-04-12   645000
3            Derek Wolfe        Denver Broncos       DE 1990-02-24  8000000
4              Jake Ryan  Jacksonville Jaguars      OLB 1992-02-27  1000000
...                  ...                   ...      ...        ...      ...
1650    Bashaud Breeland    Kansas City Chiefs       CB 1992-01-30   805000
1651         Craig James   Philadelphia Eagles       CB 1996-04-29   570000
1652  Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
1653         Chuma Edoga         New York Jets       OT 1997-05-25   495000
1654        Tajae Sharpe      Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 5 columns]

In [59]:
nfl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1655 entries, 0 to 1654
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      1655 non-null   object
 1   Team      1655 non-null   object
 2   Position  1655 non-null   object
 3   Birthday  1655 non-null   datetime64[ns]
 4   Salary    1655 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 64.8+ KB

In [61]:
# Q4

# Who are the five highest-paid players?
nfl.nlargest(5, "Salary", keep = "all")

                 Name                  Team Position   Birthday    Salary
180      Kirk Cousins     Minnesota Vikings       QB 1988-08-19  27500000
905    Marcus Mariota      Tennessee Titans       QB 1993-10-30  20922000
1623   Jameis Winston  Tampa Bay Buccaneers       QB 1994-01-06  20922000
1343       Derek Carr       Oakland Raiders       QB 1991-03-28  19900000
150   Jimmy Garoppolo   San Francisco 49Ers       QB 1991-11-02  17200000

In [62]:
# Who is the oldest player?
nfl.sort_values("Birthday")

                Name                  Team Position   Birthday    Salary
776        Tom Brady  New England Patriots       QB 1977-08-03  14000000
345       Drew Brees    New Orleans Saints       QB 1979-01-15   1400000
1271     Josh McCown   Philadelphia Eagles       QB 1979-07-04   2000000
145      Eli Manning       New York Giants       QB 1981-01-03  11500000
119      Matt Schaub       Atlanta Falcons       QB 1981-06-25   1030000
...              ...                   ...      ...        ...       ...
337   Jalen Thompson     Arizona Cardinals       SS 1998-07-18    495000
685       Devin Bush   Pittsburgh Steelers      ILB 1998-07-18    495000
1467    Travis Homer      Seattle Seahawks       RB 1998-08-07    495000
1574   Irv Smith Jr.     Minnesota Vikings       TE 1998-08-09   1447500
1217     Will Harris         Detroit Lions       SS 1998-12-19    495000

[1655 rows x 5 columns]

In [63]:
# Q5
nfl.sort_values(["Team", "Salary"], ascending=[True, False])

                    Name                 Team Position   Birthday    Salary
1577      Chandler Jones    Arizona Cardinals      OLB 1990-02-27  16500000
669     Patrick Peterson    Arizona Cardinals       CB 1990-07-11  11000000
1361    Larry Fitzgerald    Arizona Cardinals       WR 1983-08-31  11000000
1594       David Johnson    Arizona Cardinals       RB 1991-12-16   5700000
948          Justin Pugh    Arizona Cardinals        G 1990-08-15   5000000
...                  ...                  ...      ...        ...       ...
1109  Ross Pierschbacher  Washington Redskins        C 1995-05-05    495000
1325       Kelvin Harmon  Washington Redskins       WR 1996-12-15    495000
1344          Wes Martin  Washington Redskins        G 1996-05-09    495000
1345      Jimmy Moreland  Washington Redskins       CB 1995-08-26    495000
1509       Jeremy Reaves  Washington Redskins       SS 1996-08-29    495000

[1655 rows x 5 columns]

In [64]:
# Q6
# How do we set the player names as the DataFrame index?

nfl2 = nfl.set_index("Name")
nfl2

                                    Team Position   Birthday   Salary
Name
Tremon Smith         Philadelphia Eagles       RB 1996-07-20   570000
Shawn Williams        Cincinnati Bengals       SS 1991-05-13  3500000
Adam Butler         New England Patriots       DT 1994-04-12   645000
Derek Wolfe               Denver Broncos       DE 1990-02-24  8000000
Jake Ryan           Jacksonville Jaguars      OLB 1992-02-27  1000000
...                                  ...      ...        ...      ...
Bashaud Breeland      Kansas City Chiefs       CB 1992-01-30   805000
Craig James          Philadelphia Eagles       CB 1996-04-29   570000
Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
Chuma Edoga                New York Jets       OT 1997-05-25   495000
Tajae Sharpe            Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 4 columns]

In [65]:
# Q7
# Who is the oldest player on the Kansas City Chiefs roster, and what is his birthday?

nfl.sort_values(["Team", "Birthday"]) # Dustin Colquitt	; 1982-05-06 00:00:00

                  Name                 Team Position   Birthday    Salary
1000          Andy Lee    Arizona Cardinals        P 1982-08-11   2000000
1361  Larry Fitzgerald    Arizona Cardinals       WR 1983-08-31  11000000
583        Brooks Reed    Arizona Cardinals      OLB 1987-02-25   1125000
143       Corey Peters    Arizona Cardinals       NT 1988-06-08   3250000
356       Charles Clay    Arizona Cardinals       TE 1989-02-13   1150000
...                ...                  ...      ...        ...       ...
1620   Geron Christian  Washington Redskins       OT 1996-09-10    647000
1325     Kelvin Harmon  Washington Redskins       WR 1996-12-15    495000
492     Dwayne Haskins  Washington Redskins       QB 1997-05-03    495000
152       Da'ron Payne  Washington Redskins       NT 1997-05-27   1135380
581         Tim Settle  Washington Redskins       NT 1997-07-11    570000

[1655 rows x 5 columns]

In [66]:
q7 = nfl.set_index("Team")

In [67]:
q7.loc["Kansas City Chiefs"].sort_values("Birthday")

                                       Name Position   Birthday    Salary
Team
Kansas City Chiefs          Dustin Colquitt        P 1982-05-06   2450000
Kansas City Chiefs            Terrell Suggs       DE 1982-10-11   3000000
Kansas City Chiefs         James Winchester       LS 1984-03-10    820000
Kansas City Chiefs             LeSean McCoy       RB 1988-07-12   6175000
Kansas City Chiefs          Anthony Sherman       FB 1988-12-11    930000
Kansas City Chiefs        Stefen Wisniewski        G 1989-03-22   1250000
Kansas City Chiefs        Mitchell Schwartz       OT 1989-06-08   6000000
Kansas City Chiefs             Travis Kelce       TE 1989-10-05   7500000
Kansas City Chiefs         Morris Claiborne       CB 1990-02-07   1080000
Kansas City Chiefs          Daniel Sorensen       FS 1990-03-05   3600000
Kansas City Chiefs              Eric Fisher       OT 1991-01-05  10350000
Kansas City Chiefs              Alex Okafor       DE 1991-02-08    805000
Kansas City Chiefs  Laurent Duvernay-Tardif        G 1991-02-11   6203000
Kansas City Chiefs              Mike Pennel       DT 1991-05-09   1000000
Kansas City Chiefs               Blake Bell       TE 1991-08-07    805000
Kansas City Chiefs             Spencer Ware       RB 1991-11-23    805000
Kansas City Chiefs            Austin Reiter        C 1991-11-27    975000
Kansas City Chiefs          Xavier Williams       DT 1992-01-18   2257000
Kansas City Chiefs         Bashaud Breeland       CB 1992-01-30    805000
Kansas City Chiefs          Damien Williams       RB 1992-04-03   1050000
Kansas City Chiefs           Tyrann Mathieu       SS 1992-05-13    850000
Kansas City Chiefs         Anthony Hitchens       LB 1992-06-10   6500000
Kansas City Chiefs           Cameron Erving       OT 1992-08-23   1450000
Kansas City Chiefs         Devaroe Lawrence       DT 1992-10-13    570000
Kansas City Chiefs            Gehrig Dieter       WR 1993-02-24    570000
Kansas City Chiefs            Damien Wilson       LB 1993-05-28    720000
Kansas City Chiefs            Sammy Watkins       WR 1993-06-14  11950000
Kansas City Chiefs              Frank Clark       DE 1993-06-14    805000
Kansas City Chiefs             Jordan Lucas       SS 1993-08-02   2025000
Kansas City Chiefs           Reggie Ragland       LB 1993-09-24   1196551
Kansas City Chiefs            Byron Pringle       WR 1993-11-17    495000
Kansas City Chiefs              Tyreek Hill       WR 1994-03-01   1965036
Kansas City Chiefs         Tanoh Kpassagnon       DE 1994-06-14    832838
Kansas City Chiefs              Chris Jones       NT 1994-07-03   1800000
Kansas City Chiefs             Andrew Wylie        G 1994-08-19    570000
Kansas City Chiefs          Dorian O'Daniel       LB 1994-09-04    584000
Kansas City Chiefs        Demarcus Robinson       WR 1994-09-21   2015500
Kansas City Chiefs               Darron Lee       LB 1994-10-18   1843861
Kansas City Chiefs          Martinas Rankin       OT 1994-10-20    634000
Kansas City Chiefs           Kendall Fuller       CB 1995-02-13   2025000
Kansas City Chiefs              Deon Yelder       TE 1995-03-06    570000
Kansas City Chiefs              Ryan Hunter        G 1995-04-01    495000
Kansas City Chiefs          Harrison Butker        K 1995-07-14    645000
Kansas City Chiefs              Ben Niemann       LB 1995-07-27    570000
Kansas City Chiefs          Patrick Mahomes       QB 1995-09-17    645000
Kansas City Chiefs           Juan Thornhill       FS 1995-10-19    495000
Kansas City Chiefs            Demone Harris       DE 1995-12-30    570000
Kansas City Chiefs            Chris Lammons       CB 1996-01-31    495000
Kansas City Chiefs             Armani Watts       SS 1996-03-19    570000
Kansas City Chiefs          Nick Allegretti        C 1996-04-21    495000
Kansas City Chiefs            Derrick Nnadi       DT 1996-05-09    601500
Kansas City Chiefs          Charvarius Ward       CB 1996-05-16    570000
Kansas City Chiefs          Khalen Saunders       NT 1996-08-09    495000
Kansas City Chiefs          Darwin Thompson       RB 1997-02-12    495000
Kansas City Chiefs            Rashad Fenton       CB 1997-02-17    495000
Kansas City Chiefs           Mecole Hardman       WR 1998-03-12    495000