<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_script_2025_0224.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

netflix = pd.read_csv("https://bcdanl.github.io/data/netflix.csv")
netflix

                      title        director date_added     type
0               Alias Grace             NaN   3-Nov-17  TV Show
1            A Patch of Fog  Michael Lennox  15-Apr-17    Movie
2                  Lunatics             NaN  19-Apr-19  TV Show
3                 Uriyadi 2     Vijay Kumar   2-Aug-19    Movie
4         Shrek the Musical     Jason Moore  29-Dec-13    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola   7-Aug-19    Movie
5833       Hurricane Bianca   Matt Kugelman   1-Jan-17    Movie
5834           Amar's Hands  Khaled Youssef  26-Apr-19    Movie
5835  Bill Nye: Science Guy  Jason Sussberg  25-Apr-18    Movie
5836           Age of Glory             NaN        NaN  TV Show

[5837 rows x 4 columns]

# CW 6.8 Review

In [7]:
(
    netflix
    .query('type == "Movie"')[['date_added']]
    .value_counts()
    .reset_index()
    .query('count == 1')
    .shape[0]
)

425

In [14]:
(
    netflix[['date_added']]
    .drop_duplicates(keep = False)
)

     date_added
4     29-Dec-13
12    31-May-17
30     2-Oct-15
38    25-Aug-19
70    16-Feb-14
...         ...
5748  27-Aug-17
5749  12-Nov-18
5788   7-Oct-17
5789   4-Dec-15
5812  22-Apr-19

[391 rows x 1 columns]

# Reshape

In [22]:
df_wide = pd.DataFrame({
    'Weekday': ['Tuesday', 'Wednesday'],
    'Miami': [80, 83],
    'Rochester': [57, 62],
    'St. Louis': [71, 75]
})

df_long = pd.DataFrame({
    'Weekday': ['Tuesday', 'Wednesday', 'Tuesday', 'Wednesday', 'Tuesday', 'Wednesday'],
    'City': ['Miami', 'Miami', 'Rochester', 'Rochester', 'St. Louis', 'St. Louis'],
    'Temperature': [80, 83, 57, 62, 71, 75]
})

In [23]:
df_wide

     Weekday  Miami  Rochester  St. Louis
0    Tuesday     80         57         71
1  Wednesday     83         62         75

In [17]:
df_long

     Weekday       City  Temperature
0    Tuesday      Miami           80
1  Wednesday      Miami           83
2    Tuesday  Rochester           57
3  Wednesday  Rochester           62
4    Tuesday  St. Louis           71
5  Wednesday  St. Louis           75

In [18]:
df_wide['diff_mia_roc'] = df_wide['Miami'] - df_wide['Rochester']
df_wide

     Weekday  Miami  Rochester  St. Louis  diff_mia_roc
0    Tuesday     80         57         71            23
1  Wednesday     83         62         75            21

In [19]:
df_long['Temperature'].mean()

71.33333333333333

In [24]:
df_wide

     Weekday  Miami  Rochester  St. Louis
0    Tuesday     80         57         71
1  Wednesday     83         62         75

In [25]:
df_wide_to_long = (
    df_wide
    .melt()
)

df_wide_to_long

    variable      value
0    Weekday    Tuesday
1    Weekday  Wednesday
2      Miami         80
3      Miami         83
4  Rochester         57
5  Rochester         62
6  St. Louis         71
7  St. Louis         75

In [26]:
df_wide

     Weekday  Miami  Rochester  St. Louis
0    Tuesday     80         57         71
1  Wednesday     83         62         75

In [27]:
df_wide_to_long = (
    df_wide
    .melt(id_vars = 'Weekday')
)

df_wide_to_long

     Weekday   variable  value
0    Tuesday      Miami     80
1  Wednesday      Miami     83
2    Tuesday  Rochester     57
3  Wednesday  Rochester     62
4    Tuesday  St. Louis     71
5  Wednesday  St. Louis     75

In [28]:
df_wide_to_long = (
    df_wide
    .melt(id_vars = 'Weekday',
          var_name= 'City',
          value_name= 'Temperature')
)

df_wide_to_long

     Weekday       City  Temperature
0    Tuesday      Miami           80
1  Wednesday      Miami           83
2    Tuesday  Rochester           57
3  Wednesday  Rochester           62
4    Tuesday  St. Louis           71
5  Wednesday  St. Louis           75

In [29]:
df_long

     Weekday       City  Temperature
0    Tuesday      Miami           80
1  Wednesday      Miami           83
2    Tuesday  Rochester           57
3  Wednesday  Rochester           62
4    Tuesday  St. Louis           71
5  Wednesday  St. Louis           75

In [31]:
df_long_to_wide = (
    df_long
    .pivot(
        index='Weekday',
        columns='City',
        values='Temperature'
    )
    .reset_index()
)

df_long_to_wide

City    Weekday  Miami  Rochester  St. Louis
0       Tuesday     80         57         71
1     Wednesday     83         62         75

In [32]:
dict_data = {"Name": ["Donna", "Donna", "Mike", "Mike"],
             "Department": ["ECON", "DANL", "ECON", "DANL"],
             "2018": [1, 2, 3, 1],
             "2019": [2, 3, 4, 2],
             "2020": [5, 1, 2, 2]}
df = pd.DataFrame(dict_data)
df

    Name Department  2018  2019  2020
0  Donna       ECON     1     2     5
1  Donna       DANL     2     3     1
2   Mike       ECON     3     4     2
3   Mike       DANL     1     2     2

In [33]:
df_longer = df.melt(id_vars=["Name", "Department"],
                    var_name="Year",
                    value_name="Number of Courses")
df_longer

     Name Department  Year  Number of Courses
0   Donna       ECON  2018                  1
1   Donna       DANL  2018                  2
2    Mike       ECON  2018                  3
3    Mike       DANL  2018                  1
4   Donna       ECON  2019                  2
5   Donna       DANL  2019                  3
6    Mike       ECON  2019                  4
7    Mike       DANL  2019                  2
8   Donna       ECON  2020                  5
9   Donna       DANL  2020                  1
10   Mike       ECON  2020                  2
11   Mike       DANL  2020                  2

In [35]:
(
    df_longer
    .pivot(
        index = ['Name', 'Department'],
        columns= 'Year',
        values= 'Number of Courses'
    )
    .reset_index()
)

Year   Name Department  2018  2019  2020
0     Donna       DANL     2     3     1
1     Donna       ECON     1     2     5
2      Mike       DANL     1     2     2
3      Mike       ECON     3     4     2

# CW 7

## Q1

In [36]:
ny_pincp = pd.read_csv('https://bcdanl.github.io/data/NY_pinc_wide.csv')
ny_pincp

Warning: Total number of columns (53) exceeds max_columns (20). Falling back to pandas display.

,fips,geoname,pincp1969,pincp1970,pincp1971,pincp1972,pincp1973,pincp1974,pincp1975,pincp1976,...,pincp2010,pincp2011,pincp2012,pincp2013,pincp2014,pincp2015,pincp2016,pincp2017,pincp2018,pincp2019
0,36000,New York,4619,4920,5234,5603,6022,6533,7066,7510,...,48973,51496,53986,54501,56758,59243,61401,65814,68657,71717
1,36001,"Albany, NY",4272,4821,5304,5709,6154,6641,7184,7623,...,46559,48417,50190,50809,53790,55793,55805,59640,60637,63037
2,36003,"Allegany, NY",2928,3208,3424,3511,3831,4211,4513,4808,...,28206,28939,30005,29997,31457,32377,32497,34116,34784,36164
3,36005,"Bronx, NY",3632,3839,3999,4199,4497,4894,5373,5633,...,29901,30546,30537,30827,31833,33162,33794,36140,37459,39711
4,36007,"Broome, NY",3895,4153,4412,4700,5061,5517,5991,6393,...,35558,36651,37786,37802,38282,39980,40696,43055,44332,46361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,36115,"Washington, NY",3102,3385,3535,3746,4092,4458,4691,5040,...,31066,32707,33484,34116,35236,35808,36707,39002,40148,42181
59,36117,"Wayne, NY",3752,3854,4086,4342,4871,5408,5803,6140,...,35095,36463,37546,38445,39295,41170,42377,44962,45828,47886
60,36119,"Westchester, NY",6365,6682,7095,7550,8005,8704,9446,10042,...,76051,79996,87602,86452,90438,93819,96620,103808,109324,113477
61,36121,"Wyoming, NY",3360,3534,3803,4226,4705,5041,5351,5592,...,31234,33022,33969,35046,36990,36729,37265,39604,40115,43176
62,36123,"Yates, NY",3293,3497,3767,3898,4502,5149,5467,5736,...,31336,32677,33578,34154,35028,34915,36206,38359,38788,40877

In [37]:
ny_pincp.columns

Index(['fips', 'geoname', 'pincp1969', 'pincp1970', 'pincp1971', 'pincp1972',
       'pincp1973', 'pincp1974', 'pincp1975', 'pincp1976', 'pincp1977',
       'pincp1978', 'pincp1979', 'pincp1980', 'pincp1981', 'pincp1982',
       'pincp1983', 'pincp1984', 'pincp1985', 'pincp1986', 'pincp1987',
       'pincp1988', 'pincp1989', 'pincp1990', 'pincp1991', 'pincp1992',
       'pincp1993', 'pincp1994', 'pincp1995', 'pincp1996', 'pincp1997',
       'pincp1998', 'pincp1999', 'pincp2000', 'pincp2001', 'pincp2002',
       'pincp2003', 'pincp2004', 'pincp2005', 'pincp2006', 'pincp2007',
       'pincp2008', 'pincp2009', 'pincp2010', 'pincp2011', 'pincp2012',
       'pincp2013', 'pincp2014', 'pincp2015', 'pincp2016', 'pincp2017',
       'pincp2018', 'pincp2019'],
      dtype='object')

In [39]:
(
    ny_pincp
    .melt(
        id_vars= ['fips', 'geoname'],
        var_name='year',
        value_name='pincp'
    )
)

       fips          geoname       year   pincp
0     36000         New York  pincp1969    4619
1     36001       Albany, NY  pincp1969    4272
2     36003     Allegany, NY  pincp1969    2928
3     36005        Bronx, NY  pincp1969    3632
4     36007       Broome, NY  pincp1969    3895
...     ...              ...        ...     ...
3208  36115   Washington, NY  pincp2019   42181
3209  36117        Wayne, NY  pincp2019   47886
3210  36119  Westchester, NY  pincp2019  113477
3211  36121      Wyoming, NY  pincp2019   43176
3212  36123        Yates, NY  pincp2019   40877

[3213 rows x 4 columns]