<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_script_2025_0221.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

emp = pd.read_csv("https://bcdanl.github.io/data/employment.csv")
emp

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male     8/6/93       NaN   True     Marketing
1        Thomas    Male    3/31/96   61933.0   True           NaN
2         Maria  Female        NaN  130590.0  False       Finance
3         Jerry     NaN     3/4/05  138705.0   True       Finance
4         Larry    Male    1/24/98  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male    1/31/84   42392.0  False       Finance
997     Russell    Male    5/20/13   96914.0  False       Product
998       Larry    Male    4/20/13   60500.0  False  Business Dev
999      Albert    Male    5/15/12  129949.0   True         Sales
1000        NaN     NaN        NaN       NaN    NaN           NaN

[1001 rows x 6 columns]

In [2]:
emp['Team'].isna()

0       False
1        True
2       False
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000     True
Name: Team, Length: 1001, dtype: bool

In [3]:
emp["Start Date"].isna()

0       False
1       False
2        True
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000     True
Name: Start Date, Length: 1001, dtype: bool

In [4]:
emp['Team'].notna()

0        True
1       False
2        True
3        True
4        True
        ...
996      True
997      True
998      True
999      True
1000    False
Name: Team, Length: 1001, dtype: bool

In [5]:
~emp['Team'].isna()

0        True
1       False
2        True
3        True
4        True
        ...
996      True
997      True
998      True
999      True
1000    False
Name: Team, Length: 1001, dtype: bool

Q. How can we pull out employees with non-missing Team values?

In [6]:
emp[ ~emp['Team'].isna() ]

    First Name  Gender Start Date    Salary   Mgmt          Team
0      Douglas    Male     8/6/93       NaN   True     Marketing
2        Maria  Female        NaN  130590.0  False       Finance
3        Jerry     NaN     3/4/05  138705.0   True       Finance
4        Larry    Male    1/24/98  101004.0   True            IT
5       Dennis    Male    4/18/87  115163.0  False         Legal
..         ...     ...        ...       ...    ...           ...
995      Henry     NaN   11/23/14  132483.0  False  Distribution
996    Phillip    Male    1/31/84   42392.0  False       Finance
997    Russell    Male    5/20/13   96914.0  False       Product
998      Larry    Male    4/20/13   60500.0  False  Business Dev
999     Albert    Male    5/15/12  129949.0   True         Sales

[957 rows x 6 columns]

In [7]:
emp[ ~emp['Team'].isna() ].info()

<class 'pandas.core.frame.DataFrame'>
Index: 957 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  899 non-null    object
 1   Gender      815 non-null    object
 2   Start Date  956 non-null    object
 3   Salary      956 non-null    float64
 4   Mgmt        899 non-null    object
 5   Team        957 non-null    object
dtypes: float64(1), object(5)
memory usage: 52.3+ KB

In [8]:
emp["Mgmt"].isna().sum()

68

In [9]:
emp['Mgmt'].value_counts()

Mgmt
True     468
False    465
Name: count, dtype: int64

In [10]:
emp['Mgmt'].value_counts(dropna= False)

Mgmt
True     468
False    465
NaN       68
Name: count, dtype: int64

In [11]:
emp.dropna()

    First Name  Gender Start Date    Salary   Mgmt          Team
4        Larry    Male    1/24/98  101004.0   True            IT
5       Dennis    Male    4/18/87  115163.0  False         Legal
6         Ruby  Female    8/17/87   65476.0   True       Product
8       Angela  Female   11/22/05   95570.0   True   Engineering
9      Frances  Female     8/8/02  139852.0   True  Business Dev
..         ...     ...        ...       ...    ...           ...
994     George    Male    6/21/13   98874.0   True     Marketing
996    Phillip    Male    1/31/84   42392.0  False       Finance
997    Russell    Male    5/20/13   96914.0  False       Product
998      Larry    Male    4/20/13   60500.0  False  Business Dev
999     Albert    Male    5/15/12  129949.0   True         Sales

[761 rows x 6 columns]

In [12]:
emp.dropna().shape[0]

761

In [13]:
emp.dropna(how="all")

    First Name  Gender Start Date    Salary   Mgmt          Team
0      Douglas    Male     8/6/93       NaN   True     Marketing
1       Thomas    Male    3/31/96   61933.0   True           NaN
2        Maria  Female        NaN  130590.0  False       Finance
3        Jerry     NaN     3/4/05  138705.0   True       Finance
4        Larry    Male    1/24/98  101004.0   True            IT
..         ...     ...        ...       ...    ...           ...
995      Henry     NaN   11/23/14  132483.0  False  Distribution
996    Phillip    Male    1/31/84   42392.0  False       Finance
997    Russell    Male    5/20/13   96914.0  False       Product
998      Larry    Male    4/20/13   60500.0  False  Business Dev
999     Albert    Male    5/15/12  129949.0   True         Sales

[1000 rows x 6 columns]

In [15]:
emp.dropna(subset = ['Gender']).info()

<class 'pandas.core.frame.DataFrame'>
Index: 854 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  794 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  853 non-null    object
 3   Salary      853 non-null    float64
 4   Mgmt        794 non-null    object
 5   Team        815 non-null    object
dtypes: float64(1), object(5)
memory usage: 46.7+ KB

In [16]:
emp.dropna(subset = ["Start Date", "Salary"])

    First Name  Gender Start Date    Salary   Mgmt          Team
1       Thomas    Male    3/31/96   61933.0   True           NaN
3        Jerry     NaN     3/4/05  138705.0   True       Finance
4        Larry    Male    1/24/98  101004.0   True            IT
5       Dennis    Male    4/18/87  115163.0  False         Legal
6         Ruby  Female    8/17/87   65476.0   True       Product
..         ...     ...        ...       ...    ...           ...
995      Henry     NaN   11/23/14  132483.0  False  Distribution
996    Phillip    Male    1/31/84   42392.0  False       Finance
997    Russell    Male    5/20/13   96914.0  False       Product
998      Larry    Male    4/20/13   60500.0  False  Business Dev
999     Albert    Male    5/15/12  129949.0   True         Sales

[998 rows x 6 columns]

In [17]:
emp.dropna(subset = ["Start Date", "Salary"]).info()

<class 'pandas.core.frame.DataFrame'>
Index: 998 entries, 1 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  931 non-null    object
 1   Gender      852 non-null    object
 2   Start Date  998 non-null    object
 3   Salary      998 non-null    float64
 4   Mgmt        931 non-null    object
 5   Team        955 non-null    object
dtypes: float64(1), object(5)
memory usage: 54.6+ KB

# Duplicates

In [18]:
emp['Team'].duplicated()

0       False
1       False
2       False
3        True
4       False
        ...
996      True
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [19]:
emp

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male     8/6/93       NaN   True     Marketing
1        Thomas    Male    3/31/96   61933.0   True           NaN
2         Maria  Female        NaN  130590.0  False       Finance
3         Jerry     NaN     3/4/05  138705.0   True       Finance
4         Larry    Male    1/24/98  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male    1/31/84   42392.0  False       Finance
997     Russell    Male    5/20/13   96914.0  False       Product
998       Larry    Male    4/20/13   60500.0  False  Business Dev
999      Albert    Male    5/15/12  129949.0   True         Sales
1000        NaN     NaN        NaN       NaN    NaN           NaN

[1001 rows x 6 columns]

In [20]:
emp['Team'].duplicated()

0       False
1       False
2       False
3        True
4       False
        ...
996      True
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [21]:
emp['Team'].duplicated(keep = "first")

0       False
1       False
2       False
3        True
4       False
        ...
996      True
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [22]:
emp['Team'].duplicated(keep = "last")

0        True
1        True
2        True
3        True
4        True
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Team, Length: 1001, dtype: bool

In [23]:
~emp['Team'].duplicated()

0        True
1        True
2        True
3       False
4        True
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Team, Length: 1001, dtype: bool

In [24]:
emp['Team'].duplicated()

0       False
1       False
2       False
3        True
4       False
        ...
996      True
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [25]:
emp.drop_duplicates()

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male     8/6/93       NaN   True     Marketing
1        Thomas    Male    3/31/96   61933.0   True           NaN
2         Maria  Female        NaN  130590.0  False       Finance
3         Jerry     NaN     3/4/05  138705.0   True       Finance
4         Larry    Male    1/24/98  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male    1/31/84   42392.0  False       Finance
997     Russell    Male    5/20/13   96914.0  False       Product
998       Larry    Male    4/20/13   60500.0  False  Business Dev
999      Albert    Male    5/15/12  129949.0   True         Sales
1000        NaN     NaN        NaN       NaN    NaN           NaN

[1001 rows x 6 columns]

In [26]:
# Sample DataFrame with duplicate observations
data = {
    'Name': ['John', 'Anna', 'John', 'Mike', 'Anna'],
    'Age': [28, 23, 28, 32, 23],
    'City': ['New York', 'Paris', 'New York', 'London', 'Paris']
}

# pd.DataFrame( Series, List, or Dict ) creates a DataFrame
df = pd.DataFrame(data)
df

   Name  Age      City
0  John   28  New York
1  Anna   23     Paris
2  John   28  New York
3  Mike   32    London
4  Anna   23     Paris

In [27]:
df.drop_duplicates()

   Name  Age      City
0  John   28  New York
1  Anna   23     Paris
3  Mike   32    London

In [28]:
emp.drop_duplicates(subset = ['Team'])

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male     8/6/93       NaN   True     Marketing
1      Thomas    Male    3/31/96   61933.0   True           NaN
2       Maria  Female        NaN  130590.0  False       Finance
4       Larry    Male    1/24/98  101004.0   True            IT
5      Dennis    Male    4/18/87  115163.0  False         Legal
6        Ruby  Female    8/17/87   65476.0   True       Product
8      Angela  Female   11/22/05   95570.0   True   Engineering
9     Frances  Female     8/8/02  139852.0   True  Business Dev
12    Brandon    Male    12/1/80  112807.0   True            HR
13       Gary    Male    1/27/08  109831.0  False         Sales
40    Michael    Male   10/10/08   99283.0   True  Distribution

In [29]:
emp

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male     8/6/93       NaN   True     Marketing
1        Thomas    Male    3/31/96   61933.0   True           NaN
2         Maria  Female        NaN  130590.0  False       Finance
3         Jerry     NaN     3/4/05  138705.0   True       Finance
4         Larry    Male    1/24/98  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male    1/31/84   42392.0  False       Finance
997     Russell    Male    5/20/13   96914.0  False       Product
998       Larry    Male    4/20/13   60500.0  False  Business Dev
999      Albert    Male    5/15/12  129949.0   True         Sales
1000        NaN     NaN        NaN       NaN    NaN           NaN

[1001 rows x 6 columns]

In [30]:
emp.drop_duplicates(subset = ['Gender', 'Team'])

    First Name  Gender Start Date    Salary   Mgmt          Team
0      Douglas    Male     8/6/93       NaN   True     Marketing
1       Thomas    Male    3/31/96   61933.0   True           NaN
2        Maria  Female        NaN  130590.0  False       Finance
3        Jerry     NaN     3/4/05  138705.0   True       Finance
4        Larry    Male    1/24/98  101004.0   True            IT
5       Dennis    Male    4/18/87  115163.0  False         Legal
6         Ruby  Female    8/17/87   65476.0   True       Product
8       Angela  Female   11/22/05   95570.0   True   Engineering
9      Frances  Female     8/8/02  139852.0   True  Business Dev
10      Louise  Female    8/12/80   63241.0   True           NaN
11       Julie  Female   10/26/97  102508.0   True         Legal
12     Brandon    Male    12/1/80  112807.0   True            HR
13        Gary    Male    1/27/08  109831.0  False         Sales
17       Shawn    Male    12/7/86  111737.0  False       Product
18       Diana  Female   10/23/81  132940.0  False            IT
20        Lois     NaN    4/22/95   64714.0   True         Legal
22      Joshua     NaN     3/8/12   90816.0   True            IT
31       Joyce     NaN    2/20/05   88657.0  False       Product
35     Theresa  Female   10/10/06   85182.0  False         Sales
40     Michael    Male   10/10/08   99283.0   True  Distribution
41   Christine     NaN    6/28/15   66582.0   True  Business Dev
43     Marilyn  Female    12/7/80   73524.0   True     Marketing
46       Bruce    Male   11/28/09  114796.0  False       Finance
48    Clarence    Male    3/26/96   93581.0   True  Business Dev
49       Chris     NaN    1/24/80  113590.0  False         Sales
60       Paula     NaN   11/23/05   48866.0  False  Distribution
75      Bonnie  Female     7/2/91  104897.0   True            HR
76    Margaret  Female    9/10/88  131604.0   True  Distribution
91       James     NaN    1/26/05  128771.0  False           NaN
97       Laura     NaN    7/19/14  140371.0   True     Marketing
143     Teresa     NaN    1/28/16  140013.0   True   Engineering
171    Patrick    Male    8/17/07  143499.0   True   Engineering
239    Lillian     NaN    5/12/16   64164.0  False            HR

In [31]:
emp.drop_duplicates(subset = ['Team'])

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male     8/6/93       NaN   True     Marketing
1      Thomas    Male    3/31/96   61933.0   True           NaN
2       Maria  Female        NaN  130590.0  False       Finance
4       Larry    Male    1/24/98  101004.0   True            IT
5      Dennis    Male    4/18/87  115163.0  False         Legal
6        Ruby  Female    8/17/87   65476.0   True       Product
8      Angela  Female   11/22/05   95570.0   True   Engineering
9     Frances  Female     8/8/02  139852.0   True  Business Dev
12    Brandon    Male    12/1/80  112807.0   True            HR
13       Gary    Male    1/27/08  109831.0  False         Sales
40    Michael    Male   10/10/08   99283.0   True  Distribution

In [32]:
emp.drop_duplicates(subset = ['Team'], keep = 'last')

     First Name  Gender Start Date    Salary   Mgmt          Team
988       Alice  Female    10/5/04   47638.0  False            HR
989      Justin     NaN    2/10/91   38344.0  False         Legal
990       Robin  Female    7/24/87  100765.0   True            IT
993        Tina  Female    5/15/97   56450.0   True   Engineering
994      George    Male    6/21/13   98874.0   True     Marketing
995       Henry     NaN   11/23/14  132483.0  False  Distribution
996     Phillip    Male    1/31/84   42392.0  False       Finance
997     Russell    Male    5/20/13   96914.0  False       Product
998       Larry    Male    4/20/13   60500.0  False  Business Dev
999      Albert    Male    5/15/12  129949.0   True         Sales
1000        NaN     NaN        NaN       NaN    NaN           NaN

In [33]:
emp.drop_duplicates(subset = ['Team'], keep = False)

Empty DataFrame
Columns: [First Name, Gender, Start Date, Salary, Mgmt, Team]
Index: []

In [34]:
emp.drop_duplicates(subset=['First Name'], keep = False)

    First Name  Gender Start Date    Salary   Mgmt          Team
5       Dennis    Male    4/18/87  115163.0  False         Legal
8       Angela  Female   11/22/05   95570.0   True   Engineering
33        Jean  Female   12/18/93  119082.0  False  Business Dev
190      Carol  Female    3/19/96   57783.0  False       Finance
291      Tammy  Female   11/11/84  132839.0   True            IT
495     Eugene    Male    5/24/84   81077.0  False         Sales
688      Brian    Male     4/7/07   93901.0   True         Legal
832      Keith    Male    2/12/03  120672.0  False         Legal
887      David    Male    12/5/09   92242.0  False         Legal

In [35]:
emp[emp['First Name']=="David"]

    First Name Gender Start Date   Salary   Mgmt   Team
887      David   Male    12/5/09  92242.0  False  Legal

In [36]:
emp[emp['First Name']=="Keith"]

    First Name Gender Start Date    Salary   Mgmt   Team
832      Keith   Male    2/12/03  120672.0  False  Legal

Find a subset of all employees with a First Name of “Douglas” and a Gender of “Male”.

In [37]:
emp[(emp['First Name'] == "Douglas") & (emp['Gender'] == "Male")]

    First Name Gender Start Date    Salary   Mgmt         Team
0      Douglas   Male     8/6/93       NaN   True    Marketing
217    Douglas   Male     9/3/99   83341.0   True           IT
322    Douglas   Male     1/8/02   41428.0  False      Product
835    Douglas   Male     8/4/07  132175.0  False  Engineering

In [38]:
emp.drop_duplicates(subset = ["Gender", "Team"])

    First Name  Gender Start Date    Salary   Mgmt          Team
0      Douglas    Male     8/6/93       NaN   True     Marketing
1       Thomas    Male    3/31/96   61933.0   True           NaN
2        Maria  Female        NaN  130590.0  False       Finance
3        Jerry     NaN     3/4/05  138705.0   True       Finance
4        Larry    Male    1/24/98  101004.0   True            IT
5       Dennis    Male    4/18/87  115163.0  False         Legal
6         Ruby  Female    8/17/87   65476.0   True       Product
8       Angela  Female   11/22/05   95570.0   True   Engineering
9      Frances  Female     8/8/02  139852.0   True  Business Dev
10      Louise  Female    8/12/80   63241.0   True           NaN
11       Julie  Female   10/26/97  102508.0   True         Legal
12     Brandon    Male    12/1/80  112807.0   True            HR
13        Gary    Male    1/27/08  109831.0  False         Sales
17       Shawn    Male    12/7/86  111737.0  False       Product
18       Diana  Female   10/23/81  132940.0  False            IT
20        Lois     NaN    4/22/95   64714.0   True         Legal
22      Joshua     NaN     3/8/12   90816.0   True            IT
31       Joyce     NaN    2/20/05   88657.0  False       Product
35     Theresa  Female   10/10/06   85182.0  False         Sales
40     Michael    Male   10/10/08   99283.0   True  Distribution
41   Christine     NaN    6/28/15   66582.0   True  Business Dev
43     Marilyn  Female    12/7/80   73524.0   True     Marketing
46       Bruce    Male   11/28/09  114796.0  False       Finance
48    Clarence    Male    3/26/96   93581.0   True  Business Dev
49       Chris     NaN    1/24/80  113590.0  False         Sales
60       Paula     NaN   11/23/05   48866.0  False  Distribution
75      Bonnie  Female     7/2/91  104897.0   True            HR
76    Margaret  Female    9/10/88  131604.0   True  Distribution
91       James     NaN    1/26/05  128771.0  False           NaN
97       Laura     NaN    7/19/14  140371.0   True     Marketing
143     Teresa     NaN    1/28/16  140013.0   True   Engineering
171    Patrick    Male    8/17/07  143499.0   True   Engineering
239    Lillian     NaN    5/12/16   64164.0  False            HR

In [39]:
emp.drop_duplicates(subset = ["Gender", "Team"]).query("`First Name` == 'Douglas' ")

  First Name Gender Start Date  Salary  Mgmt       Team
0    Douglas   Male     8/6/93     NaN  True  Marketing

# CW 6

In [41]:
netflix = pd.read_csv("https://bcdanl.github.io/data/netflix.csv")

In [42]:
netflix

                      title        director date_added     type
0               Alias Grace             NaN   3-Nov-17  TV Show
1            A Patch of Fog  Michael Lennox  15-Apr-17    Movie
2                  Lunatics             NaN  19-Apr-19  TV Show
3                 Uriyadi 2     Vijay Kumar   2-Aug-19    Movie
4         Shrek the Musical     Jason Moore  29-Dec-13    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola   7-Aug-19    Movie
5833       Hurricane Bianca   Matt Kugelman   1-Jan-17    Movie
5834           Amar's Hands  Khaled Youssef  26-Apr-19    Movie
5835  Bill Nye: Science Guy  Jason Sussberg  25-Apr-18    Movie
5836           Age of Glory             NaN        NaN  TV Show

[5837 rows x 4 columns]

## Q1
Optimize the DataFrame for limited memory use and maximum utility by using the astype() method.

In [43]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   object
 3   type        5837 non-null   object
dtypes: object(4)
memory usage: 182.5+ KB

In [44]:
netflix['title'].nunique()

5780

In [45]:
netflix['director'].nunique()

3024

In [46]:
netflix['type'].nunique()

2

In [48]:
netflix = (
    netflix
    .astype(
        {
            'date_added': 'datetime64[ns]',
            'type': 'category'
        }
    )
)

In [49]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(1), datetime64[ns](1), object(2)
memory usage: 142.8+ KB

# Q2
Find all observations with a director of “Martin Scorsese”.

In [50]:
netflix.query("director == 'Martin Scorsese'") # single quote '' and double quotes ""

,title,director,date_added,type
186,Raging Bull,Martin Scorsese,2019-10-01,Movie
367,Gangs of New York,Martin Scorsese,2019-08-20,Movie
1139,Mean Streets,Martin Scorsese,2019-07-01,Movie
1251,Taxi Driver,Martin Scorsese,2019-07-01,Movie
3227,Rolling Thunder Revue: A Bob Dylan Story by Ma...,Martin Scorsese,2019-06-12,Movie
4804,Who's That Knocking at My Door?,Martin Scorsese,2019-07-01,Movie
5319,Alice Doesn't Live Here Anymore,Martin Scorsese,2019-07-01,Movie
5416,The Irishman,Martin Scorsese,2019-11-27,Movie

In [51]:
netflix.query('director == "Martin Scorsese"')

,title,director,date_added,type
186,Raging Bull,Martin Scorsese,2019-10-01,Movie
367,Gangs of New York,Martin Scorsese,2019-08-20,Movie
1139,Mean Streets,Martin Scorsese,2019-07-01,Movie
1251,Taxi Driver,Martin Scorsese,2019-07-01,Movie
3227,Rolling Thunder Revue: A Bob Dylan Story by Ma...,Martin Scorsese,2019-06-12,Movie
4804,Who's That Knocking at My Door?,Martin Scorsese,2019-07-01,Movie
5319,Alice Doesn't Live Here Anymore,Martin Scorsese,2019-07-01,Movie
5416,The Irishman,Martin Scorsese,2019-11-27,Movie

# Q3
Find all observations with a title of “Limitless” and a type of “Movie”.

In [52]:
netflix[ (netflix['title'] == "Limitless") & (netflix['type'] == 'Movie' ) ]

          title         director date_added   type
1559  Limitless      Neil Burger 2019-05-16  Movie
4579  Limitless  Vrinda Samartha 2019-10-01  Movie

# Q4
Find all observations with either a date_added of “2018-06-15” or a director of “Bong Joon Ho”.

In [53]:
netflix.query("date_added == '2018-06-15' | director == 'Bong Joon Ho'")

<ipython-input-53-bfd4b76b1189>:1: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  netflix.query("date_added == '2018-06-15' | director == 'Bong Joon Ho'")

,title,director,date_added,type
11,LEGO House - Home of the Brick,Anders Falck,2018-06-15,Movie
151,Lust Stories,Zoya Akhtar,2018-06-15,Movie
699,Pacificum: Return to the Ocean,Mariana Tschudi,2018-06-15,Movie
1008,Set It Up,Claire Scanlon,2018-06-15,Movie
1651,True: Wonderful Wishes,NaN,2018-06-15,TV Show
1992,The last hour,Eduardo Mendoza de Echave,2018-06-15,Movie
2552,True: Magical Friends,NaN,2018-06-15,TV Show
3657,Sunday's Illness,Ramón Salazar,2018-06-15,Movie
3755,Maktub,Oded Raz,2018-06-15,Movie
4098,Chronicle of an Escape,Israel Adrián Caetano,2018-06-15,Movie
4409,Okja,Bong Joon Ho,2017-06-28,Movie
4665,Snowpiercer,Bong Joon Ho,2019-05-01,Movie

# Q5
Find all observations with a director of “Ethan Coen”, “Joel Coen”, and “Quentin Tarantino”.

In [56]:
cond = netflix['director'].isin(["Ethan Coen", "Joel Coen", "Quentin Tarantino"])
netflix[ cond ]

,title,director,date_added,type
765,A Serious Man,Ethan Coen,2018-01-16,Movie
1057,Inglourious Basterds,Quentin Tarantino,2019-07-22,Movie
1090,The Hateful Eight: Extended Version,Quentin Tarantino,2019-04-25,TV Show
1330,The Ballad of Buster Scruggs,Joel Coen,2018-11-16,Movie
2025,The Hateful Eight,Quentin Tarantino,2017-10-25,Movie
3060,Pulp Fiction,Quentin Tarantino,2019-01-01,Movie
4116,Jackie Brown,Quentin Tarantino,2019-08-01,Movie

# Q6
Find all observations with a date_added value between January 1, 2019 and February 1, 2019.

In [57]:
cond = netflix['date_added'].between('2019-01-01', '2019-02-01')
netflix[cond]

,title,director,date_added,type
31,Good Girls,NaN,2019-01-01,TV Show
34,Sebastian Maniscalco: Stay Hungry,Rik Reinholdtsen,2019-01-15,Movie
40,The Big Catch,NaN,2019-02-01,TV Show
125,Malicious,Michael Winnick,2019-02-01,Movie
137,About a Boy,Chris Weitz,2019-02-01,Movie
...,...,...,...,...
5661,Swiss Army Man,Dan Kwan,2019-01-30,Movie
5698,Occupation,Luke Sparke,2019-01-03,Movie
5713,Sword Art Online Alternative: Gun Gale Online,NaN,2019-02-01,TV Show
5742,Chupan Chupai,Mohsin Ali,2019-01-15,Movie
5805,Velvet Buzzsaw,Dan Gilroy,2019-02-01,Movie

# Q7
Drop all observations with a NaN value in the director variable.

In [58]:
# 1. fitering
netflix[ ~netflix['director'].isna() ]

                                   title        director date_added   type
1                         A Patch of Fog  Michael Lennox 2017-04-15  Movie
3                              Uriyadi 2     Vijay Kumar 2019-08-02  Movie
4                      Shrek the Musical     Jason Moore 2013-12-29  Movie
5                       Schubert In Love     Lars Büchel 2018-03-01  Movie
6     We Have Always Lived in the Castle   Stacie Passon 2019-09-14  Movie
...                                  ...             ...        ...    ...
5830                         Bibi & Tina     Detlev Buck 2017-04-15  Movie
5832                         The Pursuit     John Papola 2019-08-07  Movie
5833                    Hurricane Bianca   Matt Kugelman 2017-01-01  Movie
5834                        Amar's Hands  Khaled Youssef 2019-04-26  Movie
5835               Bill Nye: Science Guy  Jason Sussberg 2018-04-25  Movie

[3936 rows x 4 columns]

In [60]:
netflix[ ~netflix['director'].isna() ].info()

<class 'pandas.core.frame.DataFrame'>
Index: 3936 entries, 1 to 5835
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       3936 non-null   object
 1   director    3936 non-null   object
 2   date_added  3901 non-null   datetime64[ns]
 3   type        3936 non-null   category
dtypes: category(1), datetime64[ns](1), object(2)
memory usage: 127.0+ KB

In [61]:
# 2. dropna
netflix.dropna(subset = ['director'])

                                   title        director date_added   type
1                         A Patch of Fog  Michael Lennox 2017-04-15  Movie
3                              Uriyadi 2     Vijay Kumar 2019-08-02  Movie
4                      Shrek the Musical     Jason Moore 2013-12-29  Movie
5                       Schubert In Love     Lars Büchel 2018-03-01  Movie
6     We Have Always Lived in the Castle   Stacie Passon 2019-09-14  Movie
...                                  ...             ...        ...    ...
5830                         Bibi & Tina     Detlev Buck 2017-04-15  Movie
5832                         The Pursuit     John Papola 2019-08-07  Movie
5833                    Hurricane Bianca   Matt Kugelman 2017-01-01  Movie
5834                        Amar's Hands  Khaled Youssef 2019-04-26  Movie
5835               Bill Nye: Science Guy  Jason Sussberg 2018-04-25  Movie

[3936 rows x 4 columns]

# Q8
Identify the days when Netflix added only one movie to its catalog.

In [68]:
(
    netflix
    .query('type == "Movie"')['date_added']
    .value_counts()
    .reset_index()
    .query('count == 1')
    .shape[0]
)

425