In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('https://bcdanl.github.io/data/concat_1.csv')
df2 = pd.read_csv('https://bcdanl.github.io/data/concat_2.csv')
df3 = pd.read_csv('https://bcdanl.github.io/data/concat_3.csv')

In [3]:
df1

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [4]:
df2

    A   B   C   D
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7

In [5]:
df3

     A    B    C    D
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [6]:
pd.concat([df1, df2, df3])

     A    B    C    D
0   a0   b0   c0   d0
1   a1   b1   c1   d1
2   a2   b2   c2   d2
3   a3   b3   c3   d3
0   a4   b4   c4   d4
1   a5   b5   c5   d5
2   a6   b6   c6   d6
3   a7   b7   c7   d7
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [7]:
pd.concat([df1, df2, df3], axis = 1) # axis = "columns"

    A   B   C   D   A   B   C   D    A    B    C    D
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

In [9]:
pd.concat([df1, df2, df3], axis = 1, ignore_index = True)

   0   1   2   3   4   5   6   7    8    9    10   11
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

In [10]:
pd.concat([df1, df2, df3], ignore_index = True)

      A    B    C    D
0    a0   b0   c0   d0
1    a1   b1   c1   d1
2    a2   b2   c2   d2
3    a3   b3   c3   d3
4    a4   b4   c4   d4
5    a5   b5   c5   d5
6    a6   b6   c6   d6
7    a7   b7   c7   d7
8    a8   b8   c8   d8
9    a9   b9   c9   d9
10  a10  b10  c10  d10
11  a11  b11  c11  d11

In [11]:
new_row_series = pd.Series(['n1', 'n2', 'n3', 'n4'])
new_row_series

0    n1
1    n2
2    n3
3    n4
dtype: object

In [12]:
pd.concat([df1, new_row_series])

     A    B    C    D    0
0   a0   b0   c0   d0  NaN
1   a1   b1   c1   d1  NaN
2   a2   b2   c2   d2  NaN
3   a3   b3   c3   d3  NaN
0  NaN  NaN  NaN  NaN   n1
1  NaN  NaN  NaN  NaN   n2
2  NaN  NaN  NaN  NaN   n3
3  NaN  NaN  NaN  NaN   n4

In [13]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [14]:
df1.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [16]:
new_df = pd.DataFrame(data = [ ['n1', 'n2', 'n3', 'n4'] ] ,
                      columns = df1.columns)
new_df

    A   B   C   D
0  n1  n2  n3  n4

In [17]:
pd.concat([df1, new_df])

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
0  n1  n2  n3  n4

In [18]:
pd.concat([df1, new_row_series])

     A    B    C    D    0
0   a0   b0   c0   d0  NaN
1   a1   b1   c1   d1  NaN
2   a2   b2   c2   d2  NaN
3   a3   b3   c3   d3  NaN
0  NaN  NaN  NaN  NaN   n1
1  NaN  NaN  NaN  NaN   n2
2  NaN  NaN  NaN  NaN   n3
3  NaN  NaN  NaN  NaN   n4

In [19]:
pd.concat([df1, new_row_series], axis = "columns")

    A   B   C   D   0
0  a0  b0  c0  d0  n1
1  a1  b1  c1  d1  n2
2  a2  b2  c2  d2  n3
3  a3  b3  c3  d3  n4

# CW7. Part 3

In [20]:
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'],
        'marks': [201, 200, 198, 219, 201]})

In [21]:
student_data1

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199

In [22]:
student_data2

  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

In [23]:
# Q6

pd.concat([student_data1, student_data2])

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

In [ ]:
# Q7

pd.concat([student_data1, student_data2], axis = 1)

In [24]:
pd.concat([student_data1, student_data2], axis = "columns")

  student_id              name  marks student_id              name  marks
0         S1  Danniella Fenton    200         S4  Scarlette Fisher    201
1         S2      Ryder Storey    210         S5  Carla Williamson    200
2         S3      Bryce Jensen    190         S6       Dante Morse    198
3         S4         Ed Bernal    222         S7    Kaiser William    219
4         S5       Kwame Morin    199         S8   Madeeha Preston    201

In [25]:
pd.concat([student_data1, student_data2], axis = 0)

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

In [26]:
pd.concat([student_data1, student_data2], axis = "index")

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

In [28]:
# Q8
s6 = pd.Series(['S6', 'Scarlette Fisher', 205], index=['student_id', 'name', 'marks'])
s6

student_id                  S6
name          Scarlette Fisher
marks                      205
dtype: object

In [29]:
student_data1

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199

In [30]:
pd.concat([student_data1, s6])

           student_id              name  marks                 0
0                  S1  Danniella Fenton  200.0               NaN
1                  S2      Ryder Storey  210.0               NaN
2                  S3      Bryce Jensen  190.0               NaN
3                  S4         Ed Bernal  222.0               NaN
4                  S5       Kwame Morin  199.0               NaN
student_id        NaN               NaN    NaN                S6
name              NaN               NaN    NaN  Scarlette Fisher
marks             NaN               NaN    NaN               205

In [31]:
s6

student_id                  S6
name          Scarlette Fisher
marks                      205
dtype: object

In [33]:
s6_df = pd.DataFrame(s6)
s6_df

                           0
student_id                S6
name        Scarlette Fisher
marks                    205

In [34]:
pd.concat([student_data1, s6_df])

           student_id              name  marks                 0
0                  S1  Danniella Fenton  200.0               NaN
1                  S2      Ryder Storey  210.0               NaN
2                  S3      Bryce Jensen  190.0               NaN
3                  S4         Ed Bernal  222.0               NaN
4                  S5       Kwame Morin  199.0               NaN
student_id        NaN               NaN    NaN                S6
name              NaN               NaN    NaN  Scarlette Fisher
marks             NaN               NaN    NaN               205

In [35]:
s6_df.T

  student_id              name marks
0         S6  Scarlette Fisher   205

In [38]:
pd.concat([student_data1, s6_df.T], ignore_index = True)

  student_id              name marks
0         S1  Danniella Fenton   200
1         S2      Ryder Storey   210
2         S3      Bryce Jensen   190
3         S4         Ed Bernal   222
4         S5       Kwame Morin   199
5         S6  Scarlette Fisher   205